### ISSUE TITLE
Change Maven group ID to org.jline

### ISSUE THREAD

**Issue by Minecrell** [jline/jline3#1]
Now that the Java package was changed to `org.jline` it would make sense (in my opinion) to follow the same conventions for the Maven group ID and change it to use a proper identifier like `org.jline`.

A lot of projects were using the Maven coordinates like jline before, but most projects (e.g. Apache commons-lang) switched to the new conventions after a major version jump.

**Comment by gnodet** [comment]
Yes, that makes sense.
