### ISSUE TITLE
Not able to resetPrompt like in JLine2

### ISSUE THREAD

**Issue by stanroze** [jline/jline3#10]
Perhaps I'm doing something wrong, but I'm not able to reset the prompt to keep moving it down below another threads output.

`//this returns empty buffer even though something has been typed in
BufferImpl buffer = this.reader.getBuffer();`

**Comment by gnodet** [comment]
Have you tried with a 3.0.1 ?
I'm not sure what you're trying to achieve exactly but `reader.getBuffer()`  should contain whatever is displayed by the reader.

**Comment by gnodet** [comment]
Reopen if needed, but you'd have to provide more informations.
