### ISSUE TITLE
Keep Java running after closing terminal window

### ISSUE THREAD

**Issue by wise-coders** [jline/jline3#1009]
My terminal application can start a Jetty server. I want to keep Java running after the terminal console is closed, if the server is started.
How can I do this?

I am also getting a deprecated message regarding JNA. I use the latest libraries with OpenJDK 17.
I saw I can use JNI with no additional libraries, but this require 'loading a native library.' How can I do this? 
There are no details on [this page](https://github.com/jline/jline3)

**Comment by gnodet** [comment]
> My terminal application can start a Jetty server. I want to keep Java running after the terminal console is closed, if the server is started. How can I do this?

That's tricky problem. See https://stackoverflow.com/questions/36498713/preventing-child-jvm-from-exiting-when-its-parent-jvm-exits
I solved the problem in mvnd with https://github.com/apache/maven-mvnd/blob/d3cc476ae3b942ba3d536747e0cb89024ed96e6c/daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java#L109-L121

> I am also getting a deprecated message regarding JNA. I use the latest libraries with OpenJDK 17. I saw I can use JNI with no additional libraries, but this require 'loading a native library.' How can I do this? There are no details on [this page](https://github.com/jline/jline3)

That's because there's nothing to do, just add `jline-terminal-jni` in your class path.

**Comment by wise-coders** [comment]
The Jetty is started from jline, as a license server. I want the license server to continue to run after the terminal window is closed (from the window x). Is this possible?
I tried a Thread.join() to Jetty thread pool after the readLine in a similar example as here, but it didn't work: https://github.com/jline/jline3/blob/master/demo/src/main/java/org/jline/demo/TerminalDemo.java

**Comment by gnodet** [comment]
Your problem is unrelated to JLine.
You need to fork a JVM to launch jetty, or make sure it's already launched without a parent (using `nohup` for example).
