### ISSUE TITLE
Make it possible to cancel console-ui prompts

### ISSUE THREAD

**Issue by quintesse** [jline/jline3#1035]
Right now you can only EXIT by making a selection or hitting enter, etc. It would be nice to be able to cancel out of a prompt, for example by using the escape key.

Doing that by default might not be backward-compatible, but perhaps we could add a `.cancelable(true)` option to the prompt builders which would then add an extra CANCEL action to the prompt's key bindings. If the user then hits the escape key we could have the prompt return `null` to indicate that the prompt was cancelled..

If there's interest for this feature I could try to create a PR for it.

**Comment by gnodet** [comment]
@mattirn ?

**Comment by mattirn** [comment]
@quintesse, I think that the possibility canceling prompts would be nice to have...  I wrote an other similar ticket #1042 if you are interested to create PR also for it.

**Comment by quintesse** [comment]
hi @mattirn , that's indeed an issue that's very related to this one! In fact ESC could simply be used to cancel the current question, which would then mean returning to the previous one. And only when you hit ESC on the first question would we exit. That seems like a good way to fix both issues.
