### ISSUE TITLE
Unable to create a system terminal

### ISSUE THREAD

**Issue by YiZhiMCQiu** [jline/jline3#1048]
My version is 3.26.2 JDK 21.0.2. I'm creating a terminal using TerminalBuilder.terminal(). This error appears after running:

7月 28, 2024 8:12:01 上午 org.jline.utils.Log logr
警告: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

**Comment by mattirn** [comment]
@YiZhiMCQiu , which OS and terminal you use to launch your app?

**Comment by YiZhiMCQiu** [comment]
@mattirn emmm... I use IntelliJ IDEA and booting with CMD is fine. Thanks!
