### ISSUE TITLE
JLine Start Webserver and Continue to Run After Console is Closed

### ISSUE THREAD

**Issue by wise-coders** [jline/jline3#1102]
I use JLine for a command-prompt application, which can start a web server for a Floating License Server.
Currently, if the user closes the console, the application and the web server stops.
How can I keep the application and webserver running after the console is closed?

**Comment by gnodet** [comment]
> I use JLine for a command-prompt application, which can start a web server for a Floating License Server. Currently, if the user closes the console, the application and the web server stops. How can I keep the application and webserver running after the console is closed?

On Unix, you need to detach from the parent process. That's unrelated to console management and not a feature provided by JLine.  One possibility is to start with `nohup`, another would be to launch a new JVM from the first one.  Or rely on native calls do to so.  Or use [Commons Daemon](http://commons.apache.org/daemon/) ...
