### ISSUE TITLE
InputValue prompt with mask doesn't return the enter value, only the repeated mask character

### ISSUE THREAD

**Issue by fkirchhoff** [jline/jline3#1103]
This example illustrates the problem:
```
        Terminal terminal = TerminalBuilder.builder().system(true).build();
        ConsolePrompt consolePrompt = new ConsolePrompt(terminal);
        PromptBuilder builder = consolePrompt.getPromptBuilder().createInputPrompt()
                .name("secret").message("secret>").mask('*').addPrompt();
        Map<String, PromptResultItemIF> answer = consolePrompt.prompt(builder.build());
        System.out.println("secret:"+answer.get("secret").getResult());
```
will result in:
```
? secret> ****
secret:****
```
even though I entered 1234.

**Comment by ericparton** [comment]
I'm also seeing the same issue

**Comment by fkirchhoff** [comment]
As I was trying to fix the issue locally (in the absence of https://github.com/jline/jline3/pull/1068), I noticed that [ConsolePrompt](https://github.com/jline/jline3/blob/master/console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java#L135C51-L135C64) copies the prompt value to be echoed back, which would result displaying the non-masked value.
