### ISSUE TITLE
Use of FFM without multi-release jar

### ISSUE THREAD

**Issue by io7m** [jline/jline3#1105]
Hello!

I've got a few projects that use `jline`, and on relatively recent versions, my Enforcer plugin executions are flagging `jline` as containing bytecode outside of the allowed range:

```
2024-10-26T15:01:51.7725917Z [INFO] Restricted to JDK 21 yet org.jline:jline:jar:3.27.1:compile contains org/jline/terminal/impl/ffm/CLibrary$termios.class targeted to JDK 22
```

I'm slightly hesitant to ask you to change your code to satisfy my plugin configuration ( :laughing: ), but we do now have a standard way (`META-INF/versions/22`) to include code that requires newer JDKs to run. Any chance this code could be moved there?

**Comment by gnodet** [comment]
Please use the small jars or use the JLine bundle with the jdk8 classifier, that one does not contain the FFM provider.
