### ISSUE TITLE
Cannot read anything in application started in detached screen

### ISSUE THREAD

**Issue by Minecrell** [jline/jline3#111]
When I try to read console input using `LineReader` in an application that was started in a detached screen using GNU screen it will always return `null` instead of waiting for the next input line. It works if the application is started in an attached screen.

I used the example code from https://github.com/jline/jline3/wiki/Using-line-readers and added to print the input that was read from the console. In this case, I'm running it with the `terminal-jna` implementation.

```java
public class ReaderTest {

    public static void main(String[] args) throws Exception {
        LineReader reader = LineReaderBuilder.builder().terminal(TerminalBuilder.terminal()).build();
        String prompt = "> ";
        while (true) {
            String line = null;
            try {
                line = reader.readLine(prompt);
                reader.getTerminal().writer().println(line);
            } catch (UserInterruptException e) {
                // Ignore
            } catch (EndOfFileException e) {
                return;
            }
        }
    }

}
```

When I start it normally or using an attached screen everything works as expected:

```
screen java -jar jlinetest3-1.0-SNAPSHOT-all.jar
> Test
Test
> JLine
JLine
> 
```

However, when I start it in a detached screen, it will always return null:

```
screen -dmS test java -jar jlinetest3-1.0-SNAPSHOT-all.jar
screen -r
>
null
>
null
>
null
>
null
...
```

It works fine when I read it using Java APIs or JLine 2, it's only broken using JLine 3:

```
System.out.println(System.console().readLine());
```

Correctly waits for input and prints the line.

I've attached the JAR file that can be used to reproduce the issue: [jlinetest3-1.0-SNAPSHOT-all.zip](https://github.com/jline/jline3/files/914676/jlinetest3-1.0-SNAPSHOT-all.zip) (it's a zip because GitHub doesn't accept it otherwise, but it can be run just like a regular JAR):

```
screen -dmS test java -jar jlinetest3-1.0-SNAPSHOT-all.zip
```

**Comment by gnodet** [comment]
The jar works correctly for me on OSX.

**Comment by Minecrell** [comment]
@gnodet It might be only an issue under Linux, I can reproduce it on several different systems on Linux:

- Arch Linux with `Screen version 4.05.01 (GNU) 25-Feb-17`
- Ubuntu 16.04 with `Screen version 4.03.01 (GNU) 28-Jun-15`
- Debian Jessie with `Screen version 4.02.01 (GNU) 28-Apr-14`

I'm always using the same command:

```
screen -dmS test java -jar jlinetest3-1.0-SNAPSHOT-all.zip
screen -r
```

**Comment by gnodet** [comment]
I can reproduce the problem described on FreeBSD too, though it seems to work when not using JNA.

**Comment by BrainStone** [comment]
I can reproduce this too for Debian Jessie with `Screen version 4.02.01 (GNU) 28-Apr-14`

**Comment by gnodet** [comment]
For some reason, it seems there's a difference between the code using JNA and using the stty exec calls.
In the case of JNA, the input stream built using `new FileInputStream(FileDescriptor.in)` seems to return -1 immediately rather than waiting while the same stream seems to wait when using the non-jna code.
It may be related to how the terminal attributes are set.

**Comment by Minecrell** [comment]
It works when I read directly from the reader returned by the `Terminal`:

```java
        try (BufferedReader reader = new BufferedReader(TerminalBuilder.terminal().reader())) {
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }
        }
```

That sounds a bit like the cause is somewhere in `LineReader`.

**Comment by Minecrell** [comment]
> It may be related to how the terminal attributes are set.

I continued debugging and it seems like input works as soon as I remove the call to [`terminal.enterRawMode()`](https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L470) (I replaced it with a call to `terminal.getAttributes()` for testing). I don't know what it does but it seems to be indeed related to something the reader does with the attributes.

**Comment by gnodet** [comment]
I wonder if the constants in https://github.com/jline/jline3/blob/master/terminal-jna/src/main/java/org/jline/terminal/impl/jna/linux/CLibrary.java#L271-L289 and https://github.com/jline/jline3/blob/master/terminal-jna/src/main/java/org/jline/terminal/impl/jna/freebsd/CLibrary.java#L255-L271 are correct.
Could you check on your linux headers what the values are ?

**Comment by gnodet** [comment]
I think the correct values for linux are:
```
    int VINTR       = 0;
    int VQUIT       = 1;
    int VERASE      = 2;
    int VKILL       = 3;
    int VEOF        = 4;
    int VTIME       = 5;
    int VMIN        = 6;
    int VSWTC       = 7;
    int VSTART      = 8;
    int VSTOP       = 9;
    int VSUSP       = 10;
    int VEOL        = 11;
    int VREPRINT    = 12;
    int VDISCARD    = 13;
    int VWERASE     = 14;
    int VLNEXT      = 15;
    int VEOL2       = 16;
```

**Comment by Minecrell** [comment]
@gnodet Yeah your corrected values are what I have in my header file.

**Comment by Minecrell** [comment]
I compiled the new version locally and tested using it, unfortunately it didn't fix the problem. :/

**Comment by Minecrell** [comment]
Thanks! I can confirm that it is working properly now. :)
