### ISSUE TITLE
Jline Nano unresponsive upon line overflow

### ISSUE THREAD

**Issue by abcnet** [jline/jline3#120]
I found a bug in Jline Nano editor. When we type enough characters until they do not fit in one line, Nano editor will become unresponsive.
[Jline_Nano_Bug_Report.zip](https://github.com/jline/jline3/files/963136/Jline_Nano_Bug_Report.zip)

The zip archive contains the minimal code that reproduces the error. To build and run:
 
    mvn package
    java -cp target/jline-nano-bug-1.0.jar com.NanoBug
 
I appreciate it if the problem could be resolved. 

Also, can you please make the constructor of Nano.Buffer class protected so that we can extend it?

        Buffer(String file) {
            this.file = file;
        }

Thanks a lot!

**Comment by gnodet** [comment]
Just for curiosity, what do you want to change in the Nano.Buffer class ?

**Comment by gnodet** [comment]
I've disabled non-wrapping mode, as it's clearly not working.

**Comment by abcnet** [comment]
Hi, I want to add a "protected" specifier to
    Buffer(String file) {
        this.file = file;
    }
Like this: 
    protected Buffer(String file) {
        this.file = file;
    }
So that I can extend the inner nested class. Thanks!

**Comment by gnodet** [comment]
Have you checked the commit https://github.com/jline/jline3/commit/43b443b2575fffc24bb103b48ef7e888a70de45e ?

**Comment by abcnet** [comment]
Sorry I missed that. Thank you!
