### ISSUE TITLE
Additional characters being output when JNA is enabled in Windows

### ISSUE THREAD

**Issue by camilojc** [jline/jline3#124]
Hi there,

We're using JLine3 and facing an issue in Windows with JNA enabled which we don't seem to be able to reproduce in Mac nor when using ConEmu in Windows.

When using the Windows command prompt and including the jline-terminal-jna dependency, I'm getting the following output:

![image](https://cloud.githubusercontent.com/assets/26857145/26287955/b586d76a-3e7d-11e7-97c5-e0e838865b9e.png)

If I use the same code, but using ConEmu as the terminal instead of the Windows command prompt, it works fine though:

![image](https://cloud.githubusercontent.com/assets/26857145/26287964/1a06e6ee-3e7e-11e7-86a6-3c3817412fd0.png)

We are using JLine v3.3.0.

Can't easily debug this in the IDE as I get an instance of DumbTerminal.

Is this a known issue? Or is it misconfiguration on our side?

Thanks!

**Comment by gnodet** [comment]
If you get a dumb terminal, you may be missing the jna or jansi library.
When using the windows console, one of them is required.

**Comment by camilojc** [comment]
Hi Guillaume, no, what I meant is that I can't debug via the IDE because in the IDE I don't get the JNA terminal.

However, the above issue is in the Windows Command Line using JNA.

**Comment by gnodet** [comment]
You need to launch your windows app with remote debugging enabled (using `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005`) and then connect to the remote application using your IDE.

**Comment by camilojc** [comment]
Excellent, found the issue, thanks!
