### ISSUE TITLE
A quick release of next version?

### ISSUE THREAD

**Issue by BardurArantsson** [jline/jline3#127]
It'd be **really** nice to have a new release including the https://github.com/jline/jline3/commit/5a31a1c55515b0441fbbcbcd319b918c70941ff0 commit. The issue is causing quite big problems for Arch Linux + sbt users at the moment; see https://github.com/sbt/sbt/issues/3240

**Comment by ranchoiver** [comment]
Users of OpenSUSE Tumbleweed also have this problem.

**Comment by eatobin** [comment]
Yes, I am an openSUSE Tumbleweed user having this problem after an update earlier this week...
