### ISSUE TITLE
AttributedStringBuilder: High intensity font color is unsupported

### ISSUE THREAD

**Issue by hyee** [jline/jline3#139]
It seems like the command prompt and command line doesn't support high intensity color.
For example, with below code, the output style is different from the prompt+input line, looks like `\33[1m` is eliminated:

![testansi](https://user-images.githubusercontent.com/761520/27516734-4794f17a-59f2-11e7-9be1-582843d83ee0.JPG)

```java
import org.jline.reader.LineReaderBuilder;
import org.jline.reader.impl.LineReaderImpl;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import org.jline.utils.AttributedStringBuilder;

public class TestAnsi {
    public static void main(String[] args) throws Exception {
        //Prompt color:  High Intensity Foreground Color: Yellow
        String HIY = "\33[33;1m";
        //Command color: High Intensity Foreground Color: Cyan
        String HIC = "\33[36;1m";
        //reset colors
        String NOR = "\33[0m";


        Terminal terminal = TerminalBuilder.builder().system(true).nativeSignals(true).signalHandler(Terminal.SignalHandler.SIG_IGN).exec(true).jansi(true).build();
        LineReaderImpl reader = (LineReaderImpl) LineReaderBuilder.builder().terminal(terminal).build();
        reader.setHighlighter((reader1, buffer) -> {
            AttributedStringBuilder sb = new AttributedStringBuilder();
            sb.appendAnsi(HIC);
            sb.append(buffer);
            //sb.append(NOR);
            return sb.toAttributedString();
        });

        //Terminal output
        terminal.writer().println(String.format("%s  prompt>%s %sthis is terminal output line%s\n", HIY, NOR, HIC, NOR));
        terminal.writer().flush();

        reader.readLine(String.format("%s  prompt>%s ", HIY, NOR));

        /* // Same result, FYI
        String prompt = new AttributedStringBuilder()
                .style(AttributedStyle.DEFAULT.foreground(AttributedStyle.YELLOW))
                .style(AttributedStyle.BOLD)
                .append("  prompt>")
                .style(AttributedStyle.DEFAULT)
                .append("  ").toAnsi();
        reader.readLine(prompt);
        */
    }
}
```

**Comment by gnodet** [comment]
Which os ? Which jline terminal is used (maybe print out the ```terminal.getClass().getName()``` ?  If you're using a Jansi terminal, can you check you use the latest Jansi library ?

**Comment by hyee** [comment]
Yes the depending libararies are all up to date, OS is Windows(Win7/XP/Win10), I tried both JNA and jansi, the result is the same.

* org.jline.terminal.impl.jna.win.JnaWinSysTerminal
* org.jline.terminal.impl.jansi.win.JansiWinSysTerminal

**Comment by gnodet** [comment]
It seems that the highlighter generates something like ```\33[1;36m``` instead of the ```\33[36;1m``` you use in the first place.
Could you check if the first line is also working correctly when using the ```1;33 / 1;36``` sequences instead of the ```33;1 / 36;1``` ones ?
It may be a weird windows behavior...

**Comment by gnodet** [comment]
Yes, that's the problem. The AttributedString is not aware that windows has the same behavior when using high intensity colors and bold attribute.

As a workaround, you should use 0-15 colors instead of using 0-7 + bold.

**Comment by hyee** [comment]
You are right, I checked the code of AttributedStringBuilder yesterday and found that 1;30-47m all have the equivalences of 90-107m, and also compared them in Linux terminal, so I have changed my code.
