### ISSUE TITLE
Support bracketing paste

### ISSUE THREAD

**Issue by hyee** [jline/jline3#142]
While pasting following text from clipboard: `select\t*\tfrom\tdual`, the command line becomes `select*fromdual`, the `\t` symbol is eliminated, since my completer contains about 4000 keywords, it takes about 1 second to output the whole command line.

I found the JLine2 project has the similar ticket and it is resolved, is it possible to implement in Jline3, and reduce the calls over parser and highlighter in case of pasting? thanks.

**Comment by gnodet** [comment]
This would require supporting "bracketing paste", see https://cirw.in/blog/bracketed-paste.
