### ISSUE TITLE
Unexplained NullPointerException in pump thread

### ISSUE THREAD

**Issue by nik9000** [jline/jline3#145]
When using an ExternalTerminal for testing my how my code interacts with jline I *sometimes* get this exception on the input pump thread:

```
java.lang.NullPointerException
	at org.jline.terminal.Attributes.getControlChar(Attributes.java:291)
	at org.jline.terminal.impl.LineDisciplineTerminal.processInputByte(LineDisciplineTerminal.java:186)
	at org.jline.terminal.impl.ExternalTerminal.pump(ExternalTerminal.java:68)
	at org.jline.terminal.impl.ExternalTerminal$$Lambda$49/750796170.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

I'm not really sure what I'm doing to cause this but I'm aware that a stacktrace isn't usually good enough to debug something like this. If you have any ideas on things I can try to isolate the problem I'd love to give it a shot.

From the reading the code it looks like the `cchars` map has a null value for `VINTR`. I'm not intentionally sending interrupts stranger things have happened.

**Comment by nik9000** [comment]
It looks like you can work around this with:
```
+        Attributes attrs = terminal.getAttributes();
+        attrs.setLocalFlag(LocalFlag.ISIG, false);
+        terminal.setAttributes(attrs);
```

**Comment by gnodet** [comment]
This looks like a threading issue where the terminal attributes are modified and read concurrently.
The ```EnumMap#getOrDefault``` is not an atomic operation, so that if attributes are set while in the middle of a ```getOrDefault``` call, I think there is a possibility of ```getOrDefault``` returning null.

**Comment by nik9000** [comment]
Thanks for fixing it @gnodet!
