### ISSUE TITLE
How do you compile and run the Example.java example?

### ISSUE THREAD

**Issue by jarrodwb** [jline/jline3#15]
Hello,

I compiled the jline program with `mvn install` then moved the example file and the jar file to a common directory. Then I tried to compile the file and run it.

```
javac -cp jline-2.15-SNAPSHOT.jar Example.java
java Example 
```

This gave an error of `Error: Could not find or load main class Example`. I also tried `java -cp jline-2.15-SNAPSHOT.jar Example` but got the same error.

I come from a Scala background and not a Java background so I am sure I am missing something simple.

Oh yeah. I did the same thing with both the master branch of the jline2 and the jline3 repos.

Thanks for you help.

**Comment by johnpoth** [comment]
Hi @jarrodwb ,

Test classes aren't packaged in the final artifact hence the error. If you've built the project you can run the example with (from jline's root directory):

<code>
java -cp target/classes:target/test-classes org.jline.example.Example
</code>

And you have the give it an argument so 

<code>
java -cp target/classes:target/test-classes org.jline.example.Example color
</code>

for example will do the trick :)

Cheers!

**Comment by jarrodwb** [comment]
Great! This is what I was looking for. Thanks.
