### ISSUE TITLE
JSch client with JLine3 powered SSH server

### ISSUE THREAD

**Issue by anand1st** [jline/jline3#154]
I've a [sample](https://github.com/anand1st/SSH-JLine3) of a project using jsch client with jline3 powered ssh server and and am having some issues. I've managed to connect using jline2 with the exact same unit test but getting errors with jline3. I've posted this on stackoverflow [here](https://stackoverflow.com/questions/45320387/java-ssh-server-with-jline3-and-jsch-client) but no luck yet. I don't know if this is a bug or an inaccurate usage of jsch. Hope someone can help me out here. Thanks.

**Comment by gnodet** [comment]
It looks an expected exception to me.
After 2 seconds, the test closes the jsch client channel, and on the server side, jline generated the {{ClosedException}} because the stream has been closed. You nee to catch it along the {{UserInterruptException}} and handle it.

**Comment by anand1st** [comment]
Thanks for your response. I've fixed the exception. Please take update from the above github link. It was caused by a missing jline-terminal-jansi / jline-terminal-jna. But the output is still not correct. I've also updated the example to show the implementation of jline2 and jline3 powered ssh server along with their respective Jsch client. I'm thinking that the async behaviour of jline3 is causing the problem. And if that is the case, how do we fix this? Thanks.

**Comment by gnodet** [comment]
Your expectations are wrong.
There's no guarantee about the output.

If you're using a ChannelShell, i.e. an interactive channel, you can't write your test that way.  You need to use a PipedInputStream, wait for the prompt, send the command, wait for the output, and close.
If you test against a real native sshd server, you'll see the same behavior.
So your test is too simplistic.

If you want a synchronous execution, you can use the ChannelExec instead which is a non interactive way to execute commands remotely.  In that case, you don't need jline.

**Comment by anand1st** [comment]
Thank you for the pointers. Have not used PipedInputStream/PipedOutputStream before. Replacing with these got me on track and Jsch is working as expected. Have updated unit tests to reflect this.
