### ISSUE TITLE
Top part of the display cuts off

### ISSUE THREAD

**Issue by nagakrishna** [jline/jline3#155]
On increasing the number of rows that need to be displayed, the top portion of the display cuts off. Is there a way to prevent that and display entire text using scrolling

**Comment by gnodet** [comment]
That's not implemented.  
Do you use the Display class ?

**Comment by nagakrishna** [comment]
Yes, i use display class

**Comment by gnodet** [comment]
The Display class is used to manage the screen as seen by the user and to optimize the changes needed to update the display.
If you want to display something bigger than the screen, you need to handle the scrolling yourself, and just give the subset of lines to actually display.  The Display class should detect that it's a scrolling and actually scroll the screen (not redisplaying everything).
See the [Nano](https://github.com/jline/jline3/blob/master/builtins/src/main/java/org/jline/builtins/Nano.java) class for a complete example of such usage with scrolling.
