### ISSUE TITLE
It would be good to have a "Hello World" example to help people get started with jline3

### ISSUE THREAD

**Issue by rrjohnson** [jline/jline3#161]

**Comment by gnodet** [comment]
What about the [Example.java](https://github.com/jline/jline3/blob/master/builtins/src/test/java/org/jline/example/Example.java) ?

**Comment by mslinn** [comment]
`Example.java` seems like it was intended to loop for input until ^D is pressed, but instead it displays a message and immediately exits. Unfortunately running this program does not demonstrate much at present.

```
Usage: java Example [none/simple/files/dictionary [trigger mask]]
  none    - no completors
  simple  - a simple completor that compiles "foo", "bar", and "baz"
  files   - a completor that compiles file names
  classes - a completor that compiles java class names
  trigger - a special word which causes it to assume the next line is a password
  mask    - is the character to print in place of the actual password character
  color   - colored prompt and feedback

  e.g - java example simple su '*' will use the simple completor with 'su' triggering the use of '*' as a password mask.
```

**Comment by gnodet** [comment]
The example needs at least one argument which is the feature to demonstrate, it can be `none`, `simple`, `files`, `classes`, `trigger`, `mask` or `color` as indicated by the above usage.

**Comment by LMA1980** [comment]
This may help people with learning JLine3: https://github.com/LMA1980/jline3-jlink-example
