### ISSUE TITLE
how pass the System.in to jline?

### ISSUE THREAD

**Issue by publicocean0** [jline/jline3#162]
Hi ... i m realizing a particulat commander but i d like permit also to pass a list of commands also using pipe.

cat commands.txt | mycommand.

I think i might pass System.in to jline .... but how?

**Comment by gnodet** [comment]
```TerminalBuilder.terminal()``` will give you a terminal using ```System.in```, but I'm not quite sure to understand where jline will be in your command line.
If jline is used in the implementation of ```mycommand```, then using the above terminal and give it to the line reader should work, as the JVM will receive the output of ```cat commands.txt``` and will use that as the ```System.in```.

**Comment by gnodet** [comment]
Please reopen if needed.
