### ISSUE TITLE
Unable to create system terminal when using urxvt

### ISSUE THREAD

**Issue by Yackeroeni** [jline/jline3#166]
When using uxrvt on arch-linux, when starting felix (using jline) I get the following warning:
`WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)`
The TERM environment variable is set to rxvt-unicode-256color then, a dumb terminal is created which doesn't allow me to enter any commands.

If I change TERM to screen-256color, a full system terminal is correctly created.

It looks to me like the rxvt-unicode-256color should work the same as screen-256color.

**Comment by gnodet** [comment]
You should enable debug logging and paste the exception.
I suspect {{infocmp}} can not find information for {{rxvt-unicode-256color}}.  Can you paste the output of {{infocmp rxvt-unicode-256color}} in your terminal ? It fails for me, so maybe also try setting {{TERM}} to {rxvt-256color}} instead.

**Comment by gnodet** [comment]
Maybe you need to install the required package:
```
sudo apt-get install rxvt-unicode-256color
```

**Comment by gnodet** [comment]
Please reopen if needed.
