### ISSUE TITLE
Terminal getType() returning null for JLine 3.4.0 on OSX

### ISSUE THREAD

**Issue by anand1st** [jline/jline3#172]
I've got some code that instantiates a Terminal:
`Terminal terminal = TerminalBuilder.builder().streams(is, os).build();`

With JLine 3.3.1, it works fine. But with version 3.4.0, the following exception is observed:
> Exception in thread "ssh-cli admin" java.lang.NullPointerException
>         at org.jline.utils.AttributedCharSequence.toAnsi(AttributedCharSequence.java:57)

The reason for this is that terminal.getType() is returning null.

**Comment by gnodet** [comment]
What's the class of the instantiated terminal ?

**Comment by anand1st** [comment]
The instantiated terminal is `ExternalTerminal`.
Full stack trace of exception below:
> Exception in thread "ssh-cli admin" java.lang.NullPointerException
> 	at org.jline.utils.AttributedCharSequence.toAnsi(AttributedCharSequence.java:57)
> 	at sshd.shell.springboot.server.SshSessionContext.writeOutput(SshSessionContext.java:109)
> 	at sshd.shell.springboot.server.TerminalProcessor.processInputs(TerminalProcessor.java:60)
> 	at sshd.shell.springboot.server.SshSessionInstance.run(SshSessionInstance.java:77)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by anand1st** [comment]
Please checkout the branch [https://github.com/anand1st/sshd-shell-spring-boot/tree/jline3.4](https://github.com/anand1st/sshd-shell-spring-boot/tree/jline3.4)

Run following commands to start server:

> mvn clean install -DskipTests=true
> cd sshd-shell-spring-boot-test-app
> mvn spring-boot:run

Connect via ssh:
> ssh -p 8022 admin@localhost

Exception will be thrown and user will be logged out immediately.

**Comment by gnodet** [comment]
It's working for me and I don't think the code has changed.  However, given your setup, it's system dependent, mostly because the creation of the terminal is a bit simplistic.
You need to set the terminal type explicitely.
Here's a correct ssh/jline integration:
  https://github.com/jline/jline3/blob/master/remote-ssh/src/main/java/org/jline/builtins/ssh/ShellFactoryImpl.java#L119-L224

**Comment by anand1st** [comment]
Setting terminal type worked. Thanks.
