### ISSUE TITLE
the jline reader still try to read another "enter" even need close the jline session

### ISSUE THREAD

**Issue by ffang** [jline/jline3#178]
The InputStreamReader.close is blocked because the InputStreamReader.read(char[] buf, int offset, int length) hold the lock and wait at line 270.
This cause the KARAF-5385

**Comment by ffang** [comment]
And this commit d5695a128c277e6ac1229a5737b990546edcf1a8 introduced this issue
remove code

+                    if (Thread.interrupted()) {
+                        throw new InterruptedException();
+                    }
get it work

**Comment by gnodet** [comment]
I would think https://github.com/jline/jline3/commit/11eb592999d68529932733db0d31aa234451b4ec fixed the issue already, but I'll give it a try.

**Comment by ffang** [comment]
Hi @gnodet , 
Yes, 11eb592999d68529932733db0d31aa234451b4ec fixed this issue, just verified.
This fix isn't in jline 3.5.0 so seems we need jline 3.5.1

Thanks!
Freeman
