### ISSUE TITLE
Ability to overwrite the input line.

### ISSUE THREAD

**Issue by RobertZenz** [jline/jline3#181]
It would be nice if there would be the ability to overwrite the input line.

Like this:
    
    You are seeing here the prompt the user will see.
    -------------------------------------------------
    Prompt: This is user input.

Now, when the user presses enter/return, the terminal should not advance to the next line, but instead the whole line should be removed and the cursor should return to the beginning of the line:

    You are seeing here the prompt the user will see.
    -------------------------------------------------
    That was odd input.
    Prompt: More user input goes here.

I'm not sure if that is easily possible, though.

**Comment by gnodet** [comment]
You need to create a class derived from `LineReaderImpl` and do the following
```
            LineReaderImpl readerimpl = new LineReaderImpl(terminal) {
                @Override
                protected void cleanup() {
                    buf.clear();
                    post = null;
                    prompt = new AttributedString("");
                    redisplay(false);
                    terminal.puts(Capability.keypad_local);
                    terminal.trackMouse(Terminal.MouseTracking.Off);
                    if (isSet(Option.BRACKETED_PASTE))
                        terminal.writer().write(BRACKETED_PASTE_OFF);
                    flush();
                    history.moveToEnd();
                }
            };
```

This will leave the line completely cleaned when exiting the `readLine` call.

**Comment by RobertZenz** [comment]
Works very well, thank you very much.

**Comment by RobertZenz** [comment]
I've just managed to upgrade my application to the latest version and tested the new `ERASE_LINE_ON_FINISH` option. It is clearing the line fine, but it also forwards to the next line.

As far as I can see, that is because `LineReaderImpl.cleanup()` is calling `doCleanup()` which always outputs a new line character. So the current line cannot be reused.

**Comment by RobertZenz** [comment]
Sorry for the long response times. I've just tested 3.8.0 and it works as advertised.

Thank you very much.
