### ISSUE TITLE
Can't set ANSI color for user input using readLine

### ISSUE THREAD

**Issue by cjohnstoninv** [jline/jline3#182]
In JLine1 I could use readLine and append the last character(s) of the prompt with the ANSI colors of what the user's input would be. With the latest release of JLine3 and the LineReader#readLine method it seems suffixing the input with a color code ALWAYS gets reset to the DEFAULT. Is this a design decision? Is there something I might be missing to set the input color?

Thanks.

**Comment by gnodet** [comment]
I'm not sure to understand what you were doing exactly with JLine1.
However, in JLine3, you have full control over the coloring using the [https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/Highlighter.java] interface.  You need to implement your own and use it on the reader.
