### ISSUE TITLE
Completion docs would be helpful

### ISSUE THREAD

**Issue by mslinn** [jline/jline3#186]
This page is blank:
https://github.com/jline/jline3/wiki/Completion

I am new to jline and completion is the most important feature that I am looking for in a cli library. I am unsure if jline is right for me at this time. An overview of jline's completion feature would be helpful, along with a few examples.

I wrote up some docs, based on what little I learned since yesterday. It is a start. Too bad GitHub does not support PRs for wikis. The docs are in [this fork of the wiki](https://github.com/mslinn/jline3-wiki/blob/master/Completion.md).

**Comment by mslinn** [comment]
Tab completion of available commands, options and parameters is supported by
implentations of the [Completer](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/reader/Completer.html) interface. Results are returned as a collection of [Candidate](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/reader/Candidate.html). `Completer`s can be combined into a hierarchy.

## Completer Subclasses

[AggregateCompleter]() &ndash; Combines zero or more completers.

[ArgumentCompleter]() &ndash; invokes a child completer, so individual completers do not need to know about argument parsing semantics.

[DirectoriesCompleter]() &ndash; returns matching directories as a collection of [Path](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html?is-external=true)

[EnumCompleter](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/reader/impl/completer/EnumCompleter.html) &ndash; Needs description.

[FileNameCompleter]() &ndash; returns matching files as a collection of [Path](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html?is-external=true)

[FilesCompleter](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/builtins/Completers.FilesCompleter.html) &ndash; Needs description.

[NullCompleter](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/reader/impl/completer/NullCompleter.html) &ndash; Needs description.

[RegexCompleter](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/builtins/Completers.RegexCompleter.html) &ndash; Needs description.

[StringsCompleter](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/reader/impl/completer/StringsCompleter.html) &ndash; Needs description.

[TreeCompleter](https://static.javadoc.io/org.jline/jline/3.5.1/org/jline/builtins/Completers.TreeCompleter.html) &ndash; Needs description.

*TODO: make code examples for all of the above.*

## Pro tip
If you use a `TreeCompleter`, and you want all of the top-level node values to be displayed, thereby displaying the available commands, when the user's first keypress is a tab,
call `unsetOpt` on the `LineReader` as shown:
```
LineReader reader = LineReaderBuilder().builder()
    .terminal(terminal)
    .completer(treeCompleter)
    .parser(parser)
    .build()

reader.unsetOpt(LineReader.Option.INSERT_TAB)
```

**Comment by gnodet** [comment]
Added some more doc at https://github.com/jline/jline3/wiki/Completion

**Comment by mslinn** [comment]
An explanation of the purpose of `NullCompleter` would be helpful.

**Comment by gnodet** [comment]
I've added a paragraph on the `ArgumentCompleter`, which is the main use of the `NullCompleter`.

**Comment by mslinn** [comment]
A step in the right direction, thank you. 

The new docs reference `gogo/jline` code which itself has no documentation, but uses `CompletionEnvironment` and `CompletionData` which again have no documentation. No mention of what those types are for or how they relate to completers. This requires the reader to embark on a research project. Some standalone examples showing how each type of completer would actually be used, and a discussion of when one type of completer might be more appropriate would be helpful.

**Comment by gnodet** [comment]
Yeah, well, completion is usually quite tied to the definition of commands which is out of JLine's scope.  I think usually the user will end up writing its own completer. I've yet to see a non trivial project using a trivial completer...
I'll try to add some javadoc to the `Completer`, `CompletionEnvironment` and `CompletionData` classes.
