### ISSUE TITLE
Bold (and other) formatting not always working in prompt

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#204]
Does JLine do anything special to ANSI formatting on the prompt?  I can get colors and background colors to work (most of the time...) but for the life of me, I can't get bold to work (most of the time).  There must be something going on.

For a super simple example that bypasses my ANSI-formatting library, if I run this line:
```js
reader.readLine( '#chr(27)#[1mtest#chr(27)#[0m' );
```
Then the prompt will show as the text "test" but the text will not be bold even though I have started the prompt with ESC[1 which starts bold.  

I can take that exact same string and pass it into reader.getTerminal().writer().print(); and it prints out as bold.

Here's another oddball example that makes no sense.  This string should print out the word test with black text on a yellow background. It works perfectly both in the writer and the prompt.
```
#chr(27)#[30m#chr(27)#[43mtester#chr(27)#[0m
```
Now, we add the code for bold to it 
```
#chr(27)#[1m#chr(27)#[30m#chr(27)#[43mtester#chr(27)#[0m
```
The standard writer works, but the prompt suddenly turns to grey text!  

And just when you think you've found a pattern, here's one that works the opposite:
```
#chr(27)#[1m#chr(27)#[31m#chr(27)#[42mtester#chr(27)#[0m
```
That should be bold red text on a green background. The colors are correct, but only the prompt is bold.  The writer doesn't output as bold!

What's going on with the Jline prompt that gives my ANSI formatting such a hard time?

**Comment by bdw429s** [comment]
This is in response to this thread on the mailing list.  

https://groups.google.com/d/topic/jline-users/1q_7sBI1r1A/discussion

**Comment by gnodet** [comment]
So the problem only appears on JLine's terminals which have a type `windows`.
This should be mainly the windows cmd console, which does not support bold correctly and so the bold attribute is changed to high intensity color.
This is the desired behavior and a few other things are "emulated" if the terminal does not support them fully, such as support for 256 colors.

So the real question is: on which terminal are you seing incoherent results ? i.e. do you have a terminal which supports bold font and where jline wrongly uses high intensity color.
I've tested the basic cmd and cygwin and they both seem work correctly in that regard.

**Comment by gnodet** [comment]
This looks related to #139.  I'll double check the fix that was added at that time.

**Comment by bdw429s** [comment]
This ticket is not fully resolved. Each of the ANSI sequences I showed in the sample code I provided is not displaying correctly as per the screenshots I posted.  Opening a new ticket.

**Comment by bdw429s** [comment]
Here is the new ticket for the outstanding items that were covered in this ticket but not fixed:
https://github.com/jline/jline3/issues/218
