### ISSUE TITLE
On the Windows server 2008 r2 system, there is a character problem, unless you set jna to false.

### ISSUE THREAD

**Issue by wanghuizuo** [jline/jline3#207]
system: windows server 2008r2
character: GBK
jline version: 3.4.0

On the Windows server 2008 r2 system, characters are scrambled. but windows 10/7  will not have this problem.

![image](https://user-images.githubusercontent.com/12987264/34760975-e6cde44c-f61c-11e7-9eee-a1709c36d7a3.png)

Unless I set jna to false, like this.
`TerminalBuilder.builder().jna(false).build()`

**Comment by gnodet** [comment]
When you set `jna(false)`, could you get the implementation class of the terminal being build ?

**Comment by wanghuizuo** [comment]
On the Windows server 2008 r2 system,I set `jna(false)`,Repeat the input above, the results are as follows:

![image](https://user-images.githubusercontent.com/12987264/34763173-242200be-f625-11e7-89d2-31d0ece1b91f.png)

**Comment by Minecrell** [comment]
JLine 3.4.0 is outdated. There have been a lot of Windows related encoding fixes in JLine 3.5.1+, so you should try updating first.

**Comment by wanghuizuo** [comment]
That's true. thanks.

![image](https://user-images.githubusercontent.com/12987264/34816458-f73412ba-f6ef-11e7-8b9c-b3f16e8f7948.png)
