### ISSUE TITLE
Windows/ConEMU terminal detected as 16 colors

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#209]
I'm using a pretty-much stock ConEMU install on Windows 7 that has all the settings set that are supposedly required for 256 colors. However, the following CFML code when run from the CommandBox REPL returns `16` for the max colors capability.   

```js
caps = createObject( 'java', 'org.jline.utils.InfoCmp$Capability' )
$shell.getReader().getTerminal().getNumericCapability(caps.max_colors)
```

It's possible that something isn't set right in ConEMU, but I think it's also likely that JLine isn't detecting something properly.

**Comment by bdw429s** [comment]
This help page seems to apply here, though I don't really know what most of it is talking about since all the settings discussed don't even appear in my ConEMU installation.  Perhaps it's out of date.

https://conemu.github.io/en/Xterm256Colors.html

**Comment by gnodet** [comment]
Any idea how to detect if the terminal is a ConEMU one ?
I can easily turn on 256 color support for ConEMU once I know how to detect it accurately.
Alternatively, I can let the user set the `org.jline.terminal.type=windows-256color` system property manually in order to turn on 256 color support.

**Comment by gnodet** [comment]
I just installed ConEMU. Nice terminal... ;-)
Did you managed to get the arrow keys working with jline ?

**Comment by gnodet** [comment]
I fixed the arrow keys regression with https://github.com/jline/jline3/commit/0bb16a637e31ddeaaa67fe8c85bd361b701ba90b.
I've started to hack something, but the problem is that the windows console does not support 256 colors.  I think ConEmu "emulates" the console so that it can support decoding ansi sequences and supports 256 colors even if the underlying windows api does not.  The problem is that the current terminal relies on jansi or jna and goes to the windows console api, so there's no simple way we can support 256 colors on those terminals.  
This would mean writing a new support for a ConEmu terminal somehow.  If it still needs to access the windows api, it also means 2 variations for jansi and jna...

**Comment by gnodet** [comment]
Could you try the above branch ?
Colors seem to work fine, however it seems there's a small problem with the right margin which i'm not sure how to fix.

**Comment by bdw429s** [comment]
@gnodet Thanks for the work on this.  I was traveling this week so I didn't get to any of my E-mails.  I'll test this and see.  And yes, the arrow keys seems to be working great in JLine3.  I converted my Snake game over to use arrow keys finally.

**Comment by bdw429s** [comment]
@gnodet Very good news.  I have tested your fixes for ConEMU from that branch and they seem to work great!  

![image](https://user-images.githubusercontent.com/584009/35308445-666a498e-006d-11e8-8994-044e181a0647.png)

Now, you mentioned something about JLine trying to do color rounding on terminals that don't support 256 colors.  When I do the same test on cmd.exe I just get white text.  Should the text have been approximated to a close color there? I'm not using attributed string for general output in CommandBox.  Do I need to?

**Comment by gnodet** [comment]
See #217.  In your case, the white was computed as the nearest color. I've changed the default, but you want to choose your color carefully if you expect them to be rounded to 16.  Also, you need to take into account that different terminals may have slightly different palettes for the 256 colors.

The terminal streams on windows will not perform any color rounding.  So you should only use the 256 colors ansi sequences if your terminal supports it.  If you use `AttributedString`, the check will be done when converting to ansi, so you may want to use it where you use colors.

**Comment by bdw429s** [comment]
>  In your case, the white was computed as the nearest color. 

Was it though?  In the next paragraph you said that Windows terminals don't round colors at all!  If the colors were rounding, I would have expected one of those three colors above to not have rounded to white.  The dark purple for instance.  

> Also, you need to take into account that different terminals may have slightly different palettes for the 256 colors.

Yes, I'm ok with the fact that the colors may vary across terminals.  That's no big deal.  What was unexpected was dark purple rounding to white :)

> The terminal streams on windows will not perform any color rounding. 

So.... do I need to enter a ticket for this to be implemented?  You didn't quite clarify if this is a technical impossibility or just something you haven't had the time to do yet.

> So you should only use the 256 colors ansi sequences if your terminal supports it.

Yeah, that's sort of the opposite of what I was hoping for.  You had my hopes when you originally started talking about color rounding that I _wouldn't_ need to do those sort of checks!  I'm not sure what the point of color rounding is if the onus is still on me not to use colors that my terminal doesn't support.  Surely those are contradictory requirements.

>  If you use `AttributedString`...

Can you clarify what you mean by "use".  Does this still apply to when I initialize an attributed string from a regular string already containing ANSI sequences that I've created?

```
AttributedString.fromAnsi( string )
```

Or do I have to use the other methods to build up the attributed string for it to work?

**Comment by gnodet** [comment]
If you write ansi sequences directly to the terminal output stream, you should not expect any color conversion to happen.  

The conversion is done by the `AttributedString.toAnsi` call.  The `LineReader` will call this method, but if you're executing a command such as `echo`, you are responsible for using the `AttributedString` correctly.
For pure color conversion, you could use the following code which will ensure color rounding.
```
AttributedString.fromAnsi(string).toAnsi(terminal)
```

**Comment by bdw429s** [comment]
> If you write ansi sequences directly to the terminal output stream, you should not expect any color conversion to happen.

Well, yes-- and to be clear I didn't expect it to in that case.

> `AttributedString.fromAnsi(string).toAnsi(terminal)`

Ahh, that was the missing piece.  I was testing with `AttributedString` and creating an instance with the `fromAnsi()` method, but I wasn't using `toAnsi()` to get the string back out.  I was just doing `toString()`.   

If I pass all my ANSI formatted strings through the attributed string class before outputting like tis:
```
string = createObject("java","org.jline.utils.AttributedString").fromAnsi( string ).toAnsi();
```
Then I get proper color rounding on Windows' `cmd.exe`.

There is a problem though-- Passing my strings through that class in that manner is ruining some of the formatting!  For instance, bold is disappearing, when it worked fine before.  I'm fairly certain this is the exact same issue I've been reporting with the prompt this whole time.  The `AttribtuedString` class is losing certain formatting and not displaying it the same.
