### ISSUE TITLE
mvn install hangs in HistoryPersistenceTest

### ISSUE THREAD

**Issue by PerBothner** [jline/jline3#214]
I can't `mvn build` because it hangs here:

    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running org.jline.terminal.impl.ExternalTerminalTest
    [WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.321 s - in     org.jline.terminal.impl.ExternalTerminalTest
    [INFO] Running org.jline.reader.impl.HistorySearchTest
    [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.238 s - in org.jline.reader.impl.HistorySearchTest
    [INFO] Running org.jline.reader.impl.history.HistoryTest
    [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.07 s - in org.jline.reader.impl.history.HistoryTest
    [INFO] Running org.jline.reader.impl.history.HistoryPersistenceTest
    [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 s - in org.jline.reader.impl.history.HistoryPersistenceTest
    [INFO] Running org.jline.reader.impl.history.HistoryReaderTest

This is on Fedora 27 with Java 8:

    java version "1.8.0_144"
    Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
    Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by PerBothner** [comment]
This is with a fresh

    git clone git://github.com/jline/jline3.git

**Comment by gnodet** [comment]
Is that specific to your environment ? I've tried to reproduce it on several platforms without success.
If you can reproduce it easily, could you grab a thread dump with a `kill -3` ?

**Comment by PerBothner** [comment]
[log1.txt](https://github.com/jline/jline3/files/1652748/log1.txt)
[log2.txt](https://github.com/jline/jline3/files/1652750/log2.txt)

`log1.txt` is copied from te terminal I was running `mvn install` in. `log2.txt` is from te terminal I used to kill it.

I can upload the dumpStream file if that would be useful.

**Comment by gnodet** [comment]
This looks like a regression caused by #140 and which causes the CI jobs to fail too.
