### ISSUE TITLE
Arrow keys broken in Windows 7 cmd on 3.6.0 snapshot

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#215]
From this message group thread:
https://groups.google.com/d/topic/jline-users/P-gAZ_NHDKU/discussion

I just downloaded **jline-3.6.0-20180117.080616-1.jar** from the sonatype repo to test some of the latest fixes and arrow keys no longer work at all.  
I cannot move the cursor around in the prompt text with left/right
I cannot use up/down to navigate history
I cannot read the arrow keys with a keymap any longer
When I press arrow keys, text like "ooOAoOAoOAoOAoOBoOBoOBoODoODoODoODoOCoOCoOC" appears instead.  I tested this just now on ConEMU and cmd.exe on Windows 7 and the behavior was the same.

I remember you saying that you made some changes in regards to arrow keys recently.  Any chance that is responsible for the regression? 

My terminal type is **org.jline.terminal.impl.jna.win.JnaWinSysTerminal**.

**Comment by gnodet** [comment]
Fixed by https://github.com/jline/jline3/commit/0bb16a637e31ddeaaa67fe8c85bd361b701ba90b
