### ISSUE TITLE
Pause after typing right parenthesis ")" eats next character on 3.6 snapshot

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#216]
This relates to this thread in the mailing list:

https://groups.google.com/d/topic/jline-users/7RV1uvEMxuY/discussion

Ok, the subject is actually only one of the two issues I'm seeing, but that's the most alarming one and they are likely related so I'll cover both of them here.

The first issue I can reproduce on JLine 3.5.1 AND 3.6 snapshot.  It's not breaking anything but it's annoying.

Basically, any time I type a right parenthesis, the cursor on my terminal will stay on the left side of the character for a second
```
_)
```
And then after a delay, the cursor will pop over to the right side (the end of the line)
```
)_
```
If I type a left paren followed by a right paren "()" then the cursor will move to the left of BOTH chars for a second:
```
_()
```
And then will eventually pop back over to the end of the line:
```
()_
```
If I type any other character other than a left paren, I get the same behavior as the first scenario.  This for a second:
```
R_(
```
And then after a second, this:
```
R(_
```
This appears to just be a visual bug, but it's a little distracting when typing code in the REPL for instance.

The second issue is also related to typing a right paren and is definitely a bug but this issue I can only reproduce on the 3.6 snapshot.   When I type a right parenthesis, ANY CHARACTER I type within a second (or so) will get eaten and not be printed out to the buffer.   So if I type 
```
foo().bar() 
```
What actually ends up in the buffer is:
```
foo()bar() 
```
You can see the period gets eaten.  This is also the case when pasting text into the console which is where I first noticed it.  It seems that the window of time that caused the next character to get eaten is the same as the pause in my issue above.  

I'm on Windows 7 using cmd.exe and I've disabled my custom highlighter.

**Comment by gnodet** [comment]
The whole thing is a feature, not a bug. A proposed enhancement has been raised with #47 though.
The half-second delay can be customized to a shorter period.
```
        reader.setVariable(BLINK_MATCHING_PAREN, 100L);
```
If you want to disable the whole matching highlighting, you can rebind the widgets:
```
        Map<String, Widget> widgets = reader.getWidgets();
        widgets.put(INSERT_CLOSE_CURLY, widgets.get(SELF_INSERT));
        widgets.put(INSERT_CLOSE_PAREN, widgets.get(SELF_INSERT));
        widgets.put(INSERT_CLOSE_SQUARE, widgets.get(SELF_INSERT));
```

An alternative would be to remap they keys for the current KeyMap:
```
   reader.getKeys().bind(new Reference(SELF_INSERT), "}", ")", "]");
```

As for the second problem, I suspect it also has been solved by https://github.com/jline/jline3/commit/0bb16a637e31ddeaaa67fe8c85bd361b701ba90b.

**Comment by gnodet** [comment]
Please reopen if needed.

**Comment by bdw429s** [comment]
@gnodet Hmm, very interesting to hear this is a "feature".  To be honest it's very distracting and makes me think something is wrong with the shell and it can't keep up with my input or something.  I'd definitely say this deserves to have a setting to turn it off (and not a complicated workaround rebinding widgets or whatever).  I've never seen a shell or IDE which does this and it seems like something a shell probably ought not to do anyway (this isn't an IDE after all).  If I wanted to show matching parens, I'd probably just implement it in the highlighter so if the cursor was after a closing paren or curly, I'd highlight it as well as the opening one.  Moving the cursor though is just very visually distracting.  

> I suspect it also has been solved

Not that I'm aware of.  I'm testing now on a custom JLine build that I made just last night on from the latest commits.  I see your commit is from 6 days ago so it should be a part of this build I'm testing with.

**Comment by bdw429s** [comment]
@gnodet Since you closed this issue, Github's permissions will not allow me to re-open it.  Can you please reopen it for me?

**Comment by gnodet** [comment]
It can now be disabled by setting BLINK_MATCHING_PAREN to 0:

```
LineReaderBuilder.builder(). ... .variable(BLINK_MATCHING_PAREN, 0).build()
```

**Comment by bdw429s** [comment]
Circling back to this @gnodet , the `BLINK_MATCHING_PAREN` works great.  Thx!
