### ISSUE TITLE
AttributedString loses bold in some cases in Windows CMD

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#218]
This is a continuation of the previous tickets which were not fully fixed.  The `AttributedString` class when used with Windows cmd has the undesirable effect of losing formatting in some cases as I've outlined in the previous tickets, code samples, and screenshots.  Here are two of the items pointed out previously that remain unfixed.  

This screenshot shows two ANSI-formatted strings printed out twice.  Once by passing it straight to the print writer, and the second time after being passed through `AttribtuedString.fromAnsi().toAnsi()`.

![image](https://user-images.githubusercontent.com/584009/35397774-efe9194e-01b5-11e8-8342-bcbd2c19925a.png)

The ANSI sequences being used are visible in the screenshot.  You can see there is desirable bold (or high intensity) formatting when printed normally, but that formatting is lost in the `AttributedString` class.  I would like to start using attributed string to take advantage of its color rounding, but not at the cost of formatting regressions.

**Comment by gnodet** [comment]
Would you be able to test the following patch:
```
diff --git a/terminal/src/main/java/org/jline/utils/AttributedCharSequence.java b/terminal/src/main/java/org/jline/utils/AttributedCharSequence.java
index 55e1cfb..eda4ba7 100644
--- a/terminal/src/main/java/org/jline/utils/AttributedCharSequence.java
+++ b/terminal/src/main/java/org/jline/utils/AttributedCharSequence.java
@@ -65,18 +65,6 @@ public abstract class AttributedCharSequence implements CharSequence {
                 } else {
                     sb.append("\033[");
                     boolean first = true;
-                    if ((d & (F_BOLD | F_FAINT)) != 0) {
-                        if (    (d & F_BOLD)  != 0 && (s & F_BOLD)  == 0
-                             || (d & F_FAINT) != 0 && (s & F_FAINT) == 0) {
-                            first = attr(sb, "22", first);
-                        }
-                        if ((d & F_BOLD) != 0 && (s & F_BOLD) != 0) {
-                            first = attr(sb, "1", first);
-                        }
-                        if ((d & F_FAINT) != 0 && (s & F_FAINT) != 0) {
-                            first = attr(sb, "2", first);
-                        }
-                    }
                     if ((d & F_ITALIC) != 0) {
                         first = attr(sb, (s & F_ITALIC) != 0 ? "3" : "23", first);
                     }
@@ -125,6 +113,18 @@ public abstract class AttributedCharSequence implements CharSequence {
                         }
                         background = bg;
                     }
+                    if ((d & (F_BOLD | F_FAINT)) != 0) {
+                        if (    (d & F_BOLD)  != 0 && (s & F_BOLD)  == 0
+                                || (d & F_FAINT) != 0 && (s & F_FAINT) == 0) {
+                            first = attr(sb, "22", first);
+                        }
+                        if ((d & F_BOLD) != 0 && (s & F_BOLD) != 0) {
+                            first = attr(sb, "1", first);
+                        }
+                        if ((d & F_FAINT) != 0 && (s & F_FAINT) != 0) {
+                            first = attr(sb, "2", first);
+                        }
+                    }
                     sb.append("m");
                 }
                 style = s;
```

The reason for the bug is that changing the color resets the bold attributed in the ansi writer, so we need to make sure the bold attributes is set after the color change.

**Comment by bdw429s** [comment]
@gnodet Can you confirm, was this patch meant to fix both 218 and 219?  I see that you already committed it so I pulled the latest and compiled but I can't see a change on either ticket's test case.

**Comment by gnodet** [comment]
The fix is mainly for #218 as #219 does not require any fix in the code, it's mainly a matter of understanding how ConEmu works afaik.  My latest tests shows that cmd will now handle the bold attribute by correctly highlighting the relevant part when going through `AttributedString.fromAnsi().toAnsi()`.

<img width="674" alt="cmd-bold" src="https://user-images.githubusercontent.com/84022/35426400-067542f2-0263-11e8-8b88-46bb44e6aa68.png">

**Comment by bdw429s** [comment]
Those tests might be working, but this one still isn't.  It might help if you tested with the same examples I'm reporting with :)  If you remember from the several times I posted this example on the mailing lists, if I put a space after the first reset, the last half of the string works.  `AttributedString` has a parsing issue that is affected by the whitespace in the string.

![image](https://user-images.githubusercontent.com/584009/35427395-c17defb6-022e-11e8-9b78-f3f97fbda7c3.png)

**Comment by bdw429s** [comment]
>  #219 does not require any fix in the code, it's mainly a matter of understanding how ConEmu works afaik.

Maybe I misunderstood what you said on that ticket, but you said: 

> If the color is 16 - 255, real bold font is used.

I've been testing with a color in the 16-255 range and I'm not seeing bold.  

![image](https://user-images.githubusercontent.com/584009/35427605-13114d7c-0230-11e8-89f5-7e31a0d04bef.png)

**Comment by gnodet** [comment]
In order to enable bold fonts, you need to run the following command in your console, either before or after starting the java vm: `echo ^[[9999;1H` (where `^[` is the `<esc>` char.
This is hinted in https://conemu.github.io/en/AnsiEscapeCodes.html#Description and https://conemu.github.io/en/AnsiEscapeCodes.html#Example_3_scroll_console_to_bottom.
I just spent half an hour trying to understand why it was not working anymore in my console :-(
Once you run the above command, bold is working great.

**Comment by bdw429s** [comment]
Oh, wow, that is just crazy.  

![image](https://user-images.githubusercontent.com/584009/35459657-b612d63c-02a6-11e8-9c8b-726064df08ac.png)

So, ConEMU only does bold when you're scrolled all the way to the bottom "working area" of the terminal?  Surely they don't think that's "working as designed".  I've read those same pages you linked to, but never picked up that scrolling into the "working area" was a requirement for formatting to actually work!  I'd love to hear an explanation from ConEMU on why it works this way.  

So question, do you want to add the `^[[9999;1H` to JLine as something that happens automatically when using ConEMU, or will I need to do that myself?

And a corollary question:  now that we know that bold only works on colors above 16 (which seems like another boneheaded move on ConEMU's part) I wonder if I would be better off changing all my primary colors to use a 15-255 equivalent.  16-color terminals would just round back down (hopefully) and ConEMU would always show bold.  Thoughts?

-------------------------

Were you able to reproduce the remaining issue I posted above where `AttributedString` the bold isn't happening with the background colors applied?

```
ESC[34mESC[47mESC[1mblue on whiteESC[0mESC[31mESC[42mESC[1mred on greenESC[0m
```

**Comment by gnodet** [comment]
See comments on #219 ...
Fwiw, I think ConEMU is limited because it reuses the windows underlying console so that standard applications can be reused, while other things like cygwin don't have this backward compatibility problem and thus have written a new full and working terminal implementation...

**Comment by bdw429s** [comment]
I think everything is cleaned up now on this issue, even though it ended up overlapping quite a bit with https://github.com/jline/jline3/issues/219. Thx for your work on it.
