### ISSUE TITLE
Can't print bold text in Windows / ConEMU

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#219]
This has always been an issue with ConEMU but I've been ignoring it thus far.  Now that you've formalized some support specifically for ConEMU, I wanted to document this in case there's something we can do.

I'm 99% sure the ConEMU terminal supports bold text.  There is a "bold" checkbox in the settings which you can click to turn ALL your terminal text bold:

![image](https://user-images.githubusercontent.com/584009/35398876-975864b2-01b8-11e8-8cf5-61853e688fd3.png)

However none of the ANSI formatting I've tried will actually cause bold text to appear in the terminal alongside "normal" text.  I'm unclear on whether this is a problem with the terminal itself or if JLine isn't recognising the terminal correctly and isn't sending the proper ANSI escapes.

In some cases, the `AttributedString` class changes the color of colored bold text in ConEMU which leads me to believe that JLine doesn't think bold is possible.  

![image](https://user-images.githubusercontent.com/584009/35398610-f63fd2a4-01b7-11e8-924a-d072537670c8.png)

**Comment by gnodet** [comment]
ConEmu has very limited support for bold, see https://conemu.github.io/en/FaqBoldItalic.html#Xterm-256_emulation.

I made some experiments and I think I understand how it works.  If the current text color is 0 to 7 and you turn bold on, it will switch the color to 8 - 15.  If your color is 8 - 15, nothing happens.  If the color is 16 - 255, real bold font is used.

**Comment by gnodet** [comment]
<img width="928" alt="conemu-bold" src="https://user-images.githubusercontent.com/84022/35407871-837702a0-020d-11e8-9ecf-ce88f5894541.png">

**Comment by gnodet** [comment]
Also, note that the default palette from ConEmu makes colors 4-7 very close to the higlighted ones 12-15.

**Comment by bdw429s** [comment]
Very interesting observations.  I've been through the ConEMU docs, including the page you linked to, but could never get a straight answer.  I'm surprised they don't document their behavior better.

**Comment by gnodet** [comment]
My last commit should fix the issue: it will toggle the "working area" mode to get bold when the terminal is initialized and it will use the extended `\e38;5;xm` syntax to make sure bold is always used, so that the user does not have to care about anything when using the `AttributedString` to output to the terminal.

**Comment by bdw429s** [comment]
Are you saying that if I use an primary color escape like `^[[32m^[[1mtest^[[0m` on ConEMU then you'll take the `32m` and turn it into a `38;5;xm` color that's equivalent to green so that the bold will also work?  I just built the bleeding edge code but I'm not seeing that behavior on ConEMU.  There's still only true bold for colors that I specify over 16.

**Comment by gnodet** [comment]
It works for me:
<img width="514" alt="conemu-bold2" src="https://user-images.githubusercontent.com/84022/35469407-33d247b4-0334-11e8-826d-ad3f2c01d248.png">

**Comment by bdw429s** [comment]
Can you check and make sure that all your local changes got committed?  I built the very latest commits you added today and that's the jar I'm using.  You still didn't test with the exact ANSI I showed in my example, so I changed my example to match yours so we'd be on the same playing field.

![image](https://user-images.githubusercontent.com/584009/35469620-2bd22ab0-02fe-11e8-8cda-50bdf9001c1c.png)

As you can see, ConEMU is still just doing the color swap for me and not any actual bold.  My full example looks like this:

```js
var E = chr(27);
var string = createObject("java","org.jline.utils.AttributedString")
	.fromAnsi( '#E#[47m#E#[34mblue o#E#[1mn white#E#[42;31mred o#E#[22mn green#E#[0m' )
	.toAnsi();
reader.getTerminal().writer().print( string );
reader.getTerminal().writer().flush();
```

**Comment by bdw429s** [comment]
I should have included this.  In my example above, the output of the `toAnsi()` function which gets placed in the `string` variable is:

```
ESC[34;47mblue oESC[1mn whiteESC[31;42;1mred oESC[22mn greenESC[0m
```

None of the colors are being converted to the `^[[38;5;xm` versions.

**Comment by gnodet** [comment]
Yes, that's expected.  It's a ConEMU specific feature, so it only turns on when the Terminal is a ConEMU one, so you need to use the `toAnsi(terminal)` call instead of `toAnsi()`.

Heres's what I have to show the difference:
<img width="832" alt="conemu-bold3" src="https://user-images.githubusercontent.com/84022/35470643-8c7bf086-034d-11e8-8fdc-78d8617b18b2.png">

**Comment by bdw429s** [comment]
Ahh, the missing piece of information!  We are in business now, my friend:

![image](https://user-images.githubusercontent.com/584009/35474562-95d1db3e-0355-11e8-8c6f-23baeeaa8dd7.png)

I saw the reference to `$.terminal` in your examples but since I didn't recognize the syntax, I didn't realize it was an argument to the `toAnsi()` method.
