### ISSUE TITLE
Multi Line Prompt Breaks On Windows Command Prompt

### ISSUE THREAD

**Issue by cjohnstoninv** [jline/jline3#220]
Using Windows 10 Command Prompt, a LineReader that gets a multi-line prompt works fine unless the window is resized. On window resize the prompt and the input become separated.  This does not happen when running the same JAR from Cygwin on resize, it is just isolated to Command Prompt.

Edit: This only happens on a width resize. Height works fine.
Edit (Clarification): The input cursor moves with the resize and is not properly reset to where the cursor previously was.

**Comment by gnodet** [comment]
Could you add a screenshot please ? I'll try to reproduce and fix it asap.

**Comment by bdw429s** [comment]
I can confirm this issue on my Windows 10 laptop.  Here's the initial load of my multi-line prompt

![image](https://user-images.githubusercontent.com/584009/35541665-78114b0c-0521-11e8-973d-52b1d039935a.png)

After widening the window, the cursor has been drug out to the middle of the window.

![image](https://user-images.githubusercontent.com/584009/35541588-2b203e34-0521-11e8-9a7e-66af481e0742.png)

**Comment by bdw429s** [comment]
A similar, but slightly different behavior happens in ConEMU.  Here is the initial load:

![image](https://user-images.githubusercontent.com/584009/35541722-bde3a10c-0521-11e8-95fa-7d17a04c56c9.png)

After the horizontal resize, the cursor gets pushed down to a new line.

![image](https://user-images.githubusercontent.com/584009/35541732-cf4576c8-0521-11e8-9d92-1f0ebf3ef9e8.png)

**Comment by cjohnstoninv** [comment]
Thanks for the screenshots, the Windows 10 CMD prompt one is similar to what I am experiencing.

**Comment by gnodet** [comment]
Are you sure you don't have any hidden right prompt ?
I've been able to reproduce the problem, but only with a right prompt.
I also wonder if that's related to #136

**Comment by gnodet** [comment]
Actually, I think the problem comes from the Jansi terminal. Could you remove jansi and add jna library to your classpath and see if it works better for you ?
