### ISSUE TITLE
History file doesn't escape carriage returns and errors if you enter one

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#223]
In some terminals like Windows cmd, I can enter a command that has a carriage return in it using `Ctrl-V` followed by `Enter`.  But then it puts an entry in my history file that looks like this:

```
1517272636179:echo brad
wood
```
Then JLine will blow up with this error:
```
java.lang.IllegalArgumentException: Bad history file syntax! The history file `C:\Users\Brad Wood\.CommandBox\.history-command` may be an older history: please remove it or use a different history file.
```

If I enter a line feed with `Ctrl-V` followed by `Ctrl-J` then the history file looks like this and JLine doesn't blow up.

```
1517273527331:echo "brad\nwood"
```

**Comment by gnodet** [comment]
This is actually not specific to windows.  The same thing happens for me on osx.
