### ISSUE TITLE
STDERR Writer

### ISSUE THREAD

**Issue by cjohnstoninv** [jline/jline3#229]
Would it be possible for JLine to have a separate writer that wrote the JVM's STDERR instead of STDOUT? Or is this just simply write to STDERR.....?

**Comment by gnodet** [comment]
This is a shell feature, not a terminal related feature.  In the JLine demo, which is using Gogo, there is this concept of stderr stream which can be redirected / piped when running commands, but at the end, the terminal always has a single output steam which is... the terminal.
The only difference between the system out and system err streams is that they can be redirected independently.  If you want to do that, then the responsibility lies on the system which handle the streams redirection / piping / etc...

**Comment by cjohnstoninv** [comment]
I found that the AnsiConsole class of JANSI gives me access to an ANSI safe STDERR stream (which was really all I needed). My application is shell like so being able to redirect STDOUT and STDERR is required. Unless you see this causing any issues with JLine the AnsiConsole STDERR has been working fine for me so far. Thanks!
