### ISSUE TITLE
Add option to append command history instead of overwriting it

### ISSUE THREAD

**Issue by tadayosi** [jline/jline3#23]
See also:
- https://issues.apache.org/jira/browse/KARAF-4735
- https://issues.jboss.org/browse/ENTESB-3833

Currently, `FileHistory` only dumps the entire command history instead of appending it to the history file. So if multiple terminals are used in the same machine the history is overwritten.

**Comment by gnodet** [comment]
The whole history mechanism would need a bit of love...

**Comment by tadayosi** [comment]
@gnodet Are you saying that it's rather better to refactor the whole `History`, `MemoryHistory`, and `FileHistory` interface/classes?  Actually I thought the same idea while working on the PR, too. The history mechanism can be much simpler for JLine 3. So +1.

A few ideas:
- Is it really necessary for `History` interface to extend `Iterable`?
- Do we really need the finer manipulation operations: `set(int, CharSequence)`, `remove(int)`, `removeFirst()`, `removeLast()`, and `replace(CharSequence)`?

**Comment by gnodet** [comment]
Wanna give your thoughts to the refactoring at  https://github.com/gnodet/jline3/tree/issue-23 ?

**Comment by tadayosi** [comment]
@gnodet Your refactoring looks really nice!

But one thing I don't yet understand is what the `HISTORY_SHARED` option means and how the option relates to `History.load()` [1]. In the original `FileHistory` `load()` is invoked every time an instance is created, but in the new `DefaultHistory` impl `load()` is never invoked unless the `HISTORY_SHARED` option is set. In this new `load()` , `itemsToAppend` is filled up as well as `items` [2] so I don't understand why it doesn't lead to write the entire history twice in the default APPEND mode.

Possibly it's just that I don't yet fully understand your new implementation, though...

[1] https://github.com/gnodet/jline3/commit/44703284219e5c09b6b4ca683da0439465f388fa#diff-cb9de590eb4856d2a638aa3859812915R464
[2] https://github.com/gnodet/jline3/commit/44703284219e5c09b6b4ca683da0439465f388fa#diff-70a9b0d985fbd4c61ab7b1f829ebf5e5R77

**Comment by gnodet** [comment]
Yes, I'll remove the ```HISTORY_SHARED``` option for now (the goal was that new additions would be available immediately in other sessions). I'll fix the behavior anyway.

**Comment by tadayosi** [comment]
Thanks @gnodet! Looks great now.

But let me add one more thing :-)  Your latest commit introduced `HISTORY_APPEND` option but it doesn't seem to be used anywhere including `DefaultHistory`. Is that intentional?

**Comment by gnodet** [comment]
I'm not sure about the benefit of *not* using append actually, so I've removed the option.
If you have a valid use case, I can add it back.
