### ISSUE TITLE
Any chance of reviving inputrc support?

### ISSUE THREAD

**Issue by trptcolin** [jline/jline3#230]
Hi, I see from the code and a google groups post that `inputrc` support is removed from jline3. Is there a rationale somewhere for this, or can you provide it here? I foresee some demand for it from users based on jline2 implementation usage in the wild (clojure repl stuff). The core value I see is being able to configure the keymap as an end user without a ton of custom code for each jline3 implementer. Also nice is that `inputrc` works for other readline consumers, but a more limited custom config file format would still solve the core issue from my perspective.

**Comment by gnodet** [comment]
The main problem with the `inputrc` file is that it's very bash centric.  JLine3 has moved more towards zsh instead.  The other problem is that it's a shared configuration file.

That said, have a simple file to configure keymaps, variables and options would be a good idea.  We could definitely reuse the inputrc code with a small adaptation to cover new jline3 features.
