### ISSUE TITLE
put display behind a lock or a queue so that redisplay's can't conflict with initial display

### ISSUE THREAD

**Issue by bhauman** [jline/jline3#233]
When I have concurrent output that I'm redirecting above around the active readline editor, conflicts can happen when a fresh readline is displayed.

**Comment by gnodet** [comment]
Could you be more precise please ?
Fwiw, there's no thread safety concerns in jline, so you are responsible for synchronizing access to the Terminal if you're using multiple threads.

**Comment by bhauman** [comment]
Sorry for not being clear:

There is a bit of a problem in that calls to `display.update` can happen concurrently.  I can easily make sure any calls I make to `redrawline` and `redisplay` are synchronized.

It's much harder for me to synchronize my calls to `redisplay` with the *initial* calls to `redisplay` that are inside the `readLine` method itself, 
https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L523
because my calls to redisplay are happening while the readline is engaged.

Maybe consider adding `synchronized` to the `reDisplay` method signature?

cc/ @trptcolin

**Comment by bhauman** [comment]
No I'm failrly certain that adding `synchronized` to `redisplay` will fix this.

**Comment by bhauman** [comment]
sweet!
