### ISSUE TITLE
jline jar is large - can we split it up?

### ISSUE THREAD

**Issue by PerBothner** [jline/jline3#234]
jline-3.6.2-SNAPSHOT.jar is 687863 bytes, which is a lot for basically a `readline` replacement (with admittedly some valuable extra features).  Perhaps we could have a slimmed-down `jline-base.jar` and a "complete" `jline-all.jar`? For the former, leave out the builtins and the telnet and ssh support, to start with.  I'm not familiar with all the classes, but there are probably more that are seldom used.  I realize one person's obscure class is another person's critical one, so some back-and-forth may be needed until we settle on a good set.

**Comment by Minecrell** [comment]
This was already done as part of #62. `jline` is the JAR that has everything in it (so basically what you call `jline-all`), but the modules are also available separately as:

- `jline-terminal`
- `jline-terminal-jna` / `jline-terminal-jansi`
- `jline-reader`
- etc, see [`org.jline` group on Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cg%3A"org.jline")

**Comment by PerBothner** [comment]
Having to use multiple jar files is a bit more complicated.  Especially since the directory layout is awkward, with all the various jars spread out in different sub-directories.

Consider an `autotools` application, where we want configure to have a `--with-jline=PATH` option. (Similar issues apply with other build tools.)That is difficult, because there are two variables: The root directory of the jline directory *and* the version number.  Converting a `PATH` option to a list of jar files isn't really possible in any clean way. One could do something like `--with-jline=PATH:VERSION` but that is ugly.  The configure script could figure out the jline version number by seeing what is the in the PATH, though that is also fragile (though better than having to specify it to the confifyre command).

One fix would be a `dist` directory containing all the public jar files, but that wouldn't solve the problem unless you leave off the version number from the jar files.  (Which I would much prefer, regardless.  When I compile a C program I don't have to hard-wire in version numbers of libraries, so why do I have to for Java programs?)

Finally, the documentation in the README.md doesn't explain what the build results are.  It should list the various jars, where they are, and when you might need one or the other.

**Comment by Minecrell** [comment]
Just like you use `autotools` or similar tools to build C projects, Java projects are usually built using build systems like [Gradle] or [Maven]. With these, all you need to do is define a dependency on one or more modules of JLine, and it will automatically handle fetching prebuilt JARs from Maven Central, or locally built projects from a local Maven repository (located at `~/.m2/repository` in a standardized layout).

The build system then also provides ways to bundle all your dependencies into a ZIP or a single JAR file, which means you never need to bother with all the JAR files yourself.

The same applies when building JLine from source: While the build system could be configured to place all built JAR files into a `dist` directory, you usually build Maven projects with the `install` goal, which places the built JAR files into the local Maven repository. When this is done, you can reference them directly from your build system, without any knowledge about JLine's project layout. You're not supposed to take all the JARs manually out of the build directory.

[Gradle]: https://gradle.org
[Maven]: https://maven.apache.org

**Comment by PerBothner** [comment]
Autotools still has some benefits. Mainly it's the status quo and what I'm familiar with. It also integrates well with GNU/Linux guidelines and packaging. Plus I also deal a lot with JavaScript and npm and there are only so many tools I can learn per year :-(

It might be reasonable to hack my configure script so that`--with-jline=VERSION` looks into  `~/.m2/repository/org/jline`.

It would still be helpful to add to the `README.md` a list of the jars and when you might use them. It could mention that they get installed into `~/.m2/repository/org/jline` for those of us with limited knowledge of Maven.  I should probably create a separate issue that that. I'll see what Guillaume has to say.

**Comment by gnodet** [comment]
I'm not really keen on bringing C/C++ "standards" development recipes into JLine build, which is really java/maven based. However, if that's really helpful, I'd go for adding a {{dist}} module which would contain jline smaller jars, and eventually the dependencies.  The problem is that what you want to actually pick also depends on other factors which are outside JLine.  For example, you can use either JNA or jansi, but both are not needed.  
Maybe what is needed in a NPM or similar, but I'm not too familiar with writing those.

In all cases, the {{README.md}} can easily be augmented with the non obvious informations for people not familiar with maven.  @PerBothner do you want to provided those ?

**Comment by PerBothner** [comment]
As an aside: make-based build standards have a lot going for them, even for Java. (The syntax is certainly much more pleasant than XML-based syntax.)

_"The problem is that what you want to actually pick also depends on other factors which are outside JLine. For example, you can use either JNA or jansi, but both are not needed."_

As a start it would be helpful to document the various jars produced.  Perhaps below the `Build`/`Requirements` section in `README.md` a section `Using the build` or `Build results` or `Build artifacts`. This should list each (non-internal) jar with a sentence of two about what it is useful for. (For example I have no idea when you'd use JNA or jansi.) It should also mention that they get installed into `~/.m2/repository/org/jline`.

I myself am pretty clueless about Maven, and I'm hoping to keep it that way. I have slightly more clue about npm.

**Comment by PerBothner** [comment]
Much better.  Thanks. Still a little unclear which jars you should use if you want a plain "readline for Java" experience.  Also unclear when you'd use jansi and when jna.
