### ISSUE TITLE
Attributed string adds underline in ConEMU

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#236]
When outputting colors 8-15 of the 256-color scheme via `AttributedString` in Windows ConEMU, underline is added even though it wasn't specified in the ANSI escape sequence.  

Here is an example of the ANSI escape being used.  This should simply be word "test" as black text on a white background.
```
ESC[38;5;0mESC[48;5;15mtestESC[0m
```
It works when printed directly, but when passed through `AttributedString`, this is what it looks like:

![image](https://user-images.githubusercontent.com/584009/37077701-b7f3a200-21a1-11e8-92a1-f691c6aa9024.png)

**Comment by gnodet** [comment]
Could you check if this works for you ?

**Comment by bdw429s** [comment]
@gnodet Nailed it! :rocket:
