### ISSUE TITLE
How to keep prompt at bottom on jline3?

### ISSUE THREAD

**Issue by tomocrafter** [jline/jline3#240]
With log4j2,
I tried demo's this one, but it doesn't work properly when using log4j.
![image](https://user-images.githubusercontent.com/10905364/37642959-6284bf9a-2c62-11e8-966d-e32f3ee01cf5.png)

**Comment by Minecrell** [comment]
Unrelated to your issue (not sure right now, it looks fine), but if you're using log4j2, you might want to give [TerminalConsoleAppender](https://github.com/Minecrell/TerminalConsoleAppender) a try. It's specifically made for this purpose, to log output while listening for console input at the same time.

**Comment by tomocrafter** [comment]
Thanks for replying and suggestions.
But now I already made my own Logger  and jline version has been downgraded to 2 so this problem has been fixed.

**Comment by tomocrafter** [comment]
Well, when i became I have to use log4j and jline3, I'll be there again.

**Comment by tomocrafter** [comment]
Well, when i became I have to use log4j and jline3, I'll be there again.
