### ISSUE TITLE
Typing into i-search sometimes toggles showing results every other char

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#244]
I haven't found out exactly why this doesn't happen every single time, but I'm very commonly seeing a behavior where filtering my i-search while typing a word that is an exact match for an item in my history toggles the result on and off meaning it only shows up every other character.

For instance, I have a history item that is the word "history". Right now if I press Ctrl-S and starting typing, here is the result:
* I type "h" --> the match "history" is displayed
* I add an "i' for "hi" --> the results disappear and nothing is matched
* I add an "s" for "his" -->  the match "history" is displayed again
* I add a "t" for "hist" --> the results disappear and nothing is matched 
* I add an "o" for "histo" -->  the match "history" is displayed again 
* I add a "r" for "histor" --> the results disappear and nothing is matched  
* I add a "y" for "history" -->  the match "history" is displayed again  

I think it has to do with only having a single matching line in my history.  Try clearing your history and only adding a few unique test lines to try this.

**Comment by gnodet** [comment]
Hopefuly this is fixed with the rewrite of i-search.

**Comment by bdw429s** [comment]
Thanks @gnodet , I'll give it a test.
