### ISSUE TITLE
Command completion with quoted and unquoted values

### ISSUE THREAD

**Issue by csetera** [jline/jline3#245]
As discussed in the users forum, I have a use case where I want to provide completion of a value that may or may not have a space.  What I was trying to do was alter the value of a Candidate to automatically add the quotes only if they were necessary.  However, that means that JLine will automatically filter those candidates if the user didn't start the completion with a quote.  I can't seem to figure out a way to solve for completing these values that does not require the user to start the prompt with a quote.  

After further thought since I sent that to the group, it seems to me that the way I would want to approach this (if I were to attempt to create the changes) would be to have another boolean value "quoted" on the Candidate class.  If that value is true when the value is inserted by Jline, it automatically quotes the value being inserted.  That allows the candidate to match properly, but also to provide the proper result.  It also means that there is no guesswork in if/when to quote because the Candidate is making that choice.

**Comment by csetera** [comment]
For what it's worth, using escaping does work for this use case.  I still think auto-quoting would be a really nice feature, but with escaping working my need is lower priority.

**Comment by gnodet** [comment]
This is related to #125
