### ISSUE TITLE
NPE when clearing screen prior to showing first prompt

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#255]
I was experimenting with outputting some sort of "loading" text (via direct system.out writing) while my console app loaded.  I wanted to clear out the screen prior to showing the prompt once the app was loaded, but when I call `reader.clearScreen()` as the first thing my program does prior to actually using the prompt the first time, I get an NPE.

```
java.lang.NullPointerException
        at org.jline.reader.impl.LineReaderImpl.redrawLine(LineReaderImpl.java:662)
        at org.jline.reader.impl.LineReaderImpl.clearScreen(LineReaderImpl.java:5136)
        ...
```

Calling `reader.clearScreen()` at any later point in my program is always fine.

**Comment by gnodet** [comment]
You're not supposed to call `reader.clearScreen()` unless you are inside a callback from the reader.
Outside, you should simply call:
```
terminal.puts(Capability.clear_screen);
terminal.flush();
```

**Comment by bdw429s** [comment]
Thanks for the information.
