### ISSUE TITLE
Encoding issue with JLine

### ISSUE THREAD

**Issue by Mrodent** [jline/jline3#259]
I am finding that more "exotic" Unicode characters don't seem to be encoded properly on entering them.  Using W10 and Cygwin, org.jline.terminal.impl.PosixSysTerminal and org.jline.utils.NonBlocking$NonBlockingInputStreamReader.

I have no idea what is going on: details [here](https://stackoverflow.com/questions/50009594/encoding-issue-with-jline).

**Comment by gnodet** [comment]
Could you debug, put a breakpoint or a trace at the following location:
  https://github.com/jline/jline3/blob/master/terminal-jna/src/main/java/org/jline/terminal/impl/jna/win/JnaWinSysTerminal.java#L92
The idea would be to look at the `keyEvent.uChar.UnicodeChar` value and see if you see the correct `ẃ` char.

**Comment by gnodet** [comment]
Did you solve your issues ?  Bug reports should be tracked here and not on Stackoverflow...
Let me know if you need more.

**Comment by gnodet** [comment]
I've reproduced the problem on cygwin. The default encoding of the java platform is `windows-1252` and that's the one used when decoding the terminal input stream instead of `UTF-8` as indicated by my `LANG=en_US.UTF-8` environment variable.

**Comment by gnodet** [comment]
In such cases, the best way is to set the `org.jline.terminal.encoding` system variable and the cygwin terminal encoding  correctly.
