### ISSUE TITLE
JLine the contract for NonBlockingReader seems broken

### ISSUE THREAD

**Issue by Mrodent** [jline/jline3#260]
The `peek` method is meant to wait for a given time (the Javadoc from the source doesn't actually say what the units are for `timeout`, but I presume milliseconds).

But according to my experiments `peek` blocks forever, until you enter something new... 

Details [here](https://stackoverflow.com/questions/50016620/jline-the-contract-for-nonblockingreader-seems-broken)

**Comment by gnodet** [comment]
I haven't seen any real JLine issue in your problems yet.  Please reopen if needed.
