### ISSUE TITLE
LineReader readline can return null

### ISSUE THREAD

**Issue by tpoliaw** [jline/jline3#265]
If using a LineReader with a Terminal in front of a remote connection (similar to the ssh and telnet examples) and the connection is closed (eg network failure), readline returns `null` instead of throwing a more useful `EndOfFileException`, `ClosedException` or `IOException`.

**Comment by facingBackwards** [comment]
I'm happy to submit a PR for this but I'm not sure which level would be best to handle it.
* The readline method itself
* BindingReader.readCharacter
* One of the read methods in the NonBlockingReader/InputStream

**Comment by gnodet** [comment]
I agree, there's definitely some place for improvements in this area. 
`EndOfFileException` is thrown when using `Ctrl+D`.  The telnet protocol has a `CONNECTION_LOGOUTREQUEST` event which is not properly propagated in jline btw.

If a stream or similar has been closed, a `ClosedException` should be thrown. The `NonBlockingReader` and `NonBlockingInputStream` should respect their main interface semantic, so return `-1` for EOF and throw an IOException for a network failure.

The `LineReaderImpl` has a `return null` statement which should be replaced.

**Comment by gnodet** [comment]
Related to #267 which needs to be fixed too.
