### ISSUE TITLE
input stream supplied to TerminalBuilder.streams() is consumed when a terminal instance gets created

### ISSUE THREAD

**Issue by hflzh** [jline/jline3#266]
There is an issue with the Terminal implementation that the input stream supplied to the terminal over the `TerminalBuilder.streams(InputStream, OutputStream)` API is consumed when the Terminal instance gets created. I think the input stream should not be consumed until the `LineReader.readLine()` API is called. A code snippet that reproduces the issue is as follows:

```
    System.out.println("=== JLine 3 Test  ===");
    LineReaderBuilder lrb = LineReaderBuilder.builder();
    TerminalBuilder tb = TerminalBuilder.builder();
    InputStream in = new FileInputStream("/home/user/input.txt");
    Terminal term = tb.system(false).streams(in, System.out).build();
    System.out.println("=== terminal type: " + term.getType());
//       lrb.terminal(term);
//       LineReader lr = lrb.build();
//       while (true) {
//            String str = lr.readLine();
//            if ("exit".equals(str))
//                break;
//       }
    term.close();
    System.out.println("=== done");
```

**content of the /home/user/input.txt file:**

> test 1
> test 2
> test 3
> exit

**Output:**

> === JLine 3 Test ===
> === terminal type: xterm
> === done
> test 1
> test 2
> test 3
> exit

**Comment by hflzh** [comment]
Hi @gnodet ,

I tried with 3.7.1-SNAPSHOT that includes the changeset [a67d60f](https://github.com/jline/jline3/commit/a67d60f5de6f5b8dc6de86b52fa1c3babb466b57) , I was able to create a terminal in paused state, however, when I resumed the terminal, the streams were consumed (in a separate thread?) and LineReader#readLine() was not able to read the content from input stream, instead, it hit the `EndOfFileException`.

```
System.err.println("=== JLine 3 Test  ===");
LineReaderBuilder lrb = LineReaderBuilder.builder();
TerminalBuilder tb = TerminalBuilder.builder();
InputStream in = new FileInputStream("/home/user/input.txt");
Terminal term = tb.system(false).streams(in, System.out).paused(true).build();
System.err.println("=== terminal type: " + term.getType());
lrb.terminal(term);
LineReader lr = lrb.build();
while (true) {
   if (term.paused()) {
       System.err.println("=== resuming terminal ...");
       term.resume();
   }
   try {
       String str = lr.readLine();
       System.err.println("=== readLine() returned: " + str);
       if ("exit".equals(str))
           break;
   } catch (Exception ex) {
       System.err.println("================= ");
       System.err.println("=== Caught exception: " + ex.getMessage());
       ex.printStackTrace(System.err);
       System.err.println("================= ");
       break;
   }
}
term.close();
System.err.println("=== done");
```

Output:

```
=== JLine 3 Test  ===
=== terminal type: xterm-256color
=== resuming terminal ...
test 1
test 2
M
test 3
exit
================= 
=== Caught exception: null
org.jline.reader.EndOfFileException
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:524)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:373)
	at test.JLine3Test.test10(JLine3Test.java:177)
	at test.JLine3Test.main(JLine3Test.java:27)
================= 
=== done
```

**Comment by gnodet** [comment]
It looks ok to me.
You're getting an EndOfFileException because of the changes in #265, but that's expected, unless I'm missing something.... 
Your test file includes the following lines, right ?
```
test 1
test 2
M
test 3
exit
```

**Comment by hflzh** [comment]
Yes, /home/user/input.txt:

> test 1
> test 2
> M
> test 3
> exit

But I did not inject any IO exception in the test code, and I expected the LineReader#readLine() to read and return the lines (test1, test2,...) from input.txt , but it did not.

**Comment by gnodet** [comment]
I've just fixed the problem as part of #267.

**Comment by gnodet** [comment]
1./ The behavior with the redirection is ok because JLine expects the terminal to be set up correctly, but you forgot to indicate the type of terminal on the builder.
```
tb.type("the terminal type")
```
If your terminal is not a real terminal and does not support ansi sequences, you should use the `dumb` type and it should not prompt those control sequences.

2./ You can control the behavior using `terminal.echo(true)` if you want the input to be echoed.

**Comment by hflzh** [comment]
Got it, Thanks very much!
