### ISSUE TITLE
Non-completable candidates

### ISSUE THREAD

**Issue by AndreasVoellmy** [jline/jline3#268]
In my program, I'd like to have completion candidates that display, but don't actually fill in anything on completion. For example, at a certain point in a command, if the user invokes completion, then they might see some keywords that they can continue with, but also something like "\<number\>" or "\<ipv4 address\>". It's nice to show these, since the user could continue with these choices, but I don't want to fill in the format name (e.g. the string "\<number\>") onto the input line, since the user then has to immediately delete the inserted text.

One "solution" is that I can use the multi-parameter constructor for Candidate to set value to be empty string, which sort of works. But this doesn't totally work, because if there are multiple Candidates with the same value, only the first is shown (at least that seems to be the behavior I observed). Is there any way to turn this behavior off? 

Or is there some other way of achieving my goal that is more appropriate with JLine3's API?

FWIW, I've worked with CodeMirror before, and its candidates can be given a `hint` function that applies the selected completion (https://codemirror.net/doc/manual.html#addon_show-hint). Using that, you can override to "do nothing". Something like that would be useful here.

**Comment by gnodet** [comment]
You need to create the {{Candidate}} with an empty {{value}}, but also a unique {{key}}.  This way, candidates should not be merged together.

Just a though that could be useful: JLine has a "suggestion" mechanism that is currently used when the parser detects a missing closing quote, parenthesis, curly bracket or similar.  You could have your parser throw an {{EOFError}} and use the {{missing}} field to specify {{<number>}} or {{<ip>}}.  This should then be displayed in light gray on the edit line.

**Comment by gnodet** [comment]
This would also be a good use case for #254 ...

**Comment by gnodet** [comment]
I'm closing this one, please reopen if needed.
