### ISSUE TITLE
ANSI escape sequences doesn't works on Windows 7 command line

### ISSUE THREAD

**Issue by alexander-shustanov** [jline/jline3#275]
When I try use ANSI escape sequences on Windows 7 command line to specify text color, it produces something like this
```
←[34m My text ←[m 
```
So, Is there any ability to figure out if ANSI escape sequences are not supported by current terminal? Terminal, created by jline, is DumbTerminal.

**Comment by gnodet** [comment]
Do you have the jansi or jna library on your classpath ? Windows support requires one of these libraries.

**Comment by gnodet** [comment]
Closing this issue, please reopen if needed.
