### ISSUE TITLE
Missing function to update completers

### ISSUE THREAD

**Issue by DevCubeHD** [jline/jline3#281]
There really should be a method to update the completer of a LineReader while it's running.
Thanks!

**Comment by DevCubeHD** [comment]
Thats hard to be more precise :D

I think a method in the LineReader to update the completer would be useful since not every implementation is static.

E.g. there are devs that can implement more commands via an API to my terminal.. the command contains its Argument nodes, but I cannot tell the reader because it does only update ist completer on initiation.

**Comment by gnodet** [comment]
That's a start, but I'm still not completely with you.  What do you mean by _update its completer_ ? A completer does not have to be static, for example the [`org.jline.builtins.Completers$Completer`](https://github.com/jline/jline3/blob/master/builtins/src/main/java/org/jline/builtins/Completers.java#L59) grabs its data from the [`CompletionEnvironment`](https://github.com/jline/jline3/blob/master/builtins/src/main/java/org/jline/builtins/Completers.java#L37-L57) which can then be updated at will between calls to `readline()`.  That's what is done in the main JLine demo, where the `CompletionEnvironment` is actually filled by running a set of commands : [this actually happens during initialisation](https://github.com/apache/felix/blob/trunk/gogo/jline/src/main/resources/gosh_profile#L92-L101), but the commands are accessible from the shell and calling the `complete` command will actually affect the current shell completion system.

**Comment by DevCubeHD** [comment]
Could be that you are right but there is a chance we misunderstood each other. It is simple to find out:
Can you send me an example how I add a node to a `TreeCompleter `after initializing the `LineReader`?

**Comment by gnodet** [comment]
The `TreeCompleter` is static, but you could easily wrap it in a more dynamic completer:
```
    public class DelegateCompleter implements Completer {
        
        Completer delegate;

        @Override
        public void complete(LineReader reader, ParsedLine line, List<Candidate> candidates) {
            delegate.complete(reader, line, candidates);
        }

        public void setCompleter(Completer delegate) {
            this.delegate = delegate;
        }
    }
```

So that you can then keep a reference to that completer and call the following whenever you need
```
theCompleter.setCompleter(new TreeCompleter(xxx));
```

**Comment by DevCubeHD** [comment]
Thanks a lot! 
Your high availability for a free resource is much appreciated Sir!
You are awesome! Keep on going.

**Comment by DevCubeHD** [comment]
//CLOSE
