### ISSUE TITLE
Change in scroll behaviour when using the status

### ISSUE THREAD

**Issue by tpoliaw** [jline/jline3#289]
I have just tried the new Status feature (#286) and it works well except it changes the scrolling behaviour. Without it, scrolling scrolls the terminal as expected. After the first time the status is updated, scrolling scrolls through the history instead.

Is there any way of maintaining the old 'scroll the terminal' behaviour?

Thanks for adding the status bar. It works well.

This is using an ExternalTerminal (with TERM=xterm-256color if that affects it).

**Comment by gnodet** [comment]
Could you give me a bit more information, I can't reproduce it locally.  I've tried connecting through SSH, but everything seems fine.
What's your OS/terminal software ?  Scrolling is partially handled by the terminal emulator which turns mouse events into up/down keystrokes.

**Comment by tpoliaw** [comment]
This is accessing jline via SSH. It is running on an RHEL 6 machine and I'm connecting to it from gnome-terminal on either the local machine or from an Ubuntu machine elsewhere.

Looking into it a bit more it seems to be a gnome-terminal issue. Using xterm (from either machine), scrolling seems to be ok although it has other problems around resizing (do you want me to open a new issue for that?)

**Comment by tpoliaw** [comment]
I have written a [demo class](https://gist.github.com/tpoliaw/bc5ceb7d6b0bfaa0335f2fe2b932fccc) (same as for #290) that shows this behaviour. 

With the class as is, it works as expected. With the `status.update` line uncommented, scrolling the mouse now does nothing (would scroll history if there was any).

**Comment by gnodet** [comment]
I've tried on a debian (jessie) VM / gnome-terminal 3.14.1 and the mouse wheel works correctly with the status bar.

**Comment by tpoliaw** [comment]
Thanks for looking at this. I think you can probably close it as a gnome-terminal bug. The version included in RHEL6 is 2.31.3. I've tried it with a new version on Ubuntu and it appears to work as expected.
