### ISSUE TITLE
Autocomplete options are shown in random order

### ISSUE THREAD

**Issue by tpoliaw** [jline/jline3#290]
Using 3.7 and 3.8 autocompletion options are shown in a random order in the menu.

A demo class showing this behaviour is [here](https://gist.github.com/tpoliaw/bc5ceb7d6b0bfaa0335f2fe2b932fccc). I would expect completing on 'a' to give the options in alphabetical order (the order generated), instead I get 

    ac_helloWorld   ad_helloWorld   ab_helloWorld   ae_helloWorld   aa_helloWorld

**Comment by gnodet** [comment]
You're right, the candidates should be ordered using the following comparator:
  https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L4157-L4164
I'll fix the problem asap.

**Comment by tpoliaw** [comment]
Thanks for looking at this. I'm now getting test errors from CompletionTest.testListAndMenu which I assume is from this change?

expected <foo[bar]> but was: <foo[]>

**Comment by gnodet** [comment]
Thx ! Not running a full build is _always_ a bad idea ;-)
