### ISSUE TITLE
Suppress warning on dumb terminals

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#291]
CommandBox is used by a lot of CF devs in CI environments like Travis-CI, Jenkins, and Gitlab.  Since switching to JLine 3, I've gotten a large number of reports about this "Error":

```
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
```

Obviously, it's not an error but a warning but it seems to really confuse people and in most cases there's not a need to tell the users that since they're simply running JLine in a CI server build.  Can Jline safely suppress this message so it no longer shows up?

**Comment by gnodet** [comment]
There are already several ways to remove this warning: `TerminalBuilder.builder().`**`dumb(true)`**`.xxx` or setting the `org.jline.terminal.dumb` system property to `true`.

I'd rather keep the warning, so that newbies are aware of abnormal conditions leading to not being able to setup the `Terminal` correctly.

**Comment by bdw429s** [comment]
@gnodet Are you saying that will simply disable the warning message or will that cause JLine to always use a dumb terminal?  I obviously don't want to _always_ use a dumb terminal, and I don't know of any way that my console app could possibly detect the terminal in which it was being run (nor does it seem like the responsibility of my app to do).

**Comment by gnodet** [comment]
It won't force the use of a dumb terminal.  The property's purpose is to _disallow_ (`false`)/_warn_ (`null`)/_allow_ (`true`) defaulting to a dumb terminal when a supported terminal can not be correctly created.

**Comment by bdw429s** [comment]
Ok, that sounds perfect then.  I'll plug it in and give it a test.  Thanks for letting me know about that feature.
