### ISSUE TITLE
Persistent input line with asynchronous output

### ISSUE THREAD

**Issue by Minecrell** [jline/jline3#292]
I'm trying to implement a persistent input line while having asynchronous (logging) output with a `LineReader`. To do this, I call some widgets as suggested in https://github.com/jline/jline3/issues/75#issuecomment-268496777:

```java
reader.callWidget(LineReader.CLEAR);
terminal.writer().println(line);
reader.callWidget(LineReader.REDRAW_LINE);
reader.callWidget(LineReader.REDISPLAY);
```

This works fine, but since the output is asynchronous, there is a potential race condition:

```
OutputThread: works
InputThread:  readLine() returns with a new input line
OutputThread: callWidget() results in
    java.lang.IllegalStateException: Widgets can only be called during a `readLine` call
        at org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:671)
InputThread:  readLine() is called to start reading another line
OutputThread: works, but may result into duplicate input prompts (e.g. > > ...)
OutputThread: works
```

Here is a very simple example that makes this reproducible: https://gist.github.com/Minecrell/374c4d3a0239a8c8a9c50849acf0b3f8

It reads lines from input, and schedules them to be printed a few times asynchronously directly after they were read. In reality, this situation would only occur occasionally if there is new output at the same time.
With this example, I always get a duplicate input prompt (`> > ` instead of `> `), and when typing quickly enough it will also run into the `IllegalStateException`.

All this brings me to the conclusion that I need some sort of locking mechanism to prevent the two threads from interfering with each other. However, I've been unable to think of any solution that doesn't require changes in JLine.

One way I was thinking about would be to synchronize parts of `LineReader.readLine` (e.g. everything except actual input I/O) to prevent the input/output thread from modifying the input line at the same time.
E.g. https://github.com/Minecrell/jline3/commit/c4c0560a1472d2d10c39daf8cc03f9f2285b8ebb together with this change in the output thread ([full code](https://gist.github.com/Minecrell/c97a42a7c2b0f114d4d15c815054fe83#file-jlinetest-java-L36-L46)):

```java
synchronized (reader) {
    if (reader.isReading()) {
        reader.callWidget(LineReader.CLEAR);
        terminal.writer().println(line);
        reader.callWidget(LineReader.REDRAW_LINE);
        reader.callWidget(LineReader.REDISPLAY);
    } else {
        // No need to redraw prompt
        terminal.writer().println(line);
    }
}
```

These changes fix both issues I mentioned above. There is always only a single input prompt (`> `) and I wasn't able to observe the `IllegalStateException` anymore.

I'm not sure if this should be default behavior or if some kind of optional, external lock would be more appropriate here. Or maybe you have any other suggestions to avoid the problems mentioned above?

**Comment by Minecrell** [comment]
@gnodet This looks great, much easier - thanks! Right now there seems to be a deadlock, though:

```
Found one Java-level deadlock:
=============================
"pool-1-thread-1":
  waiting to lock monitor 0x00007f7864006528 (object 0x000000076d3697f8, a java.lang.Object),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007f7864004f28 (object 0x000000076d30a108, a org.jline.reader.impl.LineReaderImpl),
  which is held by "pool-1-thread-1"

Java stack information for the threads listed above:
===================================================
"pool-1-thread-1":
        at org.jline.reader.impl.LineReaderImpl.printlnAbove(LineReaderImpl.java:644)
        - waiting to lock <0x000000076d3697f8> (a java.lang.Object)
        - locked <0x000000076d30a108> (a org.jline.reader.impl.LineReaderImpl)
        at JLineTest.processCommand(JLineTest.java:36)
        at JLineTest.lambda$main$0(JLineTest.java:25)
        at JLineTest$$Lambda$176/1566502717.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
"main":
        at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3491)
        - waiting to lock <0x000000076d30a108> (a org.jline.reader.impl.LineReaderImpl)
        at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3486)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:548)
        - locked <0x000000076d3697f8> (a java.lang.Object)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404)
        at JLineTest.main(JLineTest.java:24)
```

I think this is because both `redisplay` and `printlnAbove` are `synchronized` methods (i.e. lock the `LineReader` object) and both want the `displayLock` too. Do we really need two separate locks?

**Comment by gnodet** [comment]
We definitely don't need 2 different locks. I've kept only the displayLock.

**Comment by Minecrell** [comment]
That fixed it! It seems to work fine mostly but I'm still seeing occasional duplicate prompts (`e.g. > > `), although much less frequently. I'm not able to reproduce them with my original changes.

Not yet sure what's causing this, especially because your solution is similar to mine except for having a separate `displayLock` and the additional methods. I'll try to figure out what's causing them and will comment here when I figure it out.

**Comment by Minecrell** [comment]
It seems like the reason is that `reading` is set very early in `readLine`. This causes `printlnAbove` to eventually redisplay the prompt before `LineReaderImpl.prompt` is actually initialized and before the initial prompt was drawn. In other words:

```
InputThread: starts calling readLine(), reading = true
OutputThread: take displayLock, reading = true, call redisplay()
InputThread: prompt = "> "; take displayLock, draw initial prompt
```

To avoid this, `reading` should not be set until the prompt and everything else is initialized.

For example, it doesn't happen if `reading` is set later after everything is initialized: https://github.com/Minecrell/jline3/commit/23928a126842d0369a3e3ff97f09045085dc5b95.

With this change, we no longer check early if something else is already `reading`, though. I think we may need two separate flags here, something like `startedReading` which is set early and a `reading` which is set after everything is initialized.

My suggested fix would be https://github.com/Minecrell/jline3/commit/c0df2d059fb29d3eaa7da55a593f106bb4ee83ae, which splits `reading` and `startedReading`. `reading` should be only read and written with the lock held to avoid state changes (e.g. `cleanup()`) while we're printing a line.

For simplicity I've removed the `displayLock` so I could simply annotate the needed methods as `synchronized` without inserting a `synchronized` block all the time. It would also work the same way with the external `displayLock`, I just can't think of any advantage for having it separate.

**Comment by Minecrell** [comment]
There is a stray `displayLock` in the `redisplay()` method of your last commit, probably from some changes you made before. Can either change the method to `synchronized` again or even remove `synchronized` entirely from `redisplay()`. I don't think it's ever called without the the lock already held.

Here is one more fix for a NPE I was just running into `LineReader.println()` calls `redrawLine()`  which doesn't work if `readLine` wasn't called yet: https://github.com/Minecrell/jline3/commit/64d6d2c37d14345ef3b655f8f1111c24c14757ea

Otherwise everything is working perfectly now! :tada: Thanks again :)

**Comment by Minecrell** [comment]
It works perfectly now :+1: 

One last request: In my real application, the logging framework already adds `\n` at the end of each message. To use `printlnAbove`, I'd always need to make a copy of the string, remove `\n` just to have JLine add it back. Can we add another `printAbove` method that doesn't add the newline automatically?

I've added it in https://github.com/Minecrell/jline3/commit/901cd0b6e7a24e7a8ef154c3e5d9ca5a7bd906fa, feel free to squash it with your changes.

**Comment by gnodet** [comment]
I'm worried about the behavior if you call `printAbove` with a string not ending with a `\n`.  Could you give it a try ?

**Comment by gnodet** [comment]
I've kept only the `printAbove` methods, but added a check to not print a newline if one is already included in the argument value.

**Comment by Minecrell** [comment]
@gnodet Yep, good point about the behavior of `printAbove` when using it without `\n`. When I saw your comment earlier today I was about to suggest simply excluding `\n` if it already exists but seems like you've already implemented that! :)

I've tested your changes in my test application and one of the real applications and it seems to work fine! 
Feel free to merge it :)

**Comment by Minecrell** [comment]
Hey @gnodet, sorry to bump this. Can we merge your commit? I'd like to start using the snapshot version to fix this race condition until the next version is released.

**Comment by gnodet** [comment]
Sure, I'll first release 3.8.1, then merge it and release 3.9.0.

**Comment by tpoliaw** [comment]
> then merge it and release 3.9.0.

When do you plan to release 3.9.0? I'd like to start using 3.8.1 to get the fix for #290 but if 3.9 is going to be the next few days, I'll wait for that. We use a workaround for the same problem as this issue and it'd be good to include this as well.

**Comment by Minecrell** [comment]
Using the snapshot versions didn't worked out liked I wanted them to (I wanted to pin a specific snapshot version - e.g. `3.9.0-20180716.160016-1` - but that doesn't work well if you then have transitive dependencies to `jline-terminal` etc..)

However, I did some more tests on other platforms and it seems to work really well, so I agree with @tpoliaw that a having a new release within the next days would be great. :)

**Comment by gnodet** [comment]
JLine 3.8.2 and 3.9.0 are being released.
