### ISSUE TITLE
3.8.0 regression with color support on ConEMU

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#294]
Upgrading from JLine 3.7.0 to 3.8.0 has a regression which now causes ConEMU to report as only supporting 8 colors instead of 256 colors.  In both cases, `org.jline.terminal.impl.jna.win.JnaWinSysTerminal` is the terminal class in use.

Jline 3.7.0 running the `system-colors` command in CommandBox 4.1:
![image](https://user-images.githubusercontent.com/584009/42475669-e891f956-8390-11e8-9555-e4d542e47ad7.png)

Jline 3.8.0 running the `system-colors` command in CommandBox 4.1:
![image](https://user-images.githubusercontent.com/584009/42475637-cfa8035e-8390-11e8-81b0-f1b77ac9745a.png)

**Comment by gnodet** [comment]
Two questions:
 * is the behavior specific to Windows 10 ?
 * what is the type set on the terminal `terminal.getType()` ?

**Comment by gnodet** [comment]
Ok, I think `null` is the problem here, I'll investigate.

**Comment by gnodet** [comment]
Could you try the following patch ?
   https://github.com/jline/jline3/tree/issue-294

**Comment by bdw429s** [comment]
@gnodet I built the code on that branch and it seems to have fixed the regression.  256 colors are back in ConEMU.  Thanks!

Any idea what version this will release in?  I was hoping to include 3.8.0 in CommandBox due to some other fixes you had put in there for me but I'll need to wait until this fix going into a stable version.

**Comment by gnodet** [comment]
JLine 3.8.2 should be available shortly in central.

**Comment by bdw429s** [comment]
Thanks again @gnodet !
