### ISSUE TITLE
readLine() ignores any text in the buffer when OEF is reached

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#298]
CommandBox allows you to pipe a file of commands into it and readLine() will read the lines one at a time off the standard input just as though a human had typed them.

```
box.exe < commands.txt
```

If there's no trailing line break at the end of the file, then the last command is read in but the OEF fires before the last line is handed back for execution.  I get that this makes some deal of sense since I can press Ctrl-D while typing at the shell to exit immediately, but in the case of reading an actual text file input, I'd like to be able to execute that last line even if there's no line break at the end.  

The `org.jline.reader.UserInterruptException` exception provides `getPartialLine()` to see if the user typed something.  Is the correct fix to add the partial line to the `org.jline.reader.EndOfFileException` as well?

**Comment by gnodet** [comment]
You're right.  When the terminal is not an interactive terminal (with a human being), it does not make sense to try to read Ctrl-D in advance.  I'll try to investigate.

**Comment by gnodet** [comment]
On unix systems, the `TerminalBuilder` creates a `DumbTerminal` when the input is not a real terminal, such as a file redirect.  I think the same should be true on windows too. The `DumbTerminal` does not read the stream in advance, so the problem does not appear on unix.
In theory, the input and output should be better decorrelated so that the output could be cleanly usable even if there's no input (or the opposite), but that's really a corner case imho.

**Comment by bdw429s** [comment]
Just a note on the dumb terminal idea-- just because I've piped input to the process doesn't mean that I'm not running it in a terminal capable of ANSI formatting, etc.  In fact, in my cases I likely would be which I reported as another issue here; https://github.com/jline/jline3/issues/299

**Comment by gnodet** [comment]
Yes, this is the same issue.  But not a simple bug to fix, it may require some important changes in order to split the input from the output.

**Comment by bdw429s** [comment]
@gnodet Any progress on this?  What if, when the OEF is reached, if there is input that's been read into the buffer, the line is read (returned from `readLine()` for processing) and then any subsequent call of `readLine()` will fire OEF now that the input is truly empty.

**Comment by ghandhikus** [comment]
This really needs to get fixed, with IntelliJ on windows even with a simplest example the lib just throws EOF
```shell
org.jline.reader.EndOfFileException
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:639)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
	at main.Main.main(Main.java:26) // < String line = reader.readLine("prompt > ");
```
```java
Terminal terminal = TerminalBuilder.builder().build();
DefaultParser parser = new DefaultParser();
LineReader reader = LineReaderBuilder.builder()
        .terminal(terminal)
        .parser(parser)
        .build();
while (true) {
    try {
        String line = reader.readLine("prompt > ");
        System.out.println(line);
    } catch (UserInterruptException e) {
        // Ignore
    } catch (EndOfFileException e) {
        e.printStackTrace();
        return;
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

**Comment by bdw429s** [comment]
@mattirn I see this ticket has been closed.  Can you please elaborate on what change you made or if I need to modify any code on my end to take advantage of it?

**Comment by mattirn** [comment]
You have to catch `EndOfFileException`, get exception property partialLine, execute it and exit from REPL loop:
https://github.com/jline/jline3/blob/fd1177525be0f1b071345848f2433d15d0cf05c6/demo/src/main/java/org/jline/demo/Repl.java#L341-L351

**Comment by bdw429s** [comment]
@mattirn Thanks, I'll make these changes in my console app.

**Comment by bdw429s** [comment]
@mattirn @gnodet Oops, it seems something has gotten broken since I originally put this ticket in.  This simple example of piping commands to a text file into my console app no longer works:
```
box.exe < commands.txt
```
On Windows, using the JansiWinSysTerminal, I get the following error that appears in the console:

```
Dec 11, 2020 2:24:28 PM org.jline.utils.Log logr
WARNING: Error in WindowsStreamPump
java.io.IOException: ReadConsoleInputW failed
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:816)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:134)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
        at java.base/java.lang.Thread.run(Unknown Source)
```

The `EndOfFileException` is thrown right away on the first `readLine()` call (even if I have more than one line of text in the file) and the `getPartialLine()` method returns an empty string.

I am not able to confirm this ticket is fixed.

**Comment by bdw429s** [comment]
I attempted another approach to this, with not piping input to the process, but instead typing some text into the buffer and then pressing Ctrl-D.  Interestingly enough, when I press Ctrl-D, instead of throwing the `EndOfFileException` it behaves as though I've pressed Tab and displays completion results.  

![image](https://user-images.githubusercontent.com/584009/101954531-e0bad680-3bc1-11eb-90cd-40cac344f161.png)


I'm not sure if this is an inteded behavior or not.  I can confirm that when I press Ctrl-D without any text in the buffer, it throws the `EndOfFileException` and I exit my shell.

**Comment by mattirn** [comment]
Also Ubuntu/xterm will complete when you press Ctrl-D if the buffer is not empty.

The ticket I have tested only using Windows/CMD and it does work also with JLine version 3.18.0.

**Comment by gnodet** [comment]
<Ctrl-D> is mapped to the `DELETE_CHAR_OR_LIST` widget (see https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L6014) which is [mapped](https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L3669) to the [`deleteCharOrList`](https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L4367-L4373) method.
The <Ctrl-D> from the terminal is usually mapped to the `VEOF` control char on the terminal, and that's what causes the `EndOfFileException`, see https://github.com/jline/jline3/blob/29d72f817a6742c7a83e84812aadca300f57d9fb/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L653-L655.

**Comment by bdw429s** [comment]
> Also Ubuntu/xterm zsh will complete when you press Ctrl-D if the buffer is not empty.

Interesting, that doesn't make any sense to me, but no matter.  I've admittedly never tried it before so let's just ignore that behavior and focus on the error above that's preventing me from using the changes in this ticket.

> The ticket I have tested only using Windows/CMD and it does work also with JLine version 3.18.0.

Ok, so "works on your machine" but let's figure out why it's not working for me.  I've pasted the exception I received above.  Can you comment on what that exception might mean or why I'd be getting it?  

```
Dec 11, 2020 2:24:28 PM org.jline.utils.Log logr
WARNING: Error in WindowsStreamPump
java.io.IOException: ReadConsoleInputW failed
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:816)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:134)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by gnodet** [comment]
@bdw429s hard to tell the reason as the underlying problem is hidden.  I've raised an issue in jansi to report the real problem. That should help understanding the issue.

**Comment by bdw429s** [comment]
@mattirn Thanks for spending some time on this.  Is the commit above meant to be a fix, or simply some additional debugging code?  May I recommend adding a comment to tickets when adding commits or closing them?  I see a lot of mystery commits on tickets in this repo where I'm not sure what the current status of the ticket really is or what has been done against it.  :)

**Comment by mattirn** [comment]
Fixed and tested with ConEmu with Jansi and JNA.

**Comment by bdw429s** [comment]
@mattirn Excellent, and thanks for the update.  I'll give this a test soon on my end.
