### ISSUE TITLE
Issues detected while building with Maven in Win 10

### ISSUE THREAD

**Issue by hyee** [jline/jline3#3]
2 errors detected, and finally hanging on "org.jline.reader.impl.MultiByteCharTest"
Platform is Win10 x64, below is the console output:

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for jline:jline:jar:3.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: junit:junit:jar -> duplicate declaration of version 4.12 @ line 151, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-site-plugin is missing. @ line 373, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JLine 3.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ jline ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jline ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] skip non existing resourceDirectory D:\Green\Github\jline3\src\main\filtered-resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jline ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 95 source files to D:\Green\Github\jline3\target\classes
[INFO]
[INFO] >>> maven-bundle-plugin:2.5.4:manifest (default) > process-classes @ jline >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ jline ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jline ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] skip non existing resourceDirectory D:\Green\Github\jline3\src\main\filtered-resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jline ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 95 source files to D:\Green\Github\jline3\target\classes
[INFO]
[INFO] <<< maven-bundle-plugin:2.5.4:manifest (default) < process-classes @ jline <<<
[INFO]
[INFO] --- maven-bundle-plugin:2.5.4:manifest (default) @ jline ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jline ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] skip non existing resourceDirectory D:\Green\Github\jline3\src\test\filtered-resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jline ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ jline ---
[INFO] Surefire report directory: D:\Green\Github\jline3\target\surefire-reports

---
##  T E S T S

Running org.jline.builtins.OptionsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec - in org.jline.builtins.OptionsTest
Running org.jline.keymap.BindingReaderTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec <<< FAILURE! - in org.jline.keymap.BindingReaderTest
testBindingReaderUnicode(org.jline.keymap.BindingReaderTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<Reference[insert]> but was:<Reference[foo]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.jline.keymap.BindingReaderTest.testBindingReaderUnicode(BindingReaderTest.java:69)

Running org.jline.keymap.KeyMapTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec - in org.jline.keymap.KeyMapTest
Running org.jline.reader.completer.ArgumentCompleterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.06 sec - in org.jline.reader.completer.ArgumentCompleterTest
Running org.jline.reader.completer.DefaultParserTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.jline.reader.completer.DefaultParserTest
Running org.jline.reader.completer.NullCompleterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.jline.reader.completer.NullCompleterTest
Running org.jline.reader.completer.StringsCompleterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in org.jline.reader.completer.StringsCompleterTest
Running org.jline.reader.history.FileHistoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.jline.reader.history.FileHistoryTest
Running org.jline.reader.history.HistoryTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.26 sec - in org.jline.reader.history.HistoryTest
Running org.jline.reader.history.MemoryHistoryTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.jline.reader.history.MemoryHistoryTest
Running org.jline.reader.impl.BufferTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.jline.reader.impl.BufferTest
Running org.jline.reader.impl.CompletionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in org.jline.reader.impl.CompletionTest
Running org.jline.reader.impl.DigitArgumentTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.059 sec - in org.jline.reader.impl.DigitArgumentTest
Running org.jline.reader.impl.EditLineTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec - in org.jline.reader.impl.EditLineTest
Running org.jline.reader.impl.HistorySearchTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in org.jline.reader.impl.HistorySearchTest
Running org.jline.reader.impl.KillRingTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec - in org.jline.reader.impl.KillRingTest
Running org.jline.reader.impl.MultiByteCharTest

**Comment by seanbright** [comment]
Some of the tests rely on the platform's default character set. On Windows that is [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252).
