### ISSUE TITLE
Can't turn off echo in PowerShell

### ISSUE THREAD

**Issue by altavir** [jline/jline3#30]
All echo flags are `false` and sill it prints echo line.

**UPDATE**
The same problem with `cmd`. In both cases I am using ConEmu, but it should not matter.

**UPDATE 2**
Seem to be specific to `ExternalTerminal`. Works fine in jna and jansi.

**Comment by gnodet** [comment]
`ExternalTerminal` can only provide a very basic emulation of a real terminal and is only used when using a non system terminal on Windows.
This terminal should only be used for virtual terminals (such as when building an ssh server on windows) with custom input/output streams, but not for the real system terminal.

**Comment by altavir** [comment]
Does `ConEmu` count as non system terminal? In any case, I believe that turning echo on or off is quite basic. I believe `ExternalTerminal` should give warnings in case one tries to use features it does not implement.

**Comment by gnodet** [comment]
The system terminal can be obtained using `TerminalBuilder.builder().build()` or `TerminalBuilder.terminal()`.  This should not lead to an instance of `ExternalTerminal` being used.
Anyway, I agree `ExternalTerminal` should output some log for unsupported features.

**Comment by altavir** [comment]
It throws `ClassNotFoundxException` if neither `jna` nor `jansi` are explicitly added to dependencies. This error is obvious if one looks through the code, but does not make any sense to inexperienced user.

**Comment by gnodet** [comment]
Actually, the `ExternalTerminal` supports `echo`.  If you still have an echo when typing after having disabled the echo on the `ExternalTerminal`, it means that the streams given to it are not really raw streams.
Remember by default, the System.in stream has some line editing built-in the OS: it will usually be empty until the user hit `<enter>` at which point it will be filled by the string read.  This is also why you reported a problem with the thread not terminating until you hit the enter key. 
The `ExternalTerminal` has been designed to be used with remote connections such as ssh or telnet.

**Comment by altavir** [comment]
I was using `System.in` and `System.out`. But I guess that the best solution is not to use `ExternalTerminal` if possible.

**Comment by altavir** [comment]
`DumbTerminal` works fine with IDEA, but still there is no luck turning off echo.

**Comment by gnodet** [comment]
Yes, but this can't be done.  When using the IDEA console, the characters are echoed even before they reach the JVM I think.  This would require a much deeper integration with the IDEA console, which is not a real terminal.

IDEA does support some terminals, when executing shell commands, but I don't think it's possible to use it when running a program.

If you find anything, I'd be happy to make any modification ...

**Comment by gnodet** [comment]
I've raised #44 to capture the issue and I'm closing this issue.
