### ISSUE TITLE
Support/convert jline2 history file to jline3

### ISSUE THREAD

**Issue by snuyanzin** [jline/jline3#300]
Hello
I consider a way to move from jline2 to jline3 however I faced with the issue that if jline2 history file exists jline3 asks to remove it. 
Is there a way to keep history, do some transformation while or before the first run or whatever?

**Comment by gnodet** [comment]
You can disable history timestamps on  the `LineReader`:
```
   reader.unsetOpt(Option.HISTORY_TIMESTAMPED);
```

**Comment by bdw429s** [comment]
@snuyanzin I've asked before about JLine automatically converting old history files but that idea was not accepted.  Instead, here was my workaround to manually convert old history files ot the new format.  Note, the differences are more than just the timestamps.  The new format has different escape syntax that also need dealt with.

This code is in CFML but I'm sure you could adapt it
https://github.com/Ortus-Solutions/commandbox/blob/development/src/cfml/system/util/ReaderFactory.cfc#L114-L146

**Comment by snuyanzin** [comment]
@gnodet , @bdw429s thank you for your responses
I guess that is what I need
