### ISSUE TITLE
reader.clearScreen() on ConEMU scrolls to top, not bottom, breaks formatting

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#301]
256 colors and other ANSI formatting only work on the bottom page of ConEMU.  Jline starts at the bottom  of the window when I first run CommandBox and it used to stay there at the bottom when clearing the screen.  One of the recent new versions of Jline now scrolls me to the top of the window when I call `reader.clearScreen();` which means 256 colors and other formatting stops working unless I enter enough lights to scroll all the way back down to the bottom.

I'm not sure exactly when this regression happened but I just noticed it somewhat recently and the last update I did was from `3.7.0` to `3.8.2`.

**Comment by gnodet** [comment]
Could you check if the following patch would fix the problem maybe ?
```
diff --git a/terminal/src/main/resources/org/jline/utils/windows-256color.caps b/terminal/src/main/resources/org/jline/utils/windows-256color.caps
index c42704c..1b7b7a5 100644
--- a/terminal/src/main/resources/org/jline/utils/windows-256color.caps
+++ b/terminal/src/main/resources/org/jline/utils/windows-256color.caps
@@ -1,7 +1,7 @@
 windows-256color|windows with 256 colors terminal compatibility,
        am, mc5i, mir, msgr,
        colors#256, cols#80, it#8, lines#24, ncv#3, pairs#64,
-       bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, clear=\E[H\E[J,
+       bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, clear=\E[H\E[J\E[9999E,
        cr=^M, cub=\E[%p1%dD, cub1=\E[D, cud=\E[%p1%dB, cud1=\E[B,
        cuf=\E[%p1%dC, cuf1=\E[C, cup=\E[%i%p1%d;%p2%dH,
        cuu=\E[%p1%dA, cuu1=\E[A,
```

**Comment by bdw429s** [comment]
@gnodet Thx for looking into this.  Compiling that change locally does seem to fix the issue.  When I clear screen in ConEMU it stays scrolled to the bottom of the window which retains proper ANSI formatting.
