### ISSUE TITLE
Terminal width/height issue in Windows console

### ISSUE THREAD

**Issue by hyee** [jline/jline3#303]
My console window's screen buffer width/height is always much large than the screen width/height. 
For example,  the console's screen size is 182x60, while the screen buffer size is 1000x9999. 
The reason of why use such configuration is that I'm using JLine as a SQL console window, it's very common for a `select` statement to print wider and longer lines than screen visible area, and line wrap is not advised otherwise the output will be messed.

In JLine 3.9, `Terminal.getSize()` returns the buffer width and height in `Windows`, as a result, the `less`,`top` and printing completer candidates do not work well, since there are horizontal scrolling and other unexpected behaviors. 

In my case, I mainly expect JLine to use buffer width to impact the `readLine` behaviour in case of inputing a long line, and in other cases screen width/height seems to be a better choice.
I was using JLine 3.5 previously, did I miss something to accomplish the purpose in the new version? 
 
Acknowledged that many people only use the POSIX-style terminal that doesn't have the horizontal scrollbar, but hope this feature can be supported,  Thanks.

**Comment by gnodet** [comment]
The regression is caused by #136 so that clearly does not solve the issue.
JLine should already support at least vertical scroll bars correctly.

Horizontal scrollbars are, afaik, a windows specific issue, though there are other terminals which use it as well such as [Terminator](https://github.com/software-jessies-org/jessies/wiki/Terminator).
This definitely need some work.

**Comment by gnodet** [comment]
Maybe that's the way to go, but this would require checking all calls to verify which is should actually be used.  I was hoping for a quick fix, but not sure there's one as we may switch from a regression to another endlessly....

**Comment by gnodet** [comment]
It should be fixed hopefully. Could you verify it works for you ?

**Comment by bdw429s** [comment]
Thanks for the fix @gnodet , I'm traveling ATM but will test soon.
