### ISSUE TITLE
key_enter in BindingReader not matching

### ISSUE THREAD

**Issue by SevereOverfl0w** [jline/jline3#306]
I'm attempting to use the BindingReader to subscribe to key presses, my code looks roughly like so:

```
br = new BindingReader(terminal.reader());
km = new KeyMap();

km.bind("finish", KeyMap.key(terminal, InfoCmp.Capability.key_enter));

String x = br.readBinding(km);
```

But this never seems to be triggered when I hit "enter" on the keyboard. Am I doing something stupid?

I've also tried with `"\n"`. I'm using jline 3.9.0 on Linux.

`br.readCharacter()` has no problem in giving me `13` as the return when I hit enter, so I suspect this to be a problem of matching.

**Comment by SevereOverfl0w** [comment]
Binding "\r" seems to have done it, but I can't seem to bind to other esc-based keys, such as `key_up`.

**Comment by gnodet** [comment]
For `key_up` and other similar keys, you need to first write the `keypad_xmit` capability in order to switch the terminal into the correct mode.
See https://www.mkssoftware.com/docs/man5/terminfo.5.asp#Keypad_Handling

**Comment by SevereOverfl0w** [comment]
That's exactly it, copying the example from Nano.java has solved my problem, thank you very much!
