### ISSUE TITLE
weird use of PROP_SUPPORT_PARSEDLINE in LineReaderBuilder

### ISSUE THREAD

**Issue by PerBothner** [jline/jline3#309]
This expression in LineReaderBuilder.java doesn't make sense to me, as it will always be false:

    Boolean.parseBoolean(LineReader.PROP_SUPPORT_PARSEDLINE)

Presumably it should be something like:

    variables.get(LineReader.PROP_SUPPORT_PARSEDLINE)

perhaps wrapped with `ReaderUtils.getBoolean` - but that requires a `LineReader`, which we don't have yet. Maybe move the test to `build`?

**Comment by PerBothner** [comment]
No.  The field `PROP_SUPPORT_PARSEDLINE` in the `LineReader` interface is a constant field, and cannot be set. Thus the expression is `Boolean.parseBoolean("org.jline.reader.support.parsedline")` which is *always* `false`.

**Comment by gnodet** [comment]
This is now fixed. It was meant to use `Boolean.getBoolean` instead which is retrieving the system property and parsing it.

**Comment by PerBothner** [comment]
Makes sense.  Thanks.
