### ISSUE TITLE
Terminal does not close immediately on Windows

### ISSUE THREAD

**Issue by altavir** [jline/jline3#31]
When I invoke `terminal.close()` nothing happens. The jline thread terminates only on next line feed.

**UPDATE**
Specific to `ExternalTerminal`

**Comment by gnodet** [comment]
Unfortunately, a call to `InputStream.read()` can not easily be interrupted. Maybe we could make the pump thread a daemon thread.

**Comment by gnodet** [comment]
Is that fixed with #107 ?

**Comment by gnodet** [comment]
Closing this issue, I believe this is fixed with #107.  Please reopen if needed.
