### ISSUE TITLE
arrow keys broken because of Application Cursor Keys mode

### ISSUE THREAD

**Issue by PerBothner** [jline/jline3#310]
I recently re-built JLine - but moving the cursor using the arrow keys is now broken.

JLine sets the terminal in Application Cursor Keys mode (using `\e[?1h`).  This has the effect that an xterm-compatible terminal reports arrow keys using the prefix `\e0` rather than `\e[`.  (I.e. Left is `\e0D` rather than `\e[D`.) The former is not recognized by jline.  The fix is to either recognize these sequences (preferred) or to not set the terminal in Application Cursor Keys mode (or both).

**Comment by gnodet** [comment]
JLine uses the terminal capabilities from `infocmp`. Are you sure your terminal type (from `$TERM`) is the correct one ?  What exact terminal are you using ?

**Comment by PerBothner** [comment]
I can't reproduce the problem right now. Which is somewhat mysterious. I'll do a little more experimentation and then close this. (By "an xterm-compatible terminal" I meant xterm itself, as well s gnome-terminal and DomTerm.)
