### ISSUE TITLE
Multiline editing breaks if input has more lines than terminal

### ISSUE THREAD

**Issue by electrum** [jline/jline3#311]

**Comment by electrum** [comment]
I've been looking into how to fix this but I'm stuck on the question of how it should work.

It looks like `LineReaderImpl.redisplay()` already has some code to handle this scenario. I tested it as follows:

* Make `MIN_ROWS` larger and rebuild
* Run the demo
* Paste in a large string (a chunk of `/etc/passwd') surrounded by `'` and hit enter
* Resize terminal to have fewer lines than `MIN_ROWS`
* Press up to get to the history entry and see how it behaves. Pressing up/down while in the entry will scroll between the lines. Eventually it gets messed up.

One thought is that we could change the code to activate anytime the number of lines to display is too large for the terminal.

<img width="682" alt="screen shot 2018-09-14 at 10 42 06 am" src="https://user-images.githubusercontent.com/9230/45566249-f1c1e500-b80a-11e8-855d-93f4f0d3f4bd.png">
<img width="682" alt="screen shot 2018-09-14 at 10 42 14 am" src="https://user-images.githubusercontent.com/9230/45566250-f1c1e500-b80a-11e8-9c00-b17f46cfc76b.png">
<img width="682" alt="screen shot 2018-09-14 at 10 42 33 am" src="https://user-images.githubusercontent.com/9230/45566251-f1c1e500-b80a-11e8-94b6-63c67dac2bd5.png">

**Comment by electrum** [comment]
My motivation to fix this is to upgrade the Presto CLI to use JLine 3. People often paste large SQL queries that have hundreds or thousands of lines. Multiline editing is an awesome feature, but we can't regress on this common scenario that JLine 2 handles without problems.

**Comment by electrum** [comment]
@gnodet Do you have any thoughts on how this should work?

**Comment by gnodet** [comment]
The display needs to be fixed so that if the number of lines is greater than the height of the terminal, some continuation markers have to be displayed at the top and/or bottom and trim the number of lines.  This has to be done in the LineReaderImpl because it will certainly need special treatment for up/down cursor movement.
