### ISSUE TITLE
jLine failed with following exception org.jline.reader.EndOfFileException: null

### ISSUE THREAD

**Issue by TheAmyChan98** [jline/jline3#312]
I get an error in this project

Version: 3.8.0

```2018-09-20 10:06:31.953 [GoMint CLI reader] ERROR io.gomint.server.GoMintServer - jLine failed with following exception
org.jline.reader.EndOfFileException: null
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:554) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:402) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.GoMintServer.lambda$startAfterRegistryInit$2(GoMintServer.java:304) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

Project: https://github.com/GoMint/GoMint/blob/master/gomint-server/src/main/java/io/gomint/server/GoMintServer.java#L304

**Comment by gnodet** [comment]
Yes, this is a behavior change in 3.8.0 to behave according to the javadoc.
  https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/LineReader.java#L463-L474

You just need to catch this exception along with the `UserInterruptException`.

**Comment by geNAZt** [comment]
How is the EOF detected? The user has a Windows 10 1803 cmd terminal open running the Server inside. When i do the same in the same Version of the terminal i don't get EOF Exceptions.

**Comment by gnodet** [comment]
The exception is thrown when the terminal input reader `read` method returns `-1`.  On windows, this should only happen when the `close` method is called on the input reader.
Another explanation is that the terminal is not correctly recognized.  Could you check the implementation class of the `Terminal` created by the `TerminalBuilder` ?
Also, does the exception happen immediately, or after some time, when doing something... ?

**Comment by geNAZt** [comment]
The implementation class is org.jline.terminal.impl.jna.win.JnaWinSysTerminal. Mine is the same as the broken one. The terminal is also not closed down and the Software never closes it

**Comment by geNAZt** [comment]
We found the issue. Its due to a 32bit JVM installed on a 64bit OS. Installing a 64bit JVM fixed this issue.

**Comment by gnodet** [comment]
Glad to know !
