### ISSUE TITLE
Completion not working under Windows

### ISSUE THREAD

**Issue by markbosshard** [jline/jline3#316]
Under Windows we are receiving the error

> WARNING: unable to create a system terminal, creating dumb terminal (enable debug logging for more information)

and autocompletion is not working. will this be fixed?

To see how we set up the example project, check also our stackoverflow question:
https://stackoverflow.com/questions/52851232/jline3-issues-with-windows-terminal

**Comment by gnodet** [comment]
There's not much document, I agree, but in this the existing doc contains the answer.
See https://github.com/jline/jline3#jansi-vs-jna

**Comment by markbosshard** [comment]
Genius! thank you so much for answering. For completeness I have added the info on stackoverflow:
https://stackoverflow.com/questions/52851232/jline3-issues-with-windows-terminal
