### ISSUE TITLE
Escaped backslashes on completion seems messed up

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#317]
I noticed recently that backslashes on completion candidates are getting escaped when inserted.  I guess I don't mind that since they usually need escaped for folder paths for instance, but the line is getting messed up and spaces are being deleted.  

If I start with this at the terminal
```bash
cd C:\In
```
and I hit tab, the completor is sent three candidates which are correctly displayed.  So far, so good.
```bash
> cd C:\In
Directories
C:\Intel/             C:\Inetpub/           C:\InstallAnywhere/
```
Now, I hit `<tab>` to select the first option.  The `C:\Intel/` option is highlighted, but the input line changes to this:
```bash
cdC:\\Intel/
```
Note, the space between `cd` and the path is now gone!  If I press `<enter>` to select that candidate, the incorrect string remains in the buffer.   I used to force all slashes to forward slashes, but it caused issues with partial matches not showing up so I changed my completor to leave existing backslashes in the path which then caused me to notice this behavior.

Also note, I have `DISABLE_EVENT_EXPANSION` set on the shell and I don't use JLine's backslash escaped stuff, but I have implemented my own escapes into CommandBox.  So while I'm sort of ok with JLine auto-escaping the slashes, I'm not sure if JLine will follow the same rules that I've implemented.  Given the option, I'd probably rather turn off JLine's auto-escaping and do my own.

**Comment by bdw429s** [comment]
I have noticed that if there is only one matching candidate, the buffer is populated correctly, but now this has revealed a second issue with the automatic escaping.  Let's consider this exact match scenario:

I type the following and hit `<tab>` which matches an exact directory name
```bash
cd C:\sandbox\testboxtest
```

And now the escaping stuff kicks in and my buffer is changed to this:
```bash
cd C:\\sandbox\\testboxtest/
```
But now when I hit `<tab>` again, my custom completor is adding candidates such as `C:\sandbox\testboxtest/views/`, but JLine ignores them because the candidates all have single slashes in them so they don't look like partial matches.  If Jline is going to be automatically escaping my backslashes, then it needs to do the same thing when it looks for partial matches or this won't work.

**Comment by mattirn** [comment]
This seems to have been fixed. There are three different JLine configurations that affects how the file/directory completion is performed. The relevant configurations options are `Reader` boolean option  `USE_FORWARD_SLASH` (default `false`) and `Parser` field `escapeChars` (default `new char[] {'\\'}`)

1) use forward slash in directory separator: `reader.option(Option.USE_FORWARD_SLASH, true)`             
   ```
   groovy-repl> nano c:/tmp/jline3-master/demo/pom.xml
   ```
2) use backward slash in directory separator:  `parser.setEscapeChars(null)` or `parser.setEscapeChars(new char[]{})`
   ```
   groovy-repl> nano c:\tmp\jline3-master\demo\pom.xml
   ```

3) use two backward slash in directory separator: default
   ```
   groovy-repl> nano c:\\tmp\\jline3-master\\demo\\pom.xml
   ```
