### ISSUE TITLE
Does not operate correctly in a Powershell console on Windows

### ISSUE THREAD

**Issue by brjeter** [jline/jline3#321]
This affects 3.9.0.

Seeing several issues:
- Commands cannot be entered normally. User has to type control+enter.
- Encoding of the output is incorrect
- Backspace cannot be used

Note: I have not used jline directly. I saw this when using Karaf. See https://issues.apache.org/jira/browse/KARAF-5996.

**Comment by jbonofre** [comment]
For backspace, key, a simple workaround is to `set TERM=windows`.

**Comment by jbonofre** [comment]
Nothing related to Jline here, it was missing `TERM` in Karaf `client.bat` and also, issue with encoding in Karaf `SshTerminal`.

**Comment by jbonofre** [comment]
Can you please close this issue ?
