### ISSUE TITLE
Highlighting in history output

### ISSUE THREAD

**Issue by snuyanzin** [jline/jline3#325]
Could you please tell if there is a way to use the same highlighters for history output (to highlight each history record individually) as for `LineReader` ?

**Comment by snuyanzin** [comment]
such code snippet inside `org.jline.builtins.Commands#history` helps
```java
 Highlighter highlighter = reader.getHighlighter();
        for (History.Entry entry : history) {
            ...
            sb.append(highlighter.highlight(reader, entry.line()));
            ...
        }
```
Please let me know if there is anything I could miss

**Comment by gnodet** [comment]
Yes, that should be fine.  The `LineReader` also uses a `MaskingCallback`, but the history should be filtered already, so there's no need to handle that when displaying.
