### ISSUE TITLE
Nano needs 'restricted' mode support

### ISSUE THREAD

**Issue by sharkos** [jline/jline3#334]
The implementation in JLine should be able to support the 'restricted' mode features provided by the C implementation. This is for security when running in certain configurations. The GNU Nano man page specifics restricted mode as follow: 

-R, --restricted
              Restricted mode: don't read or write to any file not specified on the command line; don't read  any  nanorc  files  nor  history files; don't allow suspending nor spell checking; don't allow a file to be appended to, prepended to, or saved under a different name if it already has one; and don't use backup files.

**Comment by gnodet** [comment]
Note that backup / prepend / append / nanorc / history files / spell checking are currently not supported, so we're left with suspending / saving under a different name.
