### ISSUE TITLE
License mismatch between pom&readme and LICENSE.txt

### ISSUE THREAD

**Issue by zentol** [jline/jline3#335]
The [pom.xml](https://github.com/jline/jline3/blob/master/pom.xml#L32) and [README.md](https://github.com/jline/jline3/blob/master/README.md#license) both refer to the BSD 2-clause license, but the [LICENSE.txt](https://github.com/jline/jline3/blob/master/LICENSE.txt) contains the BSD 3-clause license.

**Comment by gnodet** [comment]
Thx, I fixe the 2 links to point to https://opensource.org/licenses/BSD-3-Clause

**Comment by zentol** [comment]
Note that all the license headers in [pom](https://github.com/jline/jline3/blob/master/builtins/pom.xml#L9) and [java](https://github.com/jline/jline3/blob/master/terminal-jansi/src/main/java/org/jline/terminal/impl/jansi/JansiNativePty.java#L7) files also link to the BSD 2-clause.

**Comment by gnodet** [comment]
Right, I fixed them all I think.
