### ISSUE TITLE
Terminal Writer Outputting Wrong Formatted Output

### ISSUE THREAD

**Issue by alsaha** [jline/jline3#338]
Hi,

We're having some issues with the Jline library terminal when trying to use it's writer. When we try to write a string using the terminal writer's print statement, it's appending characters around the string.

Example:
When printing: terminal.writer().print("Username:");
We get the output string as "[?1l>[?1000l[?2004lUsername:[?1h=[?2004h",  where as we want to get only "Username:" as the output.

We've tried the solution from this link https://github.com/jline/jline3/issues/181 by setting the "BRACKETED_PASTE_OFF". But that didn't work.

Regards,
Alok

**Comment by alsaha** [comment]
Setting the option (BRACKETED_PASTE, false) on the linereader did get rid of the 2004 strings. 

But I'm still getting some more stuff attached to the user name field "[?1l>[?1000lUsername:[?1h=". Looking if any other option needs to be disabled/ enabled.

**Comment by gnodet** [comment]
Are you printing from a different thread while the LineReader is working ?
If so, you need to use `printAbove` as explaine in the following issue
  https://github.com/jline/jline3/issues/292
What you see is the output of the cleanup which is done at the end of a `readLine` call and the output of the initialization done in a new `readLine` call.
Could you attach your a working example to reproduce the problem ?

**Comment by alsaha** [comment]
Thanks the printAbove did the trick and it's outputting the correct line format.

This was the fix:

`                final TerminalBuilder builder = TerminalBuilder.builder();
                 builder.jansi(false);
                builder.streams(in, out);
                terminal = builder.build();
                final Completer completer = new StringsCompleter(SHELL_CMD_QUIT, SHELL_CMD_EXIT, SHELL_CMD_VERSION, SHELL_CMD_HELP);
                reader = LineReaderBuilder.builder().terminal(terminal).completer(completer).build();
                reader.option(BRACKETED_PASTE, false);
               
               #To print to the terminal:

             reader.printAbove(telnetSessionLogin(line.toLowerCase(), commandMode));
             terminal.writer().print(telnetSessionLogin(line.toLowerCase(), commandMode));`
