### ISSUE TITLE
The prompt line does not scroll back when switching history lines

### ISSUE THREAD

**Issue by hyee** [jline/jline3#341]
If the history items have a cross-line command, switching to this command with the arrow keys will move the prompt line up from the screen bottom, but when switching to another historical line, the prompt will not scroll back to the origin position.

Attach [history.log](https://github.com/jline/jline3/files/2716185/history.log) for your reference, and below are the screen-shots as an example:
`1. waiting for input:`
![image](https://user-images.githubusercontent.com/761520/50535445-1e64f700-0b85-11e9-95fa-787f464525f1.png)

`2.switching to multi-lines command:`
![image](https://user-images.githubusercontent.com/761520/50535479-59ffc100-0b85-11e9-9225-ec22ac467ef2.png)

`3. switching to single-line command:`
![image](https://user-images.githubusercontent.com/761520/50535484-65eb8300-0b85-11e9-8b1f-98ce667d5dc2.png)

**Comment by gnodet** [comment]
That looks like the expected behavior to me.  The zsh shell does behave in a similar way.  The usual readline is not a full screen app, it should use the current line and a few additional lines if needed, but it does not control the overall vertical cursor position.

**Comment by hyee** [comment]
I agree that this behavior is expected in almost all the cases. 
BTW, is there a way to control the scroll behavior if I extend the `DefaultHistory` class? Because sometimes the historical command is too long for the screen.

**Comment by gnodet** [comment]
The `DefaultHistory` class does not control the display.  This is done mainly from the `Display` class.  I don't think the case where the command has a number of lines greater than the display height is really supported at the moment.

**Comment by hyee** [comment]
Thank a lot, I'm closing this ticket.
