### ISSUE TITLE
Target release date for the next release.

### ISSUE THREAD

**Issue by notthetup** [jline/jline3#343]
Hello! I'm curious as to when the next release is being planned. I'm looking to pick up this fix : https://github.com/jline/jline3/commit/5a58d01c960c0800f37a85fb4baf666ab693bfdb

**Comment by gnodet** [comment]
I need to go through the backlog, but I will definitely try to release JLine before the end of january.

**Comment by gnodet** [comment]
Very soon...

**Comment by gnodet** [comment]
JLine 3.10.0 has been released on 2019-02-12
