### ISSUE TITLE
Less doesn't work well in ConEmu and WSL Bash console

### ISSUE THREAD

**Issue by hyee** [jline/jline3#344]
When `org.jline.builtins.Less` is called with a `ByteArrayInputStream` as the source, it will print only the last line that matches the screen height. After hitting the right/left arrow keys, the screen is rendered as normal.
 
Calling `Display.reset()` doesn't help before invoking `Display.update`, but `Display.clear()` helps, however it will remove some previous output lines.

The same issue happens on the Bash console of Win10 WSL system.

Below is the screen cap.

![image](https://user-images.githubusercontent.com/761520/50720294-18bb6400-10e5-11e9-99d7-e05eb0b64975.png)

Apart from that, the calculation of `Display.cursorPos` for `Less` may have some issue,  as a result,  when reaching the last line of the whole buffer(for example totally 111 lines), scrolling backward to top or one window could leave some empty lines on the buttom(see screencap below), the temporary workaround is to call `Display.clear()`.
![image](https://user-images.githubusercontent.com/761520/50720372-fcb8c200-10e6-11e9-9f1f-4c4301bb07ab.png)

**Comment by gnodet** [comment]
Is this really specific to using a ByteArrayInputStream + windows ?

**Comment by gnodet** [comment]
Could you verify that it works correctly for you ?
