### ISSUE TITLE
jline3 with gradle

### ISSUE THREAD

**Issue by tomocrafter** [jline/jline3#346]
Although trying to use jline3 with gradle, trying to start up in windows environment results in an error.
Is there a solution?
`
Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:316)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:262)
        at *
        Suppressed: java.lang.UnsupportedOperationException
                at org.jline.terminal.impl.jansi.JansiSupportImpl.winSysTerminal(JansiSupportImpl.java:109)
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:348)
                ... 4 more
`

**Comment by mattirn** [comment]
I think you should add [`org.fusesource.jansi:jansi`](https://search.maven.org/search?q=g:org.fusesource.jansi%20AND%20a:jansi&core=gav) jar in your classpath

**Comment by tomocrafter** [comment]
Using: 
`
compile group: 'org.fusesource.jansi', name: 'jansi', version: '1.17.1'
`

**Comment by mattirn** [comment]
Exception 
`java.lang.UnsupportedOperationException at`
`org.jline.terminal.impl.jansi.JansiSupportImpl.winSysTerminal(JansiSupportImpl.java:109)`
will be thrown only if you do not have `jansi` jar in classpath or its version <1.12.

**Comment by gnodet** [comment]
Also check that you don't have any `jline2` dependencies in the classpath, as `jline2` binaries do embed `jansi:1.12`.

**Comment by tomocrafter** [comment]
![image](https://user-images.githubusercontent.com/10905364/50907675-50226b80-146b-11e9-9c37-70848c1f511c.png)

**Comment by gnodet** [comment]
The code can't lie and the only way the exception you see is thrown is when Jansi <= 1.12 is first in the classloader.  I can investigate, but I need a way to reproduce the problem easily. Please upload or attach a simple project to reproduce the issue.

**Comment by tomocrafter** [comment]
I ran this code but its returns null when I don't add Implementation-Version to the MANIFEST.MF
`
jar {
    ~
    manifest {
        attributes(
                'Implementation-Version': '2.0.0',
                'Main-Class': '~'
        )
    }
}
`
https://github.com/jline/jline3/blob/master/terminal-jansi/src/main/java/org/jline/terminal/impl/jansi/JansiSupportImpl.java#L34

**Comment by gnodet** [comment]
Yes, if the `Implementation-Version` attribute for the jansi jar is not present, the major / minor version would default to `0`, which would cause the exception you saw initially.

**Comment by tomocrafter** [comment]
it is not for jansi jar, it is for the software what I developing with jansi, jline (Sorry for bad English)

**Comment by gnodet** [comment]
Please upload a simple project that we can check.  I suspect you're embedding jansi somehow, and the version check would fail in such a case, leading to a version of 0.0, thus throwing an exception when creating the terminal.  If that's the case, you need to include the correct manifest entries in the jar embedding the `Ansi` class in order to provide the right version.

**Comment by tomocrafter** [comment]
Here https://github.com/tomocrafter/JLineTest

**Comment by gnodet** [comment]
In your build, you're embedding `jansi`, so the version which comes from the `MANIFEST.MF` in the jansi jar is lost.  In order to fix the problem, you need to bring it back in your `MANIFEST`.
Try with the following:
```
    manifest {
        attributes(
                'Implementation-Title': 'JLineTest',
                'Implementation-Version': version,
                'Main-Class': 'net.tomocraft.Main',
        )
        attributes(
	    [ 'Implementation-Version': '1.17.1' ],
	    'org/fusesource/jansi/'
        )
    }
```
