### ISSUE TITLE
Cooperation with picocli project

### ISSUE THREAD

**Issue by remkop** [jline/jline3#349]
Dear JLine maintainers,

I wonder if you would be interested in some form of cooperation with the [picocli](https://github.com/remkop/picocli) project. I believe JLine and picocli are a perfect match for users developing interactive shell applications with some set of commands, where each command may have options, positional parameters and subcommands.

As an example of what is possible, Picocli currently has these modules:

* [picocli-shell-jline2](https://github.com/remkop/picocli/tree/master/picocli-shell-jline2)
* [picocli-shell-jline3](https://github.com/remkop/picocli/tree/master/picocli-shell-jline3)

These modules have a `PicocliJLineCompleter` that show context-sensitive completion candidates for options, option parameters and subcommands of a set of picocli commands. (The readme of each module has an example.) Applications that use picocli to define their commands no longer need to hand-code Completers for their commands and options. (An early version of this is used in the [Micronaut CLI](http://guides.micronaut.io/micronaut-cli/guide/index.html).)

This is nice, but looking at https://github.com/jline/jline3/issues/254 , I realize that much more is possible. I love that demo and I would love to hook it into what picocli can offer!

The picocli object model is quite rich. It can provide all the details displayed in the status bar. For example, it can generate a command synopsis, and provide descriptions for a command and its options, using ANSI colors. When the demo shows a dropdown with multiple subcommands or options, the status bar could query the picocli object model to show the description for all completion candidates, which would help users select the desired option.

But this is just one idea. I am sure there are many ways in which JLine and picocli can be combined to create interesting functionality.

Please let me know if this sounds interesting.

Remko

**Comment by gnodet** [comment]
This is certainly very interesting.  Investigating picocli is actually on my todo list because I saw you already support Substrate VM (https://picocli.info/picocli-on-graalvm.html).  That's definitely something I'd like to try with JLine 3, though not sure how deep we can integrate, since JLine does fancy things...

Fwiw, #254 is not JLine powered, but that would be a goal, if time permits.

Anyway, I don't have much free time atm, but that's definitely on my todo list !
