### ISSUE TITLE
Update status asynchronous

### ISSUE THREAD

**Issue by musicha** [jline/jline3#352]
Hi, I wanna update the status from another thread but I run into issue when `Status::update` is called all visible competitions disappear.

Kotlin code snippet:
```
val terminal = TerminalBuilder.builder().build()

Thread {
    var counter = 0
    while (true) {
        val status = Status.getStatus(terminal)
        counter++
        status.update(listOf(AttributedStringBuilder().append("counter: $counter").toAttributedString()))
        Thread.sleep(1000)
    }
}.start()

val reader = LineReaderBuilder.builder()
        .terminal(terminal)
        .completer(StringsCompleter("c1", "c2"))
        .build()

while (true) {
    reader.readLine("> ")
}
```

When I hit "c" and press tab, I see the completions for max 1 second and they disappear.

Any idea how I can avoid that?

I use the version 3.9.0

**Comment by musicha** [comment]
That is how it looks like: 
https://asciinema.org/a/lFzTYGI5sxY2ge4yfxJC52Bh3

**Comment by gnodet** [comment]
Could you try with the following:
```
val terminal = TerminalBuilder.builder().build()

val reader = LineReaderBuilder.builder()
        .terminal(terminal)
        .completer(StringsCompleter("c1", "c2"))
        .build()

Thread {
    var counter = 0
    while (true) {
        val status = Status.getStatus(terminal)
        counter++
        status.update(listOf(AttributedStringBuilder().append("counter: $counter").toAttributedString()))
        reader.redisplay()
        Thread.sleep(1000)
    }
}.start()

while (true) {
    reader.readLine("> ")
}
```

**Comment by musicha** [comment]
Sadly it doesn't work. When the completer options are shown it seems like method `redisplay` blocks and either status is updated or counter is incremented.

**Comment by gnodet** [comment]
So the problem is that the `LineReaderImpl` holds a lock when calling `BindingReader#readBinding(...)` methods to read the input. 
I'm working on it.
