### ISSUE TITLE
Archived asciicast Demo Widgets and Keymaps

### ISSUE THREAD

**Issue by sirolf2009** [jline/jline3#357]
The asciicast at the wiki page https://github.com/jline/jline3/wiki/Demo-Widgets-and-Keymaps has been archived because it was uploaded by an anonymous user

**Comment by HSerg** [comment]
And https://github.com/jline/jline3/wiki/Demos

**Comment by gnodet** [comment]
I fear they've been lost.

**Comment by mattirn** [comment]
Removed broken links and added other demos.
