### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by pabloa** [jline/jline3#36]
Hello,

I am using jline3 to write a sql client. Some users write SQL sentences using multiple lines. A SQL command could have multiple lines and it finishes with a ';' in the end.

Is it possible to tell jline3 to use ; as the end of the line in LineReaderImpl (or in the class performing that job)?

**Comment by gnodet** [comment]
For which behavior ? You mean using `;` as a `<return>` key ? Or to delimit commands for completion, parsing, syntax highlighting, etc... ?

**Comment by pabloa** [comment]
Hello

What I need is:

- User write a command, for example:
```SQL
SELECT * <return>
FROM myTable <return>
WHERE myTable.id = 42; <return>
```

- When the user hit ';' and '<return>' jline3 should return all those lines as one String. 
- History functionality should work as usual but in this case it should show all the SELECT sentence.

I want to reproduce the same behavior than, for example, plsql or mysql clients.

**Comment by gnodet** [comment]
You need to implement a custom `Parser`, see [Parser.java](https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/Parser.java).
For a simple implementation, throw an `EOFError` if the input does not end with `;`.

**Comment by pabloa** [comment]
Awesome! I just could do it with JLine 3.1.2. 
Thank you

**Comment by j2kun** [comment]
@pabloa could you point me to your implementation? I'm curious to see how you did it.

**Comment by pabloa** [comment]
@j2kun that happened in 2016 in a long time gone company. ;)

**Comment by j2kun** [comment]
For posterity let me include my version, happy to hear of any improvements you might see.

@gnodet any chance a version of this could be included in the library, to save future fools like me the effort? :)

```java
import org.jline.reader.EOFError;
import org.jline.reader.ParsedLine;
import org.jline.reader.Parser;
import org.jline.reader.SyntaxError;
import org.jline.reader.impl.DefaultParser;

/** A jline extension for SQL-like inputs. Commands are terminated with a semicolon. */
public final class MultilineParser implements Parser {

  private static final Parser DEFAULT_PARSER = new DefaultParser();

  @Override
  public ParsedLine parse(String line, int cursor, Parser.ParseContext context) throws SyntaxError {
    if ((Parser.ParseContext.UNSPECIFIED.equals(context) || Parser.ParseContext.ACCEPT_LINE.equals(context)) 
        && !line.trim().endsWith(";")) {
      throw new EOFError(-1, cursor, "Missing semicolon (;)");
    }

    return DEFAULT_PARSER.parse(line, cursor, context);
  }

  public MultilineParser() {}
}
```
