### ISSUE TITLE
Can i write message in color in the terminal?

### ISSUE THREAD

**Issue by Singulativ** [jline/jline3#368]
I want to write colored messages in the Console. Both in Windows as in Linux?
Can jline3 do it for me? And if yes how? Please tell me.

**Comment by snuyanzin** [comment]
yes it is possible here is some demo from another project which uses jline3 https://asciinema.org/a/7fHnIDqqdmEk1ZoCBs9p3SAD2

Also there is a code snippet in jine3's tests https://github.com/jline/jline3/blob/a24636dc5de83baa6b65049e8215fb372433b3b1/builtins/src/test/java/org/jline/example/Example.java#L184
