### ISSUE TITLE
Candidates containing spaces lead to unexpected behaviour

### ISSUE THREAD

**Issue by loetermann** [jline/jline3#37]
Using only the following StringsCompleter resulted in an unexpected behaviour:
``new StringsCompleter("foo bar abc", "foo bar xyz", "foobar")``

Typing ``fo+tab`` worked alright.
Typing ``foo +tab`` was completed to ``foo foo``.
Same is true for ``foo bar + tab`` and ``foo foo +tab``.
``foo b+tab`` lead to a ``/ by zero`` exception.

The same completer worked fine with JLine 2.14.2.
Are Candidates supposed to represent only one word?

**Comment by gnodet** [comment]
Yes.

**Comment by loetermann** [comment]
Ok, thanks.

My bad, the ``/ by zero`` only appeared as I was using 3.0.0.M1. With 3.0.1 it works fine.

I wrote a piece of code now that splits each String into words (using the current Parser), and returns an ArgumentCompleter chaining the words. This serves the purpose for now.
