### ISSUE TITLE
Unwanted warning

### ISSUE THREAD

**Issue by dprutean** [jline/jline3#372]
I wrote a small console application using JLine, then I packed as executable using Insall4j and Exe4j. Each time when I start it on Windows 10 I get the warning below. Is there any way to suppress this ? For me the console application works fine, I don't want the users to get this on screen.

Apr. 05, 2019 12:35:05 NACHM. org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

**Comment by mattirn** [comment]
A way to get rid of the Warning is to add either Jansi or JNA library in your classpath as stated in jline README:
_"On the Windows platform, relying on native calls is mandatory, so you need to have either Jansi or JNA library in your classpath along with the jline-terminal-jansi or jline-terminal-jna jar. Failing to do so will create a dumb terminal with no advanced capabilities."_

**Comment by bdw429s** [comment]
I used to get that when running my JLine-based console app on CI servers.  I added this to the Terminal BuIlder DSL to get rid of it:

```
.dumb( true )
```
