### ISSUE TITLE
CTLR+D throws InterruptedIOException and InterruptedException

### ISSUE THREAD

**Issue by fqliao** [jline/jline3#378]
Hello, We've been using jline3.10 for the console.  On Ubuntu Terminal, When pressing `CTRL + D` and then pressing `Enter` causes the InterruptedIOException and InterruptedException. And I can not exit the terminal.
![image](https://user-images.githubusercontent.com/16574664/56075147-60dad880-5df0-11e9-9de6-d48c861f2b09.png)

The code as follows:
```
...
Terminal terminal = TerminalBuilder.builder()
.nativeSignals(true)
.signalHandler(Terminal.SignalHandler.SIG_IGN)
.build();

Attributes termAttribs = terminal.getAttributes();
termAttribs.setControlChar(ControlChar.VEOF, 4);
termAttribs.setControlChar(ControlChar.VINTR, 4);
terminal.setAttributes(termAttribs);

LineReader lineReader = LineReaderBuilder.builder()
.terminal(terminal)
.completer(new AggregateCompleter(completers))
.build();

while(true)
{
     String request = lineReader.readLine("[group:" + ConsoleImpl.groupID + "]> ");
     ...
}
```

**Comment by bdw429s** [comment]
In my use of JLine, I catch `org.jline.reader.UserInterruptException` (Ctrl-C) and `org.jline.reader.EndOfFileException` (Ctrl-D) and my application responds accordingly.

**Comment by gnodet** [comment]
Yes, you do need to catch the two exceptions and handle them correctly.
