### ISSUE TITLE
Can't I use java -cp xxx to run a jline3 Java project? ?

### ISSUE THREAD

**Issue by wl4g** [jline/jline3#380]
I am using java -cp xxx to run a jline3 Java project, why lineReader.readLine(">") always returns null, and it will loop indefinitely, my code probably looks like this:
While(true){
String cmds = lineReader.readLine(">");
// cmds process...
}

**Comment by wang4ever** [comment]
I tried to package it directly into a jar, and then java -jar xx.jar will run it normally. I don't know why? ? ?
