### ISSUE TITLE
Terminal height resizing breaks jline status line

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#387]
When decreasing jline terminal height the cursor is misplaced in status line.

![misplaced-cursor](https://user-images.githubusercontent.com/6079480/57190885-e5b4a000-6f1f-11e9-8f60-d7f1775e4bd5.jpg)

**Comment by eqvis** [comment]
Seen with cmd.exe and Windows Terminal

**Comment by mattirn** [comment]
@eqvis, fix has been partially rolled back because it caused problems in consoleZ, see #492.
