### ISSUE TITLE
Jline fails inside a screen

### ISSUE THREAD

**Issue by Niall7459** [jline/jline3#391]
I am unable to use Jline correctly within a screen instance:
Outside of a screen it seems to work correctly:
![Screenshot 2019-05-11 at 11 25 31](https://user-images.githubusercontent.com/9781846/57568449-83581580-73df-11e9-93f8-d84227a89e0b.png)
However inside a screen it fails with an UnsupportedOperationException
![Screenshot 2019-05-11 at 11 26 32](https://user-images.githubusercontent.com/9781846/57568461-a387d480-73df-11e9-8cbc-67881c862bd0.png)
At this line:
![Screenshot 2019-05-11 at 09 02 41](https://user-images.githubusercontent.com/9781846/57568482-daf68100-73df-11e9-9e33-70f18c94926a.png)

Creating the reader:
![Screenshot 2019-05-11 at 11 27 08](https://user-images.githubusercontent.com/9781846/57568469-bd291c00-73df-11e9-9fcb-4bab7fb897a3.png)

Any help is appreciated, thank you!

**Comment by PMarci** [comment]
I'm facing the same issue with `screen` under the `byobou` wrapper. I think I didn't have this issue about half a year ago.

**Comment by Niall7459** [comment]
Yeah so it seems the \\0-9 codes cause this although I have no idea why it would happen inside screen.

**Comment by Niall7459** [comment]
In the meantime I’m using version 3.3.0 which does not have this issue.

**Comment by gnodet** [comment]
Could you give the output of the `infocmp` command when running in `screen` / `byobou` ? There must be one sequence which is not properly recognized for some reason.

**Comment by gnodet** [comment]
Duplicates https://github.com/jline/jline3/issues/408
