### ISSUE TITLE
tips like redis-cli

### ISSUE THREAD

**Issue by zenglian** [jline/jline3#394]
Does jline support tips like redis-cli ( interactive mode)? 
E.g., when you type "get", it will prompt you the next candidate token is "key".

**Comment by snuyanzin** [comment]
If I understand you correct then yes it is possible. You should take a look at ArgumentCompleter or TreeCompleter or in case of more sophisticated scenarios RegexCompleter.
There is some doc https://github.com/jline/jline3/wiki/Completion and example of usage https://github.com/jline/jline3/blob/master/builtins/src/test/java/org/jline/example/Example.java

**Comment by mattirn** [comment]
No, jline does not support [redis-cli](https://asciinema.org/a/217618) like tips as you type. However there are already a couple of tickets about, see  #46 and #254
