### ISSUE TITLE
What's the recommended way to customize key binding?

### ISSUE THREAD

**Issue by markx** [jline/jline3#398]
For example I want to change `CTRL-P` to `UP_LINE_OR_SEARCH` instead of `UP_LINE_OR_HISTORY`. Is there an easy way to do it?

**Comment by mattirn** [comment]
You can use jline builtin command `keymap`:

`prompt> keymap ^P up-line-or-search`

In java, I do not the recommended way put this should work:
```
import org.jline.keymap.KeyMap;
import org.jline.reader.*;
............
............
LineReader reader = LineReaderBuilder.builder()......
KeyMap<Binding> map = reader.getKeyMaps().get(LineReader.MAIN);
map.bind(new Reference("up-line-or-search"), KeyMap.translate("^P"));
```

**Comment by markx** [comment]
@mattirn Thanks! it works for me.
