### ISSUE TITLE
How to prevent quotes autoclose while completion?

### ISSUE THREAD

**Issue by snuyanzin** [jline/jline3#405]
Currently I use simple StringCompleter and it works well until there is no non-closed quotes.
For instance the line 
```
select * from "SALES".EM
```
could be completed to 

```
select * from "SALES".EMPS
```
and this is as expected;
However the line 
```
select * from "SALES"."EM
```
is going to be completed as

```
select * from "SALES".""EMPS"
```
i.e. somehow jline3 decides to autoclose the double quote and opens one more at the end.
Is it possible somehow to custom this functionality?

**Comment by snuyanzin** [comment]
Looks like it happens at _org.jline.reader.impl.DefaultParser.ArgumentList#escape_
and overriding of this method helps

**Comment by gnodet** [comment]
Yes, this is exactly what you need to do.  The parser you were using is the default one, and definitely not suited for SQL, though the behavior you indicate looks weird anyway.
I think the goal was to end up with
```
select * from "SALES"."EMPS"
```

**Comment by snuyanzin** [comment]
thanks!
