### ISSUE TITLE
Regression: >.... prompt when using dumb terminal

### ISSUE THREAD

**Issue by Minecrell** [jline/jline3#411]
Using `LineReader` on JLine 1.12.0 produces a `>....` prompt instead of the specified prompt  
(here: `$ `) in dumb terminals. Native terminals do not seem to be affected.

Example code:

```java
LineReader reader = LineReaderBuilder.builder().build();
while (true) {
    reader.readLine("$ ");
}
```

Run it in IntelliJ IDEA or another dumb terminal, or use the system properties to force a dumb terminal. The `>....` prompt is shown instead of `$ `. It works fine on JLine 1.11.0 and below.

I suspect that #311 is the cause of this, since it added a `StringBuilder` with that string: 
https://github.com/jline/jline3/commit/062d25ca0c2989df72bc1c1787495c713fea9a48#diff-10c315592498f1bd016543e7c8d26ab5R3743 (cc @mattirn)

I don't really understand the code this commit changed, so I'm not sure about the purpose of that string for the string builder. It looks somewhat suspicious...

**Comment by Minecrell** [comment]
@mattirn Thanks for the patch! I tested #412 and the issue is gone. 👍

**Comment by gnodet** [comment]
JLine 3.12.1 has been release with this fix.
