### ISSUE TITLE
Clear Screen

### ISSUE THREAD

**Issue by GitAntoinee** [jline/jline3#418]
Hello, how can I clear the screen? Like the 'cls' command on Windows or 'clear' on Linux

**Comment by gnodet** [comment]
There's a `CLEAR_SCREEN` widget, bound by default to `Ctrl+L` which basically calls [`LineReaderImpl.clearScreen()`](https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L5419-L5435)  if you are reading a line.  If you're working purely with the terminal, then `terminal.puts(Capability.clear_screen)` is what you're looking for.

**Comment by findinpath** [comment]
Is there any chance to expose this method outside of `LineReaderImpl`?

When working with `LineReaderBuilder.builder()....build()` this method is not available in the `LineReader` interface.

Is the `LineReader` the right place to handle the responsibility of clearing the screen?

**Comment by gnodet** [comment]
@findinpath there are 2 different use cases.  A first use case it when not reading a line using the `LineReader` and you just want to clear the screen, for example when starting / exiting your application.  In such a case, you need to use the `Terminal` interface:
```
terminal.puts(Capability.clear_screen);
terminal.flush();
```

However, if you want to clear the screen while reading an input using the line reader, which can be done by using a specific key (Ctrl+L for example), or from inside a callback, you want to call the `CLEAR_SCREEN` widget using
```
reader.callWidget(LineReader.CLEAR_SCREEN);
```

**Comment by findinpath** [comment]
I actually want to read the command `clear` from the console and as a consequence to clear the screen.

I just tried

**Comment by gnodet** [comment]
@findinpath you're in the first case, because once the command has been read, the reader is not reading a new command yet (in the usual read/execute loop)

**Comment by findinpath** [comment]
@gnodet  thank you for the feedback.

Indeed it works as expected. Sorry for not paying attention at your previous comment.

Do you by chance have any idea why ,when running the application via IntelliJ - from the editor via the Run option, not from the terminal - the options Ctrl+L or "clear" don't have any outcome? Does it have to do with the console emulated by IntelliJ ?

**Comment by gnodet** [comment]
Yes, it should work if you run it from the real Intellij terminal (i.e. the one with a real shell).  The console used to start applications is not a real terminal, so JLine can't leverage it, see https://github.com/jline/jline3/issues/263
