### ISSUE TITLE
Completer sortoing order

### ISSUE THREAD

**Issue by dprutean** [jline/jline3#419]
I am using JLine3 with an SQL command line app. The completion is sorting the candidates in the lenght order. Is it possible to simple sort them alphabetical ? Maybe I am doing something wrong ? Below a sample output and the Class I am using for completion.

![image](https://user-images.githubusercontent.com/4970910/61515597-4de52f00-aa03-11e9-8233-bd4113a07b8e.png)

`public class SQLCompleter implements Completer {

    private static final Logger LOGGER = Logger.getLogger( Processor.class );
    private boolean enabled = true;

    public void setEnabled( boolean enabled ){
        this.enabled = enabled;
    }

    @Override
    public void complete(LineReader reader, ParsedLine line, List<Candidate> candidates) {
        if ( enabled ) {
            String buf = line.line();
            String[] keywords = buf.split(" ");
            String lk = keywords.length > 0 ? keywords[keywords.length - 1] : "";
            String keyword = buf.endsWith(" ") ? "" : lk;

            final Connector connector = ConnectionFactory.getFirstConnector();
            if (connector != null) {
                try {
                    if (!connector.isLearned()) {
                        connector.learnSchema( connector.getSchemaName(), null, false);
                    }
                } catch (Throwable ex) {
                    LOGGER.error("Error in Processor", ex );
                }
                for (Schema schema : connector.getSchemes()) {
                    validateCandidate(keyword, schema.name, candidates);
                    for (Table table : schema.tables) {
                        validateCandidate(keyword, schema + "." + table.name, candidates);
                        validateCandidate(keyword, table.name, candidates);
                    }
                }
            }
        }
    }

    private void validateCandidate( String typedString, String possibleMatch, final List<Candidate> candidates ) {
        if ( typedString == null || possibleMatch.toLowerCase().startsWith(typedString.toLowerCase())) {
           candidates.add ( new Candidate(AttributedString.stripAnsi(possibleMatch), possibleMatch, null, null, null, null, true) );
        }
    }

}`

**Comment by snuyanzin** [comment]
`Candidate` implements `java.lang.Comparable` and the default way of sorting is defined in `org.jline.reader.Candidate#compareTo`.
You need to extends from `Candidate` and override this method in a way you like and use your extension instead of `Candidate`
