### ISSUE TITLE
How to have working round brackets in completer's suffix?

### ISSUE THREAD

**Issue by snuyanzin** [jline/jline3#425]
There is a simple Candidate initialization for completer
`new Candidate("value", "displ", null, "descr", "(", null, false)`
where `"("` is a suffix. And there is no brackets appear during completion.
I tried the same code however not with bracket but e.g. with `"test"` and it works.
It seems there is a sort check for bracket or something like this which I have still not found...

**Comment by gnodet** [comment]
Have you found the problem ?

**Comment by mattirn** [comment]
Added completion candidate suffix test. Did not found any difference between `"("` and `"Test"` suffixes. They both works in a same way.

**Comment by mattirn** [comment]
I have not been able to reproduce the problem. For me candidate suffix works as designed.
