### ISSUE TITLE
Exception when use Terminal on docker

### ISSUE THREAD

**Issue by rudy2steiner** [jline/jline3#435]
I'm sure it's ok on my local MacOS,but exception on remote docker.

When start my program, i got following 2 exceptions  :
1.  Exception in thread "org.jline.terminal.impl.ExternalTerminal@4690b489 input pump thread" java.lang.NullPointerException
	at org.jline.terminal.impl.ExternalTerminal.pump(ExternalTerminal.java:53)
	at java.lang.Thread.run(Thread.java:748)
null
null
...
2. exception: 'stty -F not a tty -a': stty: 'not a tty': No such file or directory

------

my code, has first exception on local and remote:
```
Terminal terminal = TerminalBuilder.builder()
                .system(false)
                .build();

        terminal.handle(Terminal.Signal.QUIT, (Terminal.Signal sign)->{
            finder.stop();
            System.exit(0);
        });
        LineReader lineReader = LineReaderBuilder.builder()
                .terminal(terminal)
                .build();
        String prompt = "zebra >";
        while(true){
            String command;
            try {
                command = lineReader.readLine(prompt);
                String[] args=command.split(" ");
                parser.parseCommand(command);
                String cmd=parser.getCommand();
                if(!cliCommands.containsKey(cmd)){
                    showCommandsUsage();
                    continue;
                }
                // process command
                try {
                    cliCommands.get(cmd).parse(args).exec();
                }catch (CommandExecutionException e){
                    System.err.println(e.getMessage());
                    showCliUsage(cmd,cliCommands.get(cmd).getOptions());
                }
            } catch (UserInterruptException e) {
                // Ignore
                System.out.println("\nBye.");
                //lineReader.
                break;
            } catch (EndOfFileException e) {
                System.out.println("\nBye.");
                System.exit(0);
            }catch (Exception e){
                System.out.println("\n"+e.getMessage());
            }finally {
                parser.clean();
            }
        }
```
if i set terminal system true, it comes into another exception(second exception) on remote docker, but normal on local  :
```
Terminal terminal = TerminalBuilder.builder()
                .system(true)
                .build();
......

```

any one can help?

**Comment by gnodet** [comment]
When using a non system terminal (your first case), you need to provide an input and output streams on the builder.
In the second case, I think it should work, but you may need to run the docker in interactive mode (using the `--interactive` option of the `docker run` command).

**Comment by rudy2steiner** [comment]
Do you mean i need run my docker on interactive mode? 

But it's a service (docker run -d), and then enter it anytime and execute my shell command.
so how to deal the situation!

**Comment by rudy2steiner** [comment]
@gnodet  would you mind more advice

**Comment by gnodet** [comment]
If you run docker as a service, there's no terminal created, which leads to the second problem you had. I'm not sure how you can reattach later. Maybe you should try setting up the telnet protocol in your java process so that you can later connect to it from a terminal running in the docker vm.

**Comment by adeng-wc** [comment]
> I fix this problem by catch the exception and Just use Java Reader to readline input, if we don't have terminal , thanks for your reply

我也遇到相同的问题，想请教下，在docker 不启动交互模式的情况下，Java web 应用 你是如何解决的？
