### ISSUE TITLE
documented support for as-you-type syntax checking

### ISSUE THREAD

**Issue by PerBothner** [jline/jline3#46]
This is a wishlist item, which I think would be very neat for a language REPL.  I suspect it is already possible; if so it would be nice to have it documented (as in a "howto").

A number of IDEs (I'm most familiar with NetBeans) do as-you-type syntax checking: The IDE/compiler continuously re-compiles your source file automatically as you type (even before you save your file). It will highlight any errors or warnings it sees, perhaps with a squiggly line and hovers.  We can't do squiggly lines on a normal terminal, but the following is as good.

After each edit (and maybe a small timeout), Jline sends the current text (or a delta) is to the client. The client response includes any error messages. JLine prints those *below* the input area, by default in red (or perhaps orange for warnings).  In addition, the location of the error in the input area is highlighted: For compilers that report a character range for an error, that range would be colored (for example an orange background); for compilers that report only a position, the character at that position would be highlighted.

This could be combined with *accurate* syntax highlighting: For example the compiler can report whether an identifier is a definition or a use, so we can highlight the former but not the latter.

**Comment by gnodet** [comment]
The existing [`Parser`](https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/Parser.java) and [`Highlighter`](https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/Highlighter.java) interfaces can already work together to some degree to perform syntax highlighting.

If you run the demo, you can see the editing line is even modified before display to include any missing closing characters:
<img width="422" alt="highlight" src="https://cloud.githubusercontent.com/assets/84022/20514712/cf2061ba-b08d-11e6-9d0c-a6301990a9e6.png">

Printing parser errors at the bottom is a really nice idea and should be quite easy to do with the [`post`](https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L228) field which supports multiple lines.
