### ISSUE TITLE
Next release(s)

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#465]
@gnodet, I have fixed all the bugs (born in 3.13.0) that I'm aware. What do you think about to publish a new release 3.13.2?
The pull request #456 probably requires a minor version change due the change in `Highlighter` interface. I have been thinking to write also a new module in builtins to help integration of builtins command to JLine app #470. I'm probably able to do this within this week. After this we can publish 3.14.0.

**Comment by mattirn** [comment]
@gnodet, next version can be released when you find appropriate.
I have finished the coding now for a while... I will add later a couple of notes in wiki.

**Comment by gnodet** [comment]
@mattirn I've staged a candidate release for 3.13.2 at https://oss.sonatype.org/content/repositories/orgjline-1064/ if you want to have a look before I publish it.

**Comment by mattirn** [comment]
@gnodet It seems good to me!
