### ISSUE TITLE
automatic and accurate balanced brackets

### ISSUE THREAD

**Issue by PerBothner** [jline/jline3#47]
JLine does have simple bracket "bouncing": Type a closing paren/bracket, and the cursor briefly jumps to the open paren/bracket.  However, this is both inaccurate (it gets fooled if a paren/bracket is escaped or quoted) and incomplete (it doesn't handle string quotes, for example) - which is harmless, since it's only a brief bounce.

Some IDEs go further, and actually insert a closing bracket when you type type the open bracket.   One may have mixed feelings about this, but I believe it is highly desirable when doing as-you-type syntax checking (issue #46), so the compiler can work with a closer-to-valid program fragment.  However, if one does that, it is important to be accurate, which means consulting the compiler.

Some complications to note: We want to handle "brackets" where the open and close character are the same - for examples quotes for string literals.  We want to handle multi-character "brackets" for example `/*` and `*/` for C-style comments. XML literals are even more complex: `<p></p>`.

It is important that the user be able to explicitly type a closing bracket without getting a duplicate. I.e. after typing `(` the display is `()`; typing `+` updates it to `(+)` with the cursor before the `)`; typing `)` updates it to `(+)` with the cursor *after* the `)`.  In general, when typing a character *x* if the cursor is already before the same character *x* *and* *x* is part of a closing "bracket", just move the cursor past the *x* rather than adding a new one.  The tricky part is determining when *x* is part of a closing bracket: the compiler can give JLine that information, bundled with syntax highlighting.

To cause opening brackets to insert closing brackets is more complicated.  When the user types a character, in addition to inserting it the input area, JLine needs notify the compiler about which character was typed and where; if the character was the last character of an opening bracket the compiler responds back to JLine with the closing bracket to insert.

**Comment by gnodet** [comment]
Fwiw, the demo uses Gogo JLine which leverage the syntax highlighter to insert a _fake_ closing parenthesis, or whatever is missing.
It can be seen at [https://github.com/jline/jline3/wiki/Demo%20Widgets%20and%20Keymaps] around 25 seconds.
A real insertion could be done using custom widgets I suppose.

**Comment by mattirn** [comment]
Closed by  'New line automatic indentation after open bracket' #354 and 'Autopair custom widgets'.
