### ISSUE TITLE
org.jline.terminal.TerminalBuilder.doBuild IllegalStateException: Unable to create a system terminal

### ISSUE THREAD

**Issue by dbaltor** [jline/jline3#478]
I'm getting the `java.lang.IllegalStateException: Unable to create a system terminal`
when trying to start a Scala REPL within [Scala sbt](https://www.scala-sbt.org/) on Windows 8.1.

I've got the same error running on either **cmd** or **bash** shells. 

Here is the screenshot:

`C:\dev\dotty>sbt`
`[info] Loading settings for project dotty-build-build from build.sbt ...`
`[info] Loading project definition from C:\dev\dotty\project\project`
`[info] Loading settings for project dotty-build from build.sbt,plugins.sbt ...`
`[info] Loading project definition from C:\dev\dotty\project`
`[info] Loading settings for project dotty from build.sbt ...`
`[info] Resolving key references (15750 settings) ...`
`[info] Set current project to dotty (in build file:/C:/dev/dotty/)`
`[info] sbt server started at local:sbt-server-d26de3a6e9906cafff5f`
`sbt:dotty> repl`
`[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see
the list`
`[info] Running (fork) dotty.tools.repl.Main -classpath C:\Users\dbaltor\.ivy2\ca
che\org.scala-lang\scala-library\jars\scala-library-2.13.1.jar;C:\dev\dotty\libr
ary\..\out\bootstrap\dotty-library-bootstrapped\scala-0.21\dotty-library_0.21-0.
21.0-bin-SNAPSHOT.jar`
`Exception in thread "main" java.lang.IllegalStateException: Unable to create a s
ystem terminal`
`        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:316)`

**Comment by gnodet** [comment]
This is usually the case on Windows when neither `jansi` or `jna` library is on the classpath.

**Comment by dbaltor** [comment]
Thank you very much for the help and please accept my apologies for not being able to reply sooner. The error was due to the lack of write access on the working directory caused for running Cygwin on Win 8.1. It's working fine now.
Thanks again and happy holidays!
