### ISSUE TITLE
TailTipWidget should clear terminal status bar before change

### ISSUE THREAD

**Issue by remkop** [jline/jline3#481]
Running the [`picocli.shell.jline3.example.Example`](https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java) application (to reproduce, please use the latest version, I just updated it), after enabling the TailTipWidget terminal status bar with:

```
prompt> keymap ^[s tailtip-toggle
```
and hitting `ALT-S` to display the status bar, the issue can be reproduced by typing:

```
prompt> cmd -
```
This shows the following in the status bar:
```
-V --version            Print version information and exit.
-d --duration=<amount>  The duration quantity.
-h --help               Show this help message and exit.
-u --timeUnit=<unit>    The duration time unit.
-v --verbose            Specify multiple -v options to increase verbosity.
```

So far, so good. Now, add a `v`:

```
prompt> cmd -v
```
The status bar does not clear the previous output, it just overwrites some columns with the new output, resulting in a mixture of old and new output:

```
-v --verbose            Print version information and exit.
        Specify multiple -v options to increase verbosity.
        For example, `-v -v -v` or `-vvv`ssage and exit.
-u --timeUnit=<unit>    The duration time unit.
-v --verbose            Specify multiple -v options to increase verbosity.
```

I believe the status bar should be cleared before printing the new output.

**Comment by mattirn** [comment]
@remkop `TailTipWidget` calls `Status` class method `update()` to update terminal status bar. Status bar is cleared in [Status.java#L143](https://github.com/jline/jline3/blob/d949fb26ca608640a72561185de13e05f4e6ecb7/terminal/src/main/java/org/jline/utils/Status.java#L143). Seems that your terminal does not recognize `clr_eos` capability.
Which terminal are you using?

**Comment by remkop** [comment]
I was using the Windows Command Prompt on Windows 10.

**Comment by gnodet** [comment]
The code may need to be enhanced a bit to take care of the fact that some terminals may not support `clr_eos`.  In such cases, I think the `Status` class will have to move line by line and call `clr_eol` instead.
