### ISSUE TITLE
InfoCmp consumes about 128kb memory

### ISSUE THREAD

**Issue by CodingFabian** [jline/jline3#49]
When looking to reduce memory footprint of karaf, I noticed that InfoCmp consumes 128kb memory. This is mostly held by the NAMES map, which holds all the various permutations.
Could this be maybe restructured or even discarded after startup?

(yes I know. 128kb is not much. But its the third biggest consumer in this karaf runing on a low memory device.)

**Comment by gnodet** [comment]
The InfoCmp uses enums for capabilities, so while I'm quite sure the memory use is still the same, it may be a bit more difficult to simply get rid of it.

**Comment by gnodet** [comment]
Actually, it should be feasible, because the capability names are really only used during parsing, so it should be possible to tweak things a bit.

**Comment by gnodet** [comment]
The [memory-49](https://github.com/jline/jline3/tree/memory-49) branch provides a fix, but given there's a small incompatibility, I'd rather schedule that for 3.2.0

**Comment by CodingFabian** [comment]
thanks, that should do the trick
