### ISSUE TITLE
3.13 prevents scrolling in ConsoleZ

### ISSUE THREAD

**Issue by hyee** [jline/jline3#492]
Hi,
Jline v3.9 works well in [ConsoleZ](https://github.com/cbucher/console), but in the latest version, trying to scroll the screen with the vertical/horizontal scrolling bar, the screen will scroll back, either `TYPE_WINDOWS_VTP` or `TYPE_WINDOWS` has the same issue.  The case can be reproduced via running  `org.jline.example.Example` with any parameter.
This issue only happens on [ConsoleZ](https://github.com/cbucher/console), the executable file can be found at https://github.com/cbucher/console/wiki/Downloads.

**Comment by hyee** [comment]
As my test that the issue is due to the change of #388 , after removing  the newly added `redrawLine()` the issue is gone

**Comment by mattirn** [comment]
If we remove `redrawLine()` then after resizing terminal window command prompt will not be drawn. That's more like an aesthetic error than a real bug. I think we can remove `redrawLine()` if no other solution can be found.  

![Screenshot from 2020-01-04 10-30-18](https://user-images.githubusercontent.com/6079480/71763544-64ae0e00-2edd-11ea-9b84-7198f506620e.png)
