### ISSUE TITLE
Attempt to complete filename option value by using the whole option expression "--option=value"

### ISSUE THREAD

**Issue by mel4tonin4** [jline/jline3#504]
Hello.

I have a command with just one option named `"--path"` which is completed by a `FileNameCompleter`.

If I type `"--[TAB]"` the option name is completed to "--path=".

If I press `[TAB]` again, the content of the current working directory is displayed as completion candidates. If I pick a subdirectory named "folder", the option is completed to `--path=folder/`.

Then `[TAB]` stops working.

If I set a breakpoint inside `FileNameCompleter`'s code, I see that it is attempting to complete "--path=folder" instead of "folder", but there is no subdirectory called "--path=folder" in the current working directory, so no candidates are found.

Why is that happening?

If I remove the "=" sign, there is no completion at all. Does _jline3_ only accept "--option=value" and not "--option value"?

**Comment by mattirn** [comment]
Yes, for long options jline3 accept only "--option=value"

**Comment by mel4tonin4** [comment]
Ok, this is even more puzzling, then. Why is `FileNameCompleter` trying to complete the string "--path=folder" instead of "folder"?

**Comment by mattirn** [comment]
That has been fixed in [Completers.java#L795](https://github.com/jline/jline3/blob/58c385801d6beabab8c6bb504736122ee18feb6f/builtins/src/main/java/org/jline/builtins/Completers.java#L795).

**Comment by mel4tonin4** [comment]
Oh, I missed that. Thanks, mattirn!
When will this appear on mvm?

**Comment by mattirn** [comment]
I think the next release will be done in February or at the beginning of March. I do not know if you can download 13.3.4-SNAPSHOT jars somewhere.
