### ISSUE TITLE
Control-C during long running task terminates the shell

### ISSUE THREAD

**Issue by mel4tonin4** [jline/jline3#506]
Hello.

If I type `Control-C` while I'm typing a command in a _jline3_ shell, the editing of the current line is aborted and a new command line is started, with new prompt.

If a command takes time to execute, and `Control-C` is pressed during this time, the shell program is terminated and I end up on the _bash_ prompt.

How do I prevent this from happening?

Thanks.

**Comment by gnodet** [comment]
You need to register a signal handler on your terminal.
```
  terminal.handle(Signal.INT, sig -> {
     // handle the signal
  });
```
When reading a line, the jline's `LineReader` will do so but to intercept `Control-C` will be reset it to the previous value when exiting the call.

**Comment by mel4tonin4** [comment]
Thanks, Guillaume!
