### ISSUE TITLE
JLine3 interactive mode does not work in cygwin

### ISSUE THREAD

**Issue by adamGyure** [jline/jline3#520]
**Problem description:**

When running the REPL application in cygwin, the terminal's behavior is unpredictable. E.g. the prompt name is all over the place when I execute a command, additional whitespaces or line breaks are inserted randomly, tab completion and command history are not working.

**Steps to reproduce:**

1. Download and install cygwin: https://cygwin.com/install.html
1. Build the demo application in the project
1. Execute `jline-repl.bat`

Log during startup: `JLine terminal: xterm-256color`

In the terminal try using tab completion, get the previous command with the up arrow key, start typing a command then move the cursor within the command with the left and right arrow keys, execute the help command or just simply hit enter.

**Setup:**

- Windows 10 x64
- JLine3 3.14.0

**Comment by mattirn** [comment]
Have you executed `jline-repl.bat` using either `jansi` or `jna` option?
I assume you will have the same problem if you execute `jline-gogo.bat`.

**Comment by adamGyure** [comment]
Thank you for the quick answer.
I tried both `jansi` and `jna`, the result was the same.
By executing the `jline-gogo.bat` script I get even more issues. (tried with jansi and jna as well)

**Comment by mattirn** [comment]
Despite apparently correct terminal detection it seems to me that cygwin does not interpret correctly ansi sequences. Please, could you copy/paste the terminal output to your response.
What's the value of your `TERM` environment variable? You could change its value to `xterm` or `ansi` before launching repl app.

**Comment by adamGyure** [comment]
I tried with `TERM` `xterm` originally, then with `xterm-256color`, the same behavior. Now, I changed it back to `xterm`, but it does not matter as the `TerminalBuilder` internally changes the type from `xterm` to `xterm-256color` in case you are using Cygwin on Windows.

I'm attaching some screenshots:

**Help command with whitespaces(I typed the command without them)**
![jline3_help_command](https://user-images.githubusercontent.com/20340484/77949647-9d386a80-72c7-11ea-9821-bf5d49f11b2e.png)

**Misaligned prompt with extra line**
![help_command_output](https://user-images.githubusercontent.com/20340484/77948114-2a2df480-72c5-11ea-994a-e8fb9be62b5f.png)

**Clear command output**
![clear_command](https://user-images.githubusercontent.com/20340484/77948124-2e5a1200-72c5-11ea-8fe5-906e6cd5e3f8.png)

**Comment by mattirn** [comment]
I have installed Cygwin and reproduced your problem. Cygwin fails to display correctly because the method `terminal.getSize()` returns wrong terminal width. My real terminal size below was 80*24: 

```
groovy-repl> org.jline.builtins.SystemRegistry.get().terminal().istry.get().terminal().
getSize()
org.jline.builtins.SystemRegistry.get().terminal().getSize()
org.jline.builtins.SystemRegistry.get().terminal().getSize()          l().getSize()
rows    24
class   org.jline.terminal.Size
columns 102
```
This seems the same problem as reported here #151.

**Comment by mattirn** [comment]
I have installed Cygwin and reproduced the problem. This is the same problem as reported here #151 .

I have do not have an idea where is the bug. @gnodet, could you help?

**Comment by adamGyure** [comment]
@mattirn @gnodet The bug is related to the `PosixSysTerminal`.
It seems that the issue is gone if I force the creation of a `jansi` or `jna` based terminal.
However, it's not possible by setting them to true as the "Cygwin support code" will always have precedence in the `TerminalBuilder`:
```
                //
                // Cygwin support
                //
                if ((OSUtils.IS_CYGWIN || OSUtils.IS_MSYSTEM) && exec && !cygwinTerm) {
                    try {
                        Pty pty = ExecPty.current();
                        // Cygwin defaults to XTERM, but actually supports 256 colors,
                        // so if the value comes from the environment, change it to xterm-256color
                        if ("xterm".equals(type) && this.type == null && System.getProperty(PROP_TYPE) == null) {
                            type = "xterm-256color";
                        }
                        terminal = new PosixSysTerminal(name, type, pty, encoding, nativeSignals, signalHandler);
                    } catch (IOException e) {
                        // Ignore if not a tty
                        Log.debug("Error creating EXEC based terminal: ", e.getMessage(), e);
                        exception.addSuppressed(e);
                    }
                }
```
It seems odd that the only way to skip this condition is to disable a third option: `exec`.

Could you please tell me whether it's a valid workaround and what functionality do I lose?

**Comment by mattirn** [comment]
To force `jansi`/`jna` based terminal you can set `TERM=cygwin`

**Comment by adamGyure** [comment]
This is irrelevant as the outcome is exactly the same. Only the `PosixSysTerminal` uses the `exec` option, which I'm trying to get rid of.
The tool I'm developing is not bound to Cygwin in any way, so I would need to dynamically modify the `TERM` environment variable which is a significantly bigger overhead for the same behavior.

Also, this workaround does not make the code less confusing.
I have to explicitly say that I'm using Cygwin to disable JLine's Cygwin support.

What functionality do I lose with bypassing the buggy `PosixSysTerminal`?

**Comment by mattirn** [comment]
Ok, I have not used much `jansi`/`jna` based terminals but let's say so that if JLine built-in commands `nano`, `less` and `ttop` + other command-line features like tab-completion, the keyboard shortcuts, command auto-suggestions  etc are working well you do not lose anything. 
If you are not forced to use Cygwin you can give a try to [GitBash](https://gitforwindows.org/) which IMHO works rather well with JLine/`PosixSysTerminal`.

**Comment by mattirn** [comment]
duplicate with #151

**Comment by adamGyure** [comment]
Yes, GitBash works fine but I would rather avoid making it mandatory. Clients should be free to choose their terminal.

The other ticket was already closed once because of inactivity and the last update was in mid-December. It's very likely that the ticket will be closed again as the reporter doesn't seem to be interested in the solution or doesn't have time to update the ticket.
I would like to keep this report open and get updates.

**Comment by shoaniki** [comment]
This is technically not a duplicate -- the issue reported in 2017 must have had a different cause, because this behavior is a result of the support for Windows pseudo-consoles that was only added to Cygwin in December 2019.

Since git-bash is based on MSYS which is based on Cygwin, the fact that it works there now is no guarantee that it will continue to work in the future, if those projects pull in the upstream changes that cause this.

See https://github.com/fusesource/jansi/issues/165 for the same issue affecting jansi.

**Comment by gnodet** [comment]
@adamGyure @shoaniki could you try the branch I pushed at https://github.com/gnodet/jline3/commit/25e6fe138d394f45c6ddaaf4adf06dfe7ce0d4e1 ?
It seems to work for me, but I'd rather double check.

**Comment by David-dp-** [comment]
FWIW, Windows Subsystem for Linux (aka WSL2), which is an Ubuntu-based terminal built into Windows10 (64-bit) also behaves as a dumb terminal even when invoked this way:

`java -cp /mnt/e/Tools/rhino1_7R4/js.jar:/mnt/e/Tools/jline-3.14.1.jar:/mnt/e/Tools/jline-terminal-jansi-3.14.1.jar:/mnt/e/Tools/jansi-1.17.jar org.mozilla.javascript.tools.shell.Main`

btw, rhino is a javascript REPL and works fine when called this way; it's just limited to dumb terminal behavior.

**Comment by shoaniki** [comment]
@gnodet Thank you for working on this!  I can confirm that your branch appears to fix the display issues.  No unexpected whitespace, and "demo/jline-repl.sh jansi" has correctly coloured output.  (It's only 16 colours, but I believe that's a pcon limitation not a jline issue.)  Our app's jline-based CLI also displays correctly.

I have however noticed another issue -- keyboard shortcuts involving cursor keys, home/end, etc appear not to work.  Other shortcuts like Ctrl+N/Ctrl+P are fine.  I have verified that the breakage only occurs when Cygwin is using the new pseudo-console support, so this would seem to be another effect of that.  I have not yet attempted to debug this further.

**Comment by adamGyure** [comment]
@gnodet With your branch, the issues are fixed if I set the terminal to `jna` or `jansi` explicitly, thank you.

**Comment by gnodet** [comment]
@shoaniki would you mind raising a different issue for the problems you see ?
