### ISSUE TITLE
JLine JNA Terminal ................................. FAILURE

### ISSUE THREAD

**Issue by samyak-jn** [jline/jline3#523]
Hey,

On building JLine3, 
The following error is encountered `JLine JNA Terminal ....................... FAILURE`.
Building for Jline v3.14.0.

Here are the logs,

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/win/Kernel32.java:[22,30] error: cannot find symbol
  symbol:   method load(String,Class<Kernel32>,Map<String,Object>)
  location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/linux/LinuxNativePty.java:[29,52] error: cannot find symbol
  symbol:   method load(String,Class<CLibrary>)
  location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/linux/LinuxNativePty.java:[35,37] error: cannot find symbol
  symbol:   method load(String,Class<UtilLibrary>)
  location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/freebsd/FreeBsdNativePty.java:[29,52] error: cannot find symbol
  symbol:   method load(String,Class<CLibrary>)
  location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/freebsd/FreeBsdNativePty.java:[35,37] error: cannot find symbol
  symbol:   method load(String,Class<UtilLibrary>)
  location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/solaris/SolarisNativePty.java:[28,52] error: cannot find symbol
  symbol:   method load(String,Class<CLibrary>)
  location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/osx/OsXNativePty.java:[29,52] error: cannot find symbol
  symbol:   method load(String,Class<CLibrary>)
  location: class Native
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for JLine Parent 3.14.0:
[INFO] 
[INFO] JLine Parent ....................................... SUCCESS [  0.375 s]
[INFO] JLine Terminal ..................................... SUCCESS [  1.915 s]
[INFO] JLine JNA Terminal ................................. FAILURE [  0.905 s]
[INFO] JLine JANSI Terminal ............................... SKIPPED
[INFO] JLine Reader ....................................... SKIPPED
[INFO] JLine Groovy ....................................... SKIPPED
[INFO] JLine Builtins ..................................... SKIPPED
[INFO] JLine Style ........................................ SKIPPED
[INFO] JLine Bundle ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.434 s
[INFO] Finished at: 2020-04-06T19:51:14Z
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jline-terminal-jna: Compilation failure: Compilation failure: 
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/win/Kernel32.java:[22,30] error: cannot find symbol
[ERROR]   symbol:   method load(String,Class<Kernel32>,Map<String,Object>)
[ERROR]   location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/linux/LinuxNativePty.java:[29,52] error: cannot find symbol
[ERROR]   symbol:   method load(String,Class<CLibrary>)
[ERROR]   location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/linux/LinuxNativePty.java:[35,37] error: cannot find symbol
[ERROR]   symbol:   method load(String,Class<UtilLibrary>)
[ERROR]   location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/freebsd/FreeBsdNativePty.java:[29,52] error: cannot find symbol
[ERROR]   symbol:   method load(String,Class<CLibrary>)
[ERROR]   location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/freebsd/FreeBsdNativePty.java:[35,37] error: cannot find symbol
[ERROR]   symbol:   method load(String,Class<UtilLibrary>)
[ERROR]   location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/solaris/SolarisNativePty.java:[28,52] error: cannot find symbol
[ERROR]   symbol:   method load(String,Class<CLibrary>)
[ERROR]   location: class Native
[ERROR] /<<PKGBUILDDIR>>/terminal-jna/src/main/java/org/jline/terminal/impl/jna/osx/OsXNativePty.java:[29,52] error: cannot find symbol
[ERROR]   symbol:   method load(String,Class<CLibrary>)
[ERROR]   location: class Native
[ERROR] -> [Help 1]
[ERROR] 

What can be done for the same?

**Comment by mattirn** [comment]
You get errors `error: cannot find symbol` because you have a wrong version of jna library in your jline project.

JLine github project compiles without errors ;)
