### ISSUE TITLE
Jline is not working on Windows 10 with TERM=dumb environment variable

### ISSUE THREAD

**Issue by precoder** [jline/jline3#524]
Hello,

I had created an issue for the Apache Felix about the command line usage in here:
https://issues.apache.org/jira/browse/FELIX-6233
But as far as I understand it was more a Jline issue than a Felix issue.

It seems like if I set (which was the default value on the Windows installation I guess)
TERM=dumb
Felix gogo shell is not working (which is using JLine internally) but If I set 
TERM=windows
it is working as expected on my machine.

Another colleague has tried to reproduce the issue but on his machine, with different versions of Java, it seems to be working, you can see the discussion on the linked Felix Issue.

For now, I can set TERM=windows in environment properties and continue to work like this.
It seems like it is also used by Karaf etc (which also use gogo shell and Jline internally)
I also linked the Karaf issues on the link above.

I just want to know if setting TERM=windows is just a workaround until some bug is fixed
or is this the official way that it should be working?

Depending on your answer I can close the issue on the link above.

**Comment by mattirn** [comment]
If you set `TERM=dumb` you will obtain dumb terminal without advanced features. 
If the `TERM` variable is not set on Windows 10 you will obtain `windows-vtp` terminal with advanced features.
