### ISSUE TITLE
Cannot build Jline 3.14.1 : gpg: invalid option "--pinentry-mode"

### ISSUE THREAD

**Issue by dattasid** [jline/jline3#529]
Looks like 3.12.1 did not have the gpg dependency but it was introduced in 3.14 . How do I avoid this error or remove this dependency? Or how do I setup gpg correctly ?

**Comment by gnodet** [comment]
This should be run only during a release.  If that's not the case, there's a problem in the plugin configuration.  Are you trying to build **master** or the **3.14** tag ?

**Comment by dattasid** [comment]
I downloaded jline-parent-3.14.1.zip .
Then I run

./build rebuild

This worked for 12.1 . What additional steps should I take ?

I need the jars built.

**Comment by gnodet** [comment]
You could download them from maven central ?
   https://repo1.maven.org/maven2/org/jline/jline/3.14.1/

Alternatively, you can try building with `-Dgpg.skip=true` to skip the gpg signing.

**Comment by dattasid** [comment]
It worked, thanks!

I am on Enterprise Linux 7 which seems to be stuck in GnuPG 2.0 which does not have the --pinentry-mode option. It might help other people like me if you add this to the readme.

Where can I find a list of other options like gpg.skip ?

**Comment by gnodet** [comment]
Each maven plugin can be configured, sometimes with system properties, see http://maven.apache.org/plugins/maven-gpg-plugin/sign-mojo.html#skip in that particular case.
