### ISSUE TITLE
Simplified examples.

### ISSUE THREAD

**Issue by lscoughlin** [jline/jline3#537]
Can we get some simplified examples?

Right now, Example.java is huge and somewhat difficult to follow structure.

The API is a bit quirky and highly opinionated as it is... trying to unravel what all the bits do is proving more than a little challenging.

**Comment by mattirn** [comment]
I agree in Example has  remain also some outdated code. I will update it in near future.  

There are other three example JLine apps: [gogo](https://github.com/jline/jline3/blob/master/demo/src/main/java/org/jline/demo/Gogo.java), [groovy-repl](https://github.com/jline/jline3/blob/master/demo/src/main/java/org/jline/demo/Repl.java) and [graal](https://github.com/jline/jline3/blob/master/demo/src/main/java/org/jline/demo/Graal.java). If you are looking something very simple to start with I will add here also a minimal JLine repl example:
```
import java.io.IOException;

import org.jline.reader.EndOfFileException;
import org.jline.reader.LineReader;
import org.jline.reader.LineReaderBuilder;
import org.jline.reader.UserInterruptException;
import org.jline.reader.impl.DefaultParser;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;

public class SimpleExample {

    public static void main(String[] args) throws IOException {
        Terminal terminal = TerminalBuilder.builder().build();
        DefaultParser parser = new DefaultParser();
        LineReader reader = LineReaderBuilder.builder()
                .terminal(terminal)
                .parser(parser)
                .build();
        while (true) {
            try {
                String line = reader.readLine("prompt > ");
                System.out.println(line);
            } catch (UserInterruptException e) {
                // Ignore
            } catch (EndOfFileException e) {Minimal JLine repl example:
                return;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
```

**Comment by mattirn** [comment]
[Example.java](https://github.com/jline/jline3/blob/master/builtins/src/test/java/org/jline/example/Example.java) has been split in two.
Now widgets, auto suggestions and other advanced console features can be found at [Console.java](https://github.com/jline/jline3/blob/master/console/src/test/java/org/jline/example/Console.java)
