### ISSUE TITLE
Characters are getting omitted on editing a multiline command on Jline shell

### ISSUE THREAD

**Issue by prt95** [jline/jline3#544]
Hello,
I am using picocli to create a command line interface for my application and Picocli is using Jline 3.
I found below issue in Jline3 :
Type a long command (should take more than one line) on terminal. Now move the cursor to the first line of command and try to edit the command, the issue is that the characters of command starts getting omitted as you edit the command. To fix this you will need to maximize the command window so that given command gets sufficient space.

Given below is a long command which takes more than one line :
![image](https://user-images.githubusercontent.com/8886750/84000866-2385c280-a983-11ea-9b63-313b36b6f816.png)
On editing characters are getting omitted as shown in below image:
![image](https://user-images.githubusercontent.com/8886750/84000902-37312900-a983-11ea-855e-05f3a6c65ea0.png)
On maximizing terminal window issue gets fixed as shown in below image :
![image](https://user-images.githubusercontent.com/8886750/84000924-431ceb00-a983-11ea-9519-8ce3c4d2b1bd.png)

**Comment by mattirn** [comment]
Do you have [Jansi/JNA](https://github.com/jline/jline3#jansi-vs-jna) jar on your classpath?

**Comment by prt95** [comment]
Yes @mattirn jansi-1.18.jar is in my classpath.

**Comment by mattirn** [comment]
Which Windows version you are using?
Please, could you add in your code line:
```
System.out.println(terminal.getName() + ": " + terminal.getType());
```
after you have created JLine terminal. What does it output?

**Comment by prt95** [comment]
Here is the system details. Windows Server 2016 with version 1607
![image](https://user-images.githubusercontent.com/8886750/84242216-2832ae00-ab1e-11ea-935a-6a15baf9a3ba.png)

The output is below:
JLine terminal: windows-vtp

**Comment by prt95** [comment]
Window Server 2016 with version 1607 .

The output is : 
 JLine terminal: windows-vtp

**Comment by prt95** [comment]
@mattirn 
Tab completion is working. 
Setting TERM to windows solved the problem.

Thanks :)

**Comment by mattirn** [comment]
Updated [Terminals](https://github.com/jline/jline3/wiki/Terminals#system-terminals) wiki.
