### ISSUE TITLE
Disable completion if candidate was chosen

### ISSUE THREAD

**Issue by strogiyotec** [jline/jline3#549]
Good day. I have the following problem. This is my code.
```
final LineReaderImpl reader = new LineReaderImpl(TerminalBuilder.terminal());
            reader.setCompleter(new StringsCompleter("hello"));
            final String s = reader.readLine(">");
            System.out.println(s);
            return;
```
As you can see I have single candidate for completion ("hello").  Every time I press TAB ,the new instance of hello is appended to the end of my prompt .
```
>hello hello hello
```
What I want is when I press TAB then "hello" will be appended to prompt but when I press TAB again nothing will happen. Is it possible to do it ? 
Version is `3.15.0`

**Comment by mattirn** [comment]
Creating a completer using [ArgumentCompleter](https://github.com/jline/jline3/wiki/Completion#argumentcompleter) as
```
completer = new ArgumentCompleter(new StringsCompleter("hello"), NullCompleter.INSTANCE);
```
should resolve your problem.

**Comment by strogiyotec** [comment]
@mattirn thank you it solved my problem
