### ISSUE TITLE
System terminal on Windows

### ISSUE THREAD

**Issue by dprutean** [jline/jline3#556]
Running Jline on Windows I get this message:
"Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)"

The completion using TAB does not work.
I saw a method 
```
TerminalBuilder.builder().system(true)
```
What is this method for ( system(true) )? I found nothing in the documentation.

**Comment by mattirn** [comment]
JLine [Terminals](https://github.com/jline/jline3/wiki/Terminals) and in particular TerminalBuilder building options are documented [here](https://github.com/jline/jline3/wiki/Terminals#terminal-building-options). 
Note that on the Windows platform you need to have either Jansi or JNA library in your classpath along with the `jline-terminal-jansi` or `jline-terminal-jna` jar. Failing to do so will create a dumb terminal with no advanced capabilities ([README](https://github.com/jline/jline3#jansi-vs-jna))

**Comment by mattirn** [comment]
Improved [Terminals](https://github.com/jline/jline3/wiki/Terminals) wiki page.
