### ISSUE TITLE
UserInterruptException not thrown on ctrl-C

### ISSUE THREAD

**Issue by electrum** [jline/jline3#56]
We've been using jline2 for the Presto CLI and everyone loves it. Just noticed the new jline3 project and started playing with it. Looks awesome!

I tried a basic example:
```java
Terminal terminal = TerminalBuilder.terminal();
LineReader reader = LineReaderBuilder.builder().terminal(terminal).build();
while (true) {
    try {
        reader.readLine("> ");
    }
    catch (UserInterruptException e) {
        System.out.println("Interrupted: " + e.getPartialLine());
    }
    catch (EndOfFileException e) {
        break;
    }
}
```

On Mac Terminal, pressing ctrl-C causes the program to exit after a short delay (~1 second). I tried catching `Throwable` and a finally block, but neither get called, so the `readLine()` method is causing the JVM to exit.

`LineReaderImpl` in response to `state == INTERRUPT`, but state is never set to that (that enum value isn't used elsewhere).

I sent the original patch for `UserInterruptException` in jline2 and it worked by disabling interrupt handling for the terminal, allowing the key to be read as normal input. jline3 seems to be handling it by catching `SIGINT`. I wonder if that's less reliable? Were there problems with the other method?

**Comment by gnodet** [comment]
The signal support is disabled by default.
Try building the terminal with the following:
```
        Terminal terminal = TerminalBuilder.builder()
                .nativeSignals(true)
                .signalHandler(Terminal.SignalHandler.SIG_IGN)
                .build();
```

**Comment by electrum** [comment]
Thanks, that works! However, there is a problem with `TSTP` handling. Hitting ctrl-Z crashes the JVM with SIGSEGV (happens every time).
