### ISSUE TITLE
ANSI escape codes don't work on the terminal that comes with git for windows

### ISSUE THREAD

**Issue by martijnhoekstra** [jline/jline3#560]
ANSI escape codes aren't processed in the terminal that comes with git for windows since git for windows 2.27.0.

Reported against git for windows on https://github.com/git-for-windows/git/issues/2661#issuecomment-667613335

**Comment by mattirn** [comment]
I have tested JLine demo app with git for Windows version 2.29.2.windows.2 (mintty 3.4.2). I have not found any other anomalies than 'Ctrl-C + return crash', #590.
