### ISSUE TITLE
Problems with readLine on Windows 7 cmd.

### ISSUE THREAD

**Issue by smalirizvi** [jline/jline3#561]
I have been working on a Linux machine and everything works great. As soon as I tried to run it on Windows 7 this started to create problems as the line reader is not picking up all keystrokes. I am on the latest version of JLine.

**Comment by morris821028** [comment]
Did you add jna.jar or jansi.jar into classpath? If you want advanced usage, must pick one of these .jar to make tab-complete work on Windows.

**Comment by mattirn** [comment]
Close for inactivity.

**Comment by gnodet** [comment]
Could it be similar to https://github.com/fusesource/jansi/issues/190 ?
