### ISSUE TITLE
TailTipWidget Enabling by default

### ISSUE THREAD

**Issue by rnc** [jline/jline3#571]
I have followed https://github.com/jline/jline3/wiki/Autosuggestions (which has 
```
TailTipWidgets tailtipWidgets = new TailTipWidgets(reader, tailTips, 5, TipType.COMPLETER);
// Enable autosuggestions 
tailtipWidgets.enable();
```
 ) but I get ` Widgets can only be called during a readLine call`.

For code like 
```
                new TailTipWidgets(reader, systemRegistry::commandDescription, 5, TailTipWidgets.TipType.COMPLETER);
                KeyMap<Binding> keyMap = reader.getKeyMaps().get("main");
                keyMap.bind(new Reference("tailtip-toggle"), KeyMap.alt("s"));
```
what is the correct way of enabling it by default (so the user doesn't have to press Alt-s to enable it)

**Comment by mattirn** [comment]
It should work... I have modified Groovy REPL so that tailtip widgets are enabled https://github.com/mattirn/jline3/tree/widget-enable, see the last commit https://github.com/mattirn/jline3/commit/c1a7b29d76d78b66241910ba92dc3b5fb4448431.

**Comment by rnc** [comment]
> It should work... I have modified Groovy REPL so that tailtip widgets are enabled [https://github.com/mattirn/jline3/tree/widget-enable](https://github.com/mattirn/jline3/tree/widget-enable?rgh-link-date=2020-09-16T17%3A02%3A45Z), see the last commit [mattirn@c1a7b29](https://github.com/mattirn/jline3/commit/c1a7b29d76d78b66241910ba92dc3b5fb4448431). In my PC it works as expected.

Thanks for the reply! 

I guess I must be missing something in my configuration. I am using jline via picocli (which brings in org.jline:jline:jar:3.15.0 ). Maybe that is affecting it / making a difference? 

The code is https://github.com/rnc/bacon/blob/JLINE3/cli/src/main/java/org/jboss/pnc/bacon/cli/App.java#L156 pushed to branch JLINE3 and running via the produced shaded jar gives:
```
java -jar cli/target/bacon.jar
Exception in thread "main" java.lang.IllegalStateException: Widgets can only be called during a `readLine` call
        at org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:832)
        at org.jline.builtins.Widgets.callWidget(Widgets.java:91)
        at org.jline.builtins.Widgets$TailTipWidgets.toggleKeyBindings(Widgets.java:1068)
        at org.jline.builtins.Widgets$TailTipWidgets.enable(Widgets.java:834)
        at org.jboss.pnc.bacon.cli.App.run(App.java:156)
        at org.jboss.pnc.bacon.cli.App.main(App.java:73)
```

**Comment by mattirn** [comment]
Yes, you are right! There is a bug in version 3.15.0 which has been fixed in 3.16.0, see commits
* [`fcac9694`](https://github.com/jline/jline3/commit/fcac969406439b8c0d32bf01fbb30d1510a6f055) Console example: fixed widgets enabling/disabling, step II
* [`1aa0bda2`](https://github.com/jline/jline3/commit/1aa0bda27f7db310899482a8d4540b9a9abc5fec) Console example: fixed widgets enabling/disabling

I'm afraid `picocli-shell-jline3` requires some minor changes to use JLine version 3.16.0, see https://github.com/jline/jline3/issues/551

**Comment by rnc** [comment]
@mattirn Ah ha, I was cross-checking the released versions and that was going to be my next guess after you said it should work. I think the appropriate thing to do would be enter a ticket for picocli. Thanks for your help!

**Comment by rnc** [comment]
I've just given it a go and added 
 ```     
 <dependency>
  <groupId>org.jline</groupId>
  <artifactId>jline-console</artifactId>
</dependency>
```
 as an extra dependency and it works. Thanks!
