### ISSUE TITLE
Ansi capabilities don't contain delete, home, or insert

### ISSUE THREAD

**Issue by eatkins** [jline/jline3#578]
When using a custom version of sbt on windows that uses the latest jline, none of the delete, home or insert keys work. I was able to fix it with a workaround (https://github.com/sbt/sbt/pull/5874/commits/036fef33832ae672f13c394f39a0ed1b5040d4ec) but I'm wondering if maybe these keys should be added to the ansi.caps file.

**Comment by mattirn** [comment]
I have not been able to reproduce the problem using JLine demo and Windows CMD. I have tested on Microsoft Windows [Version 10.0.18362.1049]. Using `ansi` terminal all the three keys you mentioned are working expect 'delete'. When using `windows` or `windows-vtp` terminal type all the three keys are working correctly.

```
jline3-master\demo>set TERM=ansi
jline3-master\demo>jline-repl.bat jna
```

**Comment by eatkins** [comment]
sbt does a lot of custom stuff so I don't doubt that it doesn't reproduce in every use case. I am testing on a vm and I actually don't have home or insert keys so I have only truly tested forward delete. When I ssh to a windows vm, the term is reported as screen-256color, key_dc is in the screen-256color.caps and forward delete does work. If I run on the actual vm instance, the term is null so it falls back to ansi and forward work does not work. That was why I had to add the workaround in the sbt commit in my initial comment. I am almost certain that if ansi.caps included a value for key_dc, then I wouldn't have needed a workaround. I just double checked the ansi.caps and they do include insert, but not delete or home.

**Comment by mattirn** [comment]
Ah ok. So when you run on the VM instance you are creating your terminal using JLine `TerminalBuilder` and since you have terminal `type=null` you end up having ansi terminal here [AbstractTerminal.java#L208](https://github.com/jline/jline3/blob/ccf838c0e39194a093a989eb06bc1ac105bdd949/terminal/src/main/java/org/jline/terminal/impl/AbstractTerminal.java#L208). I guess for some reason you cannot set your terminal type on VM instance for example using system property `org.jline.terminal.type`.

Yes, I think too that adding the key values in ansi.caps file would resolve your problem. As far as I know all the caps files are produced using output of `infocmp` command without introducing additional modifications.  By the way ansi.caps do include also 'home'.

**Comment by eatkins** [comment]
>  I guess for some reason you cannot set your terminal type on VM instance for example using system property org.jline.terminal.type

I don't actually use windows and am a maintainer of sbt who upgraded it from jline 2 to jline 3. This issue came up because a user reported that those keys weren't working with our latest release. On posix platforms, it seems the TERM environment variable is set but I don't necessarily want to automatically set the `org.jline.terminal.type` property if it isn't because I don't know enough about the various windows environments. We don't want our users to have to set the property themselves since that would be a bad out of box experience. This isn't an urgent problem for us though because of the workaround I added. But I figured that someone else might run into this issue in the future so I reported it.

It might not make sense to change ansi.caps if it is autogenerated, but maybe there could/should be a different fallback for windows in AbstractTerminal?

**Comment by mattirn** [comment]
> It might not make sense to change ansi.caps if it is autogenerated, but maybe there could/should be a different fallback for windows in AbstractTerminal?

I do not think so... We cannot test there OS because the terminal might be used in remote connection.
OS can be tested only when creating [System Terminals](https://github.com/jline/jline3/wiki/Terminals#system-terminals): [TerminalBuilder.java#L318-L444](https://github.com/jline/jline3/blob/ce3c93081f359e9dc207f63f6d3baff9a9cc400d/terminal/src/main/java/org/jline/terminal/TerminalBuilder.java#L318-L444).

I think you are using a [Virtual Terminal](https://github.com/jline/jline3/wiki/Terminals#virtual-terminals) on VM instance. In this case terminal information need to be passed to JLine terminal builder or otherwise you will get ansi terminal. We could add mappings to ansi.caps but I do not think it would resolve the problem generally and nonetheless you will obtain rather bad working terminal. Added mappings might also not work in a non Windows terminals.

**Comment by eatkins** [comment]
What about making the default terminal capabilities an overridable method in AbstractTerminal? Then AbstractWindowsTerminal could set it to windows.caps or whatever makes the most sense rather than ansi.caps.

**Comment by mattirn** [comment]
Yes, to have possibility to change the fallback terminal could probably make sense. 

If you are creating a virtual terminal then you either have `PosixPtyTerminal` (JNA or Jansi in classpath) or `ExternalTerminal`, see [TerminalBuilder.java#L446-L462](https://github.com/jline/jline3/blob/ce3c93081f359e9dc207f63f6d3baff9a9cc400d/terminal/src/main/java/org/jline/terminal/TerminalBuilder.java#L446-L462). Do not know how windows.caps would work here or how well these terminals works in windows.
@gnodet, can you confirm my analysis....

**Comment by mattirn** [comment]
Original ticket of the problem: https://github.com/sbt/sbt/issues/5828

**Comment by gnodet** [comment]
@eatkins your recent commit https://github.com/sbt/sbt/commit/410a8dd4b1263db257b2b11e0145dd79f9c34b26 switches the type from harcoded `ansi` to something more meaningful.  Does it change the behavior ? I think this should cause the terminal to use `windows` somehow instead of `ansi` which should solve the problem without your specific fix for the windows keys.

Also, fwiw, in your original fix, there's a typo for the end key, it should be `\u001B[4~` and not `\u001B[4!`

**Comment by eatkins** [comment]
@gnodet that is correct. I don't personally need a fix in jline 3 because I was able to work around it in sbt but I thought it was worth opening because I had to make the workaround in the first place. The issue that I see it is that the following:
```java
System.err.println(TerminalBuilder.system(true).build().getStringCapability(Capability.key_dc))
```
will print null on windows in many terminals. I trust that in many applications jline still works correctly but it didn't in sbt.

Thanks for pointing out the typo https://github.com/sbt/sbt/pull/5906

**Comment by eatkins** [comment]
Our initial pre-release was actually using a mixture of jline 2 and jline 3. We were effectively passing in the wrapped input stream from jline 2 into the jline 3 terminal that we constructed for the line reader. jline 2 had different logic for replacing the system escape codes with ansi escape codes which was why those keys didn't work initially. For whatever reason, using the system terminal's input stream did not work for our purposes (no key presses were detected), so I wrote a custom input stream, https://github.com/sbt/sbt/blob/develop/internal/util-logging/src/main/scala/sbt/internal/util/WindowsInputStream.scala. It is kind of a hybrid of the jline 2 windows input stream and the jline 3 `AbstractWindowsTerminal.processKeyEvent` function that manually uses jansi to read from the windows console input translates windows escape codes to jline capability strings using a variant of `AbstractWindowsTerminal.getEscapeSequence`. Even after this change, some keys still weren't working because instead of calling, for example, `getRawSequence(InfoCmp.Capability.key_dc)` as jline 3 does in `getEscapeSequence`, we call `Terminal.getStringCapability(InfoCmp.Capability.key_dc)`. That was still returning null when windows was using the ansi.caps file so I had to manually change it "\u001B[3~" if the system terminal returned null. If ansi.caps had an entry for key_dc, then I could have just copied the logic from `AbstractWindowsTerminal.getEscapeSequence` with no workaround.

No doubt this is very much not using the library as intended but I thought the backstory would be helpful.

**Comment by mattirn** [comment]
In a given JVM there can be only one system terminal. If you try to create an other system terminal  you will obtain dumb terminal instead. 
```
            Terminal terminal = TerminalBuilder.builder().build();
            System.err.println(terminal.getStringCapability(Capability.key_dc));
            System.err.println(TerminalBuilder.builder().system(true).build().getStringCapability(Capability.key_dc));
```
In Linux xterm the code above will output
\E[3~
null

I think an exception should be thrown if you try to build second system terminal.

**Comment by eatkins** [comment]
I understand that you can't make two system terminals. My point is that if you make a single system terminal on windows that the you can get null for `terminal.getStringCapability(Capability.dc)` when running it in the powershell app.

**Comment by eatkins** [comment]
In sbt, we make one system terminal for the whole jvm session but we make many instances of `AbstractTerminal` that delegate some methods to the system terminal such as `getStringCapability`. We do not use the input stream for the system terminal for reasons specific to our application which is why we need to make custom instance of `AbstractTerminal`.

**Comment by mattirn** [comment]
I'm not able to reproduce the problem in PowerShell 7.0.3. `terminal.getStringCapability(Capability.key_dc)` returns \E[3~. I have been using windows-vtp terminal type set by the Terminal builder.

**Comment by eatkins** [comment]
On my computer, when running sbt `System.getenv("TERM")` returns null as well as `System.getProperty("org.jline.terminal.type")` so we fall back to ansi. This is why I was thinking it would be a good idea to change AbstractTerminal to have a method like
```java
protected String defaultFallbackType() {
  return "ansi"
}
```
but in `AbstractWindowsTerminal` it could be
```java
@Override
protected String defaultFallbackType() {
  return "windows-vtp"
}
```

**Comment by mattirn** [comment]
But if you are using [JansiWinSysTerminal.java](https://github.com/jline/jline3/blob/ce3c93081f359e9dc207f63f6d3baff9a9cc400d/terminal-jansi/src/main/java/org/jline/terminal/impl/jansi/win/JansiWinSysTerminal.java#L38-L65) (or JnaWinSysTerminal) to create your Windows system terminal they will detect the correct terminal type for you. You will never get an ansi terminal neither when you have not set `TERM` or `org.jline.terminal.type` system property.
I have never use Windows in virtualbox but I suppose that it should work like 'normal' Windows.

**Comment by eatkins** [comment]
I was able to confirm your results. Somehow I convinced myself we were hitting the ansi fallback in AbstractTerminal but I was mistaken. Sorry for the confusion.
