### ISSUE TITLE
Does Jline have any option to do list view of autocomplete suggestions?

### ISSUE THREAD

**Issue by parrotcar00** [jline/jline3#582]
I just saw Python prompt toolkit: https://github.com/prompt-toolkit/python-prompt-toolkit which does a list view of autocomplete suggestions and was wondering if I could do something similar with Jline? I was looking for a Java library instead of a python one to do this.

**Comment by mattirn** [comment]
Yes, you can do something similar using [TailTipWidgets](https://github.com/jline/jline3/wiki/Autosuggestions#tailtipwidgets).

There is a test implementation you can play with [Console](https://github.com/jline/jline3/blob/master/console/src/test/java/org/jline/example/Console.java) and a couple of demo apps to start from

1.  [Groovy REPL](https://github.com/jline/jline3/blob/master/demo/src/main/java/org/jline/demo/Repl.java)
Uses `JLineCommandRegistry`. You can create commands that have `Object` parameters and returns `Object` and you can use scripts within your app. Wiki pages: [Groovy language REPL](https://github.com/jline/jline3/wiki/Groovy-language-REPL), [REPL Console](https://github.com/jline/jline3/wiki/REPL-Console) and [REPL Console Customization](https://github.com/jline/jline3/wiki/REPL-Console-Customization). Updated [asciinema demo](https://asciinema.org/a/363278?t=15&speed=2).
2. [Graal](https://github.com/jline/jline3/blob/master/demo/src/main/java/org/jline/demo/Graal.java)
Uses `JLineCommandRegistry` without Groovy, console scripts and variables.
3. [Picocli](https://github.com/remkop/picocli/tree/master/picocli-shell-jline3)

**Comment by mattirn** [comment]
Added JLine option `AUTO_MENU_LIST`  to show suggestions  below the field to be completed. Menu colours can be customised using JLine variables `DEFAULT_COMPLETION_COLOR_STARTING`, `DEFAULT_COMPLETION_COLOR_DESCRIPTION` and `DEFAULT_COMPLETION_LIST_BACKGROUND_COLOR`

![auto-menu-list](https://user-images.githubusercontent.com/6079480/95102780-18c21b00-0734-11eb-8c42-474ad4e15716.png)

**Comment by parrotcar00** [comment]
Thanks @mattirn! , this looks exactly what I was looking for.
