### ISSUE TITLE
Support JColor as and alternative to Jansi

### ISSUE THREAD

**Issue by sirinath** [jline/jline3#588]
Can [JColor](https://github.com/dialex/JColor) be supported as an alternative to Jansi.

**Comment by gnodet** [comment]
We don't really use the colouring part of Jansi, JLine uses the `AttributedString`.  What we use in Jansi is the low level functions provided by the `CLibrary` and `Kernel32` classes from Jansi.
In addition, `JColor` does not seem to care about the terminal capabilities, so I don't think we can leverage it.
