### ISSUE TITLE
Remove \ in completer

### ISSUE THREAD

**Issue by Evynglais** [jline/jline3#596]
Hi,

I'm trying to complete a phrase; i.e. "Thread Allocation Count", and the completer adds a slash between when TAB completing, i.e. you'll have "Thread\ Allocation". This doesn't affect how the completer works, so is not an issue, just a request for help, I'm just wondering how I can edit this to not display a "\ ".

Thank you
Evynglais

**Comment by mattirn** [comment]
If you are using `DefaultParser` you should create it as
```
DefaultParser parser = new DefaultParser();
parser.setEscapeChars(new char[]{});
```

then spaces won't be escaped.
