### ISSUE TITLE
Show auto-suggestions when the reader starts reading

### ISSUE THREAD

**Issue by Evynglais** [jline/jline3#598]
Hi,

Is it possible to auto-show the tailtip when the reader starts reading? At the moment it requires a char/TAB/some user interaction to display, but I'd like it to display automatically.

Thanks
Evyn

**Comment by mattirn** [comment]
See [Autosuggestions](https://github.com/jline/jline3/wiki/Autosuggestions) 

```
TailTipWidgets tailtipWidgets = new TailTipWidgets(reader, tailTips, 5, TipType.COMPLETER);
// Enable autosuggestions 
tailtipWidgets.enable();
```

**Comment by mattirn** [comment]
Added JLine variable `suggestions-min-buffer-size`. Set `suggestions-min-buffer-size = 0` to display suggestions when the reader start reading.
```
groovy-repl> setvar suggestions-min-buffer-size 0
groovy-repl> 
!               del             hello2          nano            prnt            sort            ttop
alias           distinct        help            null            select          testkey         unalias
class           doc             history         objarg          setopt          tget            unsetopt
clear           exit            import          pipe            setvar          to              widget
completerTest   groovy          keymap          print           show            tput            xargs
def             hello           less            println         slurp           trace
```

**Comment by Evynglais** [comment]
> Added JLine variable `suggestions-min-buffer-size`. Set `suggestions-min-buffer-size = 0` to display suggestions when the reader start reading.
> 
> ```
> groovy-repl> setvar suggestions-min-buffer-size 0
> groovy-repl> 
> !               del             hello2          nano            prnt            sort            ttop
> alias           distinct        help            null            select          testkey         unalias
> class           doc             history         objarg          setopt          tget            unsetopt
> clear           exit            import          pipe            setvar          to              widget
> completerTest   groovy          keymap          print           show            tput            xargs
> def             hello           less            println         slurp           trace
> ```

Exactly what I was looking for. Thanks
