### ISSUE TITLE
Problems with cursor (arrow) keys and CTRL+anything in jline3

### ISSUE THREAD

**Issue by hypfvieh** [jline/jline3#60]
I try to use jLine (3.1.2) as shell in apache's sshd-core.
So I use TerminalBuilder/LineReaderBuilder to setup jLine as seen in the documentation.

Most of the stuff I would like to do is working. 
But some features I would like to use are not working at all.

It already was a long way to get CTRL+C and CTRL+D working, as it seems like ControlChar.VEOF and ControlChar.VINTR are undefined as default (-1).

So pressing e.g. CTRL+C resulted in a unprintable character which int representation was 3.
I fixed that problem by using setControlChar(ControlChar.VINTR, 3) on the attributes provided by TerminalBuilder.
Same thing goes for CTRL+D (which sends a character with id 4).

Now I'm still struggling with the usage of the cursor-keys (to e.g. use the history).

When pressing any of the cursor keys,  I only get 'oA' or 'oB' etc. depending on which cursor key I used.

Is there any option I have enable to get the cursor keys working?

btw. using jLine 2 is working in my setup, but it messes up with line-feed/carriage return...

Sample code:
```
    Attributes termAttribs = new Attributes();
    // enable output processing (required for all output flags)
    termAttribs.setOutputFlag(OutputFlag.OPOST, true);
    // map newline to carriage return + newline
    termAttribs.setOutputFlag(OutputFlag.ONLCR, true);

    // enable signals (for CTRL+C usage)
    termAttribs.setLocalFlag(LocalFlag.ISIG, true);
    // print control chars as '^X' (e.g. ^C for CTRL+C)
    termAttribs.setLocalFlag(LocalFlag.ECHOCTL, true);

    // enable CTRL+D shortcut
    termAttribs.setControlChar(ControlChar.VEOF, 4);
    // enable CTRL+C shortcut
    termAttribs.setControlChar(ControlChar.VINTR, 3);

    terminal = TerminalBuilder.builder()
            .system(false)
            .streams(getInStream(), getOutStream())
            .signalHandler(Terminal.SignalHandler.SIG_IGN)
            .nativeSignals(true)
            .attributes(termAttribs).build();

    reader = LineReaderBuilder.builder()
            .terminal(terminal)
            .build();

    reader.unsetOpt(Option.INSERT_TAB); // disable tab insertion when no letter was given (allows using tab to list all commands)

    // output welcome banner on ssh session startup
    if ((shellGreeter != null) && !shellGreeter.isEmpty()) {
        for (String line : shellGreeter) {
            terminal.writer().println(line);
        }
        terminal.flush();
    }

    String readline;
    while ((readline = reader.readLine(prompt)) != null) {
        handleUserInput(readline); // handles the input, executes what ever command
    }
```

**Comment by gnodet** [comment]
You can look at a working integration at the following location: https://github.com/apache/felix/tree/trunk/gogo/jline/src/test/java/org/apache/felix/gogo/jline/ssh

In particular, look at the terminal setup: https://github.com/apache/felix/blob/trunk/gogo/jline/src/test/java/org/apache/felix/gogo/jline/ssh/ShellFactoryImpl.java#L135-L234

In addition, you need to make sure the client terminal is put into raw mode, as that's what the ssh server side expects, but a native ssh client should do that already.

**Comment by gnodet** [comment]
In your case, the cursor problems may come from the terminal type which is set by the following line:
  https://github.com/apache/felix/blob/trunk/gogo/jline/src/test/java/org/apache/felix/gogo/jline/ssh/ShellFactoryImpl.java#L137

I should bring back the code above for ssh / telnet integration into a new jline module.

**Comment by hypfvieh** [comment]
Thank you so much! 

The sample you provided was the important part. 
Now all keys are working like they should!
