### ISSUE TITLE
Display command is incorrect when use here document

### ISSUE THREAD

**Issue by toanvan** [jline/jline3#607]
I copy and paste some command as below:

```
root@localhost# api_cli << EOS
DROP TABLE myIntervalPartition2;
DROP TABLE employees;
CREATE TABLE myIntervalPartition2 (
   key INTEGER PRIMARY KEY,
   value STRING
) PARTITION BY RANGE (key) EVERY (20000);
CREATE TABLE employees (
   id INTEGER,
   first_name STRING,
   last_name STRING,
   age INTEGER,
   department STRING,
   enrollment_period DOUBLE
);
EOS
```
After copy paste I saw console display as below:
```
 app_cli>DROP TABLE myIntervalPartition2;
 app_cli>DROP TABLE employees;
 app_cli>CREATE TABLE myIntervalPartition2 (
>    key INTEGER PRIMARY KEY,
>    value STRING
> ); PARTITION BY RANGE (key) EVERY (20000);
app_cli> CREATE TABLE employees (
>    id INTEGER,
>    first_name STRING,
>    last_name STRING,
>    age INTEGER,
>    department STRING,
>    enrollment_period DOUBLE
> ) PARTITION BY RANGE (key) EVERY (20000);                                       
```

The sql 2nd we have some character from sql 1st. It seem related to autosuggest  from sql 1st. Please help me check this case

**Comment by mattirn** [comment]
In order to fix the incorrect command display you can set `LineReader` option `BRACKETED_PASTE = true` (default).

If you do not like how commands are pasted to your app when `BRACKETED_PASTE = true` you can create a widget which toggle between 'copy mode' (auto-suggestions disabled, `BRACKETED_PASTE = false`) and 'auto-suggestion mode' (auto-suggestions enabled, `BRACKETED_PASTE = true`) and bind it to a key.

**Comment by toanvan** [comment]
Thank your comment. I'm sorry. I described issue again. It's just issues when we use here document. Please help me check again.

**Comment by mattirn** [comment]
Then you should not enable auto-suggestions widgets at application startup but create a key binding for it (for example alt-s) so that you can enable it easily
```
AutosuggestionWidgets autosuggestionWidgets = new AutosuggestionWidgets(reader);
KeyMap<Binding> keyMap = reader.getKeyMaps().get("main");
keyMap.bind(new Reference('autosuggest-toggle', KeyMap.alt("s"));
```

**Comment by toanvan** [comment]
But I have a question: "How to check dumb terminal ?"
