### ISSUE TITLE
Document how I/O error in LineReader.readLine is reported

### ISSUE THREAD

**Issue by stepancheg** [jline/jline3#608]
`LineReader.readLine` throws:
* `UserInterruptException` If the call was interrupted by the user
* `EndOfFileException` If the end of the input stream was reached
* and function never returns null

How `readLine` returns an error? E. g. when stdin is a file, and file I/O results in error? I guess it will return `EndOfFileException`, but would be good if it was in javadoc.

**Comment by gnodet** [comment]
If an I/O exception occurs, an `IOError` will be thrown by `LineReader.readLine()`.
But yes, improving the javadoc would be good.
