### ISSUE TITLE
Parser cancels Completer

### ISSUE THREAD

**Issue by pabloa** [jline/jline3#61]
I wrote a parser that checks if the line finishes with ';' and throws an error if it is not finishes like that

```java
        if(!line.trim().endsWith(";")) {
            System.out.println("missing ;!");
            throw new EOFError(-1, -1, "Missing semicolon (;)", ";");
        }
```

I am writing an editor for SQL sentences using JLine3. The editor should support multiline sentences separated by ';'. I am following your suggestions about multiline support on ticket #36 

At the same time I wrote a completer that would suggest SQL keywords.

It seems there is a conflict when the parser throws an error. When this happens, the completer never is queried so no suggestions are done to the user.

Example:

If user writes:

```sql
SELECT * FROM table
```

and then press tab, the parser throws and EOFError because the sentence did not finish with ';'. Parser does not know the user pressed <tab> key so it just checks if the sentence ends with a ';'...

In the #parse() method I cannot say if user pressed <tab> key looking for suggestions. So parser cannot say if the ';' is missing or the user did not finish to write the SQL query (perhaps he/she pressed <tab> key and he/she looking for autocomplete).

I am using Jline3 3.1.2 and it seems the issue happens in LineReaderImpl.java

```java
        // Parse the command line and find completion candidates
        List<Candidate> candidates = new ArrayList<>();
        ParsedLine line;
        try {
            line = parser.parse(buf.toString(), buf.cursor(), ParseContext.COMPLETE);  // <-- EOFError() throwes here and execution goes to the catch section. Parser cannot say if <tab> key was pressed.
            if (completer != null) {
                completer.complete(this, line, candidates);
            }
        } catch (Exception e) {
            return false;
        }
```

No sure if this is a bug or I am writing a wrong parser. If parser has information about user pressing <tab> key, it could avoid throwing an exception.

Any suggestion?

**Comment by gnodet** [comment]
Actually, I think you can ;-)
Have a look at the [ParserContext|https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/Parser.java#L19-L37] parameter given to the parser.

**Comment by pabloa** [comment]
Excellent. It worked! :+1: 
Thank you
