### ISSUE TITLE
Expose `clearScreen` on `LineReader`

### ISSUE THREAD

**Issue by sualeh** [jline/jline3#610]
Expose `clearScreen` on `LineReader` so that it is generally useful. Or, implement it on `Terminal` - if that makes more sense.

**Comment by gnodet** [comment]
You could use
```
lineReader.callWidget(LineReader.CLEAR_SCREEN);
```

**Comment by sualeh** [comment]
@gnodet - thanks - let me try that.

**Comment by sualeh** [comment]
@gnodet - I get an exception: Widgets can only be called during a `readLine` call

**Comment by mattirn** [comment]
In general I think that we should not expose methods (neither in `LineReaderImpl`) that implements widgets but they should be executed by using `callWidget()` method. Maybe we can implement a method `executeWidget()` that could be used outside of `readerLine` call to invoke widgets:

```
    public void executeWidget(String name) {
        String keyseq = alt(ctrl('W'));
        getKeyMaps().get(LineReader.MAIN).bind(new Reference(name), keyseq);
        runMacro(keyseq);
    }
```

**Comment by sualeh** [comment]
Thanks. If you could do that, it would be great. I know too little about jline3 to help with a PR.

**Comment by gnodet** [comment]
@sualeh the `ReadLineImpl.clearScreen()` aims at cleaning and redrawing the screen during a `readLine()` call.  if you simply want to clear the screen, you can simply call
```
terminal.puts(Capability.clear_screen);
```

**Comment by sualeh** [comment]
Thanks, @gnodet
