### ISSUE TITLE
JLine3 should not allow building a system terminal if input *or* output is not a tty

### ISSUE THREAD

**Issue by gnodet** [jline/jline3#612]

**Comment by gnodet** [comment]
Actually, this may go against https://github.com/jline/jline3/issues/298, so not sure

**Comment by boxleytw** [comment]
Java does not have a pleasant means to determine if STDIN or STDOUT are ttys.  For example, a program using JLine has difficulty with:
```shell
$ ./a-program  # should read from console, and do all the amazing things which JLine provides
$ blah-blah | ./a-program  # should read from the pipe, and _not_ do fancy input magic
$ ./a-program >./some-file  # should write to the file, and _not_ do fancy output magic
```
One could try `System.console() != null`, and choose to not call JLine, however this puts the burden on the app code writer to get this right.  Nicer would be for JLine to handle the situation and "do the right thing".

**Comment by mattirn** [comment]
Fixed in commit https://github.com/jline/jline3/commit/2ec403f745d31810e5036f4b9e9aa038bc5b5606
