### ISSUE TITLE
Tab completion loses groups when tabbing (3.17 regression)

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#613]
In JLine `3.16.0` I can keep pressing tab to iterate through my options as shown.  Notice I'm grouping the completion candidates into groups.

![image](https://user-images.githubusercontent.com/584009/101227964-5b826f80-365f-11eb-9ad2-a18a0790a45a.png)

However, in `3.17.1` the groups display initially like above when I press tab, but when I press tab subsequent times to begin toggling through the options, the screen redraws without any of the groups.

![image](https://user-images.githubusercontent.com/584009/101228038-9a182a00-365f-11eb-938d-2c4412ae07a8.png)

This regression remains in the `3.17.2-SNAPSHOT` build.

**Comment by bdw429s** [comment]
cc/ @mattirn

**Comment by mattirn** [comment]
Navigating grouped candidates has been disabled in #580.
I can add JLine option to preserve the old behaviour.

**Comment by bdw429s** [comment]
@mattirn Wait, what?  Completion groups are awesome!  Why would you disabled them? My console app regularly has 3 or 4 different groups for all the possible completion candidates and I'd hate to see that functionality go away as it really helps organize what's on the screen.  

![image](https://user-images.githubusercontent.com/584009/101258450-2c641080-36e8-11eb-9ba3-f0523e27a121.png)

Without the nice, clear grouping in the UI, the same list is just a jumbled mess

![image](https://user-images.githubusercontent.com/584009/101258503-7f3dc800-36e8-11eb-8b37-fb43c2392b3f.png)

I'm concerned about features like this being dropped in a minor version release without even having any conversation on the JLine mailing list about it.
