### ISSUE TITLE
Use style instead of colours for the completion list

### ISSUE THREAD

**Issue by gnodet** [jline/jline3#617]

**Comment by gnodet** [comment]
The style strings should be final and not changed after being converted to a style.
So instead of 
```
        if (menuList) {
            return AttributedStyle.DEFAULT.background(getCompletionListBackgroundColor());
        }
        return AttributedStyle.DEFAULT.backgroundDefault();
```
I think we should duplicate the styles names and have `COMPLETION_STYLE_LIST_GROUP` in addition of `COMPLETION_STYLE_GROUP` for example.

@mattirn  Thoughts ?

**Comment by mattirn** [comment]
Sure, the choice of colour as integer is bad especially if you are going to add support for true colour for the rest I think I have just modified the existing implementation.

I do not know what we can exactly set using style strings and how... 
For example if we can define both foreground and background in a style then we can duplicate all the styles that we use inside menu list. 
An the other hand if style can define only foreground or background colour then I think we need to duplicate only menu list background colour.

**Comment by gnodet** [comment]
Fwiw, the styles are the ansi representation of whatever the terminal support (foreground, background, bold, blink, crossed out, italic, underling...).  So you can do whatever you want, the problem is that it's not really intuitive.
I'll first add some javadoc, but maybe we could find something more human readable than a list of integers...  Ideally, we should leverage the [`StyleResolver`](https://github.com/jline/jline3/blob/master/terminal/src/main/java/org/jline/utils/StyleResolver.java).

**Comment by mattirn** [comment]
Not tested much but seems to work... https://github.com/mattirn/jline3/commit/63b5c1182dd2e0d28ad25e4853e56f7154e33949

**Comment by gnodet** [comment]
I have something that leverages the `StyleResolver`, I'll try to push it tomorrow, but it's currently merged with the color support, so I need to split those...

**Comment by mattirn** [comment]
About human friendly styles also the latest nanorc format is quite good

```
[style1,style2,...,stylen],[foreground],[background]
```
where `stylei` are `bold`, `inverse`, `italic`, `underline`,... .  `foreground` and `background` are colours. Everything in style string are optional. [Nano.java#L1822-L1837](https://github.com/jline/jline3/blob/b77a0a8afea5a50a3cfa514e510ca214a0857900/builtins/src/main/java/org/jline/builtins/Nano.java#L1822-L1837)
