### ISSUE TITLE
Release 3.18.0

### ISSUE THREAD

**Issue by gnodet** [jline/jline3#621]
I've switched the milestone to 3.18.0 because there are incompatibilities, mainly caused by the 24-bit color support which changed the `AttributedStyle` fields from `int` to `long`.
@mattirn and others, let me know if you plan on working on additional stuff, else I'll try to cut a release asap.

**Comment by mattirn** [comment]
@gnodet I have not any pending works. Go ahead for next release!

**Comment by mattirn** [comment]
*Bugs*

- Inline completion re-sorts while tabbing when using groups (menu-list) #618
- Tab completion loses groups when tabbing (3.17 regression) (menu-list) #613
- JLine option AUTO_MENU_LIST: candidate list is wrongly positioned (menu-list) #600
- Failed to build JLine Graal demo: NoClassDefFoundError #615
- JLine nano xml highlighting differs considerable from GNU nano highlight (nanorc) #614
- Less fails with PatternSyntaxException (nanorc) #609
- Keep argument sorting in large argument list when formatting candidates for terminal into multiple columns #605
- Jline completion has logic issues with terminal and prompt widths (StringIndexOutOfBoundsException) #604
- Auto suggestion error when type "\\" character #602
- Autosuggestion choices are not refreshed after tab #545
- Windows gitbash: JLine will create dumb terminal if JNA lib is in classpath #599
- Display command is incorrect when use here document #607
- Windows CMD, redirecting input using JLine with Jansi fails #597
- Dumb terminal when piping input to console app disallows ANSI formatting #299
- readLine() ignores any text in the buffer when OEF is reached #298

*Enhancements and new features*

- Support terminal palette #620
- Support for 24-bit colours #619
- Show auto-suggestions when the reader starts reading #598
- Groovy REPL: highlight command and groovy language syntax using nanorc https://github.com/jline/jline3/commit/ca381eec4885fab0523a19718db1a3e0ec8cbea9
- Document how I/O error in LineReader.readLine is reported #608

**Comment by gnodet** [comment]
@mattirn the release is available on central
