### ISSUE TITLE
Change completer without recreating LineReader

### ISSUE THREAD

**Issue by Evynglais** [jline/jline3#625]
Hi,

Is there any way to update the available candidates without having to recreate the reader? Currently we have

`LineReader reader = LineReaderBuilder.builder().terminal(terminal).completer(completer).build();`

which works fine, but we have to recreate the reader whenever we update candidates (which we do often in our implementation). Is there any way to assign a completer to a built reader (or update the candidates inside the completer without rebuilding the reader)?

Thanks,
Evynglais

**Comment by mattirn** [comment]
You can use Java functional interfaces to update candidates inside the completer. See for example [StringsCompleter.java](https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/completer/StringsCompleter.java) that can be constructed using `Supplier<Collection<String>>`.

**Comment by Evynglais** [comment]
Hi, thanks for that response - I hadn't thought of doing something similar for candidates (and I'm surprised the existing implementation isn't there considering how useful and simple it was). I just created these two classes:

```
public class StringCompleterSupplier implements Supplier<Collection<Candidate>> {
        List<Candidate> candidates;

        @Override
        public Collection<Candidate> get() {
            return candidates;
        }

        public void setCandidates(List<Candidate> candidates) {
            this.candidates = candidates;
        }
    }
```

and then extended the StringCompleter to use it:

```
public class CustomStringCompleter extends StringsCompleter {

        private final Supplier<Collection<Candidate>> supplier;

        public StringCompleter(Supplier<Collection<Candidate>> supplier) {
            this.supplier = supplier;
        }

        @Override
        public void complete(LineReader reader, final ParsedLine commandLine, final List<Candidate> candidates) {
            assert commandLine != null;
            assert candidates != null;

            if (supplier.get() != null) {
                candidates.addAll(supplier.get());
            }
        }

    }
```

(I removed the part of `complete()` associated with the stringSupplier, since I never use strings).

Thanks again for your help,
Evynglais
