### ISSUE TITLE
Logs or println methods overrides my reader prompt.

### ISSUE THREAD

**Issue by portlek** [jline/jline3#630]
![image](https://user-images.githubusercontent.com/12835420/102900459-586be980-447d-11eb-957f-0327dda753c1.png)
![image](https://user-images.githubusercontent.com/12835420/102900467-5c980700-447d-11eb-8fec-8719bde0a25d.png)
[My terminal and reader code](https://github.com/shiruka/shiruka/blob/ad98a01fe860c4c18f7816556793a78074424bae/src/main/java/io/github/shiruka/shiruka/console/ShirukaConsole.java#L89)

**Comment by thetoothpick** [comment]
We've been running into this problem at my company when using loggers from asynchronous threads.  I hacked together a solution that duplicated the `LineReaderImpl` class to add more fine-grained support in the existing `printAbove()` method, which clears the screen, redraws it with the new output, and then adds the prompt to the end.  This keeps the prompt always visible at the end of the screen while log lines are added above it.

I had to additionally redirect the logger to an output stream wrapper which forwarded to this new `printAbove()` method.

I'll work on a PR to add proper support this weekend.

**Comment by gnodet** [comment]
@thetoothpick I don't really understand the idea at all.  AFAIK, the _print above_ operation can only be done with full lines because the `LineReader` will have to erase the prompt, print the lines, and redraw the lines.
So while the idea is not bad, the implementation has to buffer by lines and then use the existing `printAbove` method instead of defining a new `writeAbove`.

**Comment by gnodet** [comment]
The idea of the `WriteAboveStream` is definitely interesting, but it should be a `Writer` instead, or event better, a `PrintWriter`.  When flushing one or more line, it would call `LineReader.printAbove()`.

**Comment by mattirn** [comment]
Closed by pull request #649
