### ISSUE TITLE
Commands.history: Start Index from 0, not 1

### ISSUE THREAD

**Issue by morris821028** [jline/jline3#637]
Hi All,

I observe most of shell built-in command `history` label the entry from 1, but JLine gives 0 as defaults.

```bash
> history
    0  history
```

Expected:
```bash
> history
    1  history
```

Is it possible config the offset?

Thanks.

**Comment by mattirn** [comment]
No, it's not possible to configure history index to start from 1.
Anyway it is only transitory 'problem' when your history size has reached to `HISTORY_SIZE` (default 500) the history start index will be greater than zero.

It would be trivial to change index to start from 1 but 0 is more natural choice. The simplest way to make index start from 1 would be decrement by 1 user `history` command index inputs and when displaying record increment index by 1. As the index start of 0 does not cut away any functionality of the `history` command I was thinking not to introduce the change.
