### ISSUE TITLE
Use JLine DefaultPrint class to print table

### ISSUE THREAD

**Issue by Evynglais** [jline/jline3#638]
Hi,

I'm hoping to print a table with a similar style to what you printed using groovy-repl in #636, ideally without using the groovy-repl code as we don't currently implement it (if we can call/create a specific method, that would be fantastic). Would anyone be able to give any hints on how to do this, e.g. if I have three headers and a map of <row number, column values>? At the moment we have a basic console table printer that uses the LineReaderImpl println(), but it would be more useful to call an internal jLine table printer if it's available.

Any help is appreciated.
Thanks

**Comment by mattirn** [comment]
You do not need Groovy to use `DefaultPrinter`. You can construct your printer as
```
DefaultPrinter printer = new DefaultPrinter(configPath);    // you can set configPath=null if you do not use nanorc
```
and use it like shown here [Console.java#L194-L207](https://github.com/jline/jline3/blob/4ba4649ebd48ee9014b142659efeac367431ddba/console/src/test/java/org/jline/example/Console.java#L194-L207).

If you want to customize table highlighting you can create environment variable `PRNT_COLORS`. The default value of `PRNT_COLORS`:
https://github.com/jline/jline3/blob/4ba4649ebd48ee9014b142659efeac367431ddba/builtins/src/main/java/org/jline/builtins/Styles.java#L22

**Comment by mattirn** [comment]
If you are not using `SystemRegistry` in your REPL app and want to use `DefaultPrinter` then you must extend `DefaultPrinter` overriding:
1) method `terminal()`
2) method `highlightAndPrint(options, exception)` if you are going to print exceptions
3) method `defaultPrntOptions(skipDefault)` if you want to manage configurable printing options.

See an example in [Console.MyPrinter](https://github.com/jline/jline3/blob/0d63afbe3086a9e03e2fabeb876d5f60ea1077c3/console/src/test/java/org/jline/example/Console.java#L325-L348)
