### ISSUE TITLE
How to disable the prompt of multiple candidates

### ISSUE THREAD

**Issue by jxnu-liguobin** [jline/jline3#652]
In other words, I need to show all the candidates. (because all candidates cannot be displayed correctly in this terminal).

![image](https://user-images.githubusercontent.com/29496873/108292092-62d10800-71ce-11eb-940c-302e59c78a15.png)

**Comment by jxnu-liguobin** [comment]
It may have something to do with debug mode. After all, there are only six candidates and there is no need to prompt

**Comment by mattirn** [comment]
Probably because you are using dumb terminal and JLine creates it with zero column/row size. Set your terminal size after build as
```
            if (terminal.getWidth() == 0 || terminal.getHeight() == 0) {
                terminal.setSize(new Size(120, 40)); 
            }
```

**Comment by jxnu-liguobin** [comment]
Yes, it use dumb terminal when debug `scala repl`.  thanks
