### ISSUE TITLE
cursor position is not visible at command line 

### ISSUE THREAD

**Issue by kaushalkumar** [jline/jline3#655]
We are using jline-3.19.0, where we could not see the cursor position at command line. unavailability of cursor position makes it difficult to type (for e.g. fixing any typo in command). Please suggest how to get this visible.

**Comment by mattirn** [comment]
Which are OS and terminal you using?
Add line
```
System.out.println(terminal.getName() + ": " + terminal.getType());
```
after the line where you create your terminal. What does it output?

Have you tried different cursor types: vertical-line, underline or block?

**Comment by kaushalkumar** [comment]
I am using macOS Catalina (v 10.15.6). The output of  
`System.out.println(terminal.getName() + ": " + terminal.getType());` is `JLine terminal: xterm-256color`

I have not tried any other cursor type as i could not find any doc on how to set cursor types. Please suggest how to set different cursor types, I can give it a try.
I have picked the code from https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java and have modified it a bit to understand its usage. The current main method looks like this

    ```
public static void main(String[] args) {
        AnsiConsole.systemInstall();
        try {
            Supplier<Path> workDir = () -> Paths.get(System.getProperty("user.dir"));
            // set up JLine built-in commands
            Builtins builtins = new Builtins(workDir, null, null);
            // set up picocli commands
            CliCommands commands = new CliCommands();

            PicocliCommandsFactory factory = new PicocliCommandsFactory();

            CommandLine cmd = new CommandLine(commands, factory);
            PicocliCommands picocliCommands = new PicocliCommands(cmd);

            Parser parser = new DefaultParser();
            try (Terminal terminal = TerminalBuilder.builder().build()) {
                SystemRegistry systemRegistry = new SystemRegistryImpl(parser, terminal, workDir, null);
                systemRegistry.setCommandRegistries(builtins, picocliCommands);
                systemRegistry.register("help", picocliCommands);

                LineReader reader = LineReaderBuilder.builder()
                        .terminal(terminal)
                        .completer(systemRegistry.completer())
                        .parser(parser)
                        .variable(LineReader.LIST_MAX, 50)   // max tab completion candidates
                        .build();
                builtins.setLineReader(reader);
                factory.setTerminal(terminal);
                System.out.println(terminal.getName() + ": " + terminal.getType());

                String prompt = "prompt> ";
                String rightPrompt = null;
```

**Comment by mattirn** [comment]
[Change the Terminal window cursor on Mac](https://support.apple.com/en-za/guide/terminal/trml15226/2.10/mac/10.15)

**Comment by kaushalkumar** [comment]
hi @mattirn -  thanks for providing your input. The setting was already enabled in the terminal, however for some wierd reason the cursor prompt was not visible. When i restarted the terminal then the cursor blinking came back. I will keep an eye on this and if i find any observation then will post it here. Closing this ticket.
