### ISSUE TITLE
how to break out from top command

### ISSUE THREAD

**Issue by kaushalkumar** [jline/jline3#657]
What is the mechanism to come out of top command. When we use CTRL+C then the program exits. Is there a way to break top output without closing the program (prompt). Please suggest

**Comment by gnodet** [comment]
Pressing `q`should do the trick:
  https://github.com/jline/jline3/blob/master/builtins/src/main/java/org/jline/builtins/TTop.java#L601

**Comment by kaushalkumar** [comment]
thanks @gnodet
