### ISSUE TITLE
The next release

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#668]
@gnodet, the next version can be released when you find appropriate.

*Bugs*

- JLine history file seems to grow without limit #642
- After JLine has trimmed history history-search-backward widget does not work well #643
- Use new 24bit support when parsing ANSI sequences #641
- Fix case insensitive typo matching #647
- Fix PumpReader.read(CharBuffer) not being synchronized #660
- Command prnt style option does not work #661
- TailTipWidgets throws IndexOutOfBoundsException when descriptionSize set to 0 #645
- Groovy REPL demo erroneously can complete groovy statements in shell command #663

*Enhancements and new features*

- Add a PrintAboveWriter class to print text above the prompt #649
- Add a color field on the TerminalBuilder to control the dumb terminal #662
- CamelCase matcher has a poor performance #650
- CompletionMatcherImpl: adjust matcher functions execution order #648
- Use JLine DefaultPrinter class to print table #638
- DefaultPrinter: map print enable option for keys selection [`169f9cff`](https://github.com/jline/jline3/commit/169f9cff098e70fcd984fd29cec544b8d1cbfd07)
- Command colors: add option --ansistyles [`6c3cfb7f`](https://github.com/jline/jline3/commit/6c3cfb7f2ccc0b53dc5bd360fd0ca177253d8d4c)
- SystemHighlighter: use LS_COLORS rules to highlight command file args and option values [`3320df5f`](https://github.com/jline/jline3/commit/3320df5f74e2907cbd3b3ef8c4d347c9f24af235), [`5f2497dd`](https://github.com/jline/jline3/commit/5f2497dd059c19fa928e9cd728f72ab870e8e2ce)
- Unable to directly handle unknown commands in console #653
- Groovy REPL does not load classes from groovy sources #664
- Groovy REPL: purge dynamically created Script classes from classloader cache & add groovy command classloader [`8f092569`](https://github.com/jline/jline3/commit/8f0925699f964cb23ef9ea68482b74f6b5d16a23) , [`ead6de89`](https://github.com/jline/jline3/commit/ead6de895ae308023b74a045da830ddf833262dc), [`a3bf295e`](https://github.com/jline/jline3/commit/a3bf295e4f75c4121756c935309dda0165e732e4)
- Groovy REPL: add support for Groovy traits  [`9d05f0ae`](https://github.com/jline/jline3/commit/9d05f0aec2b024f83063e5209b2830c0c1a93d03) 
- Groovy REPL: add option syntheticMethodsCompletion [`427fbadf`](https://github.com/jline/jline3/commit/427fbadf6a017a38ff2bd203d7d7f455478d0304)
- Groovy REPL: improve package completion performance [`8daf2917`](https://github.com/jline/jline3/commit/8daf29171bd4df32fb8adf261d79f6ee58f5d2ea), [`1d9bb288`](https://github.com/jline/jline3/commit/1d9bb2884450aa25f204480689e75a5f480837e1)
- Groovy REPL: add inner class completion [`7df36e38`](https://github.com/jline/jline3/commit/7df36e38c5a61cb4738c3bc730d0a2c43f5736fc) 
- Groovy REPL: method tab completion fails complete obj. super class methods [`8dc496fb`](https://github.com/jline/jline3/commit/8dc496fbb844856104029c3c6735343408387a6a) 
- Groovy REPL: manage tab completions of dynamically loaded jars  [`92a63e14`](https://github.com/jline/jline3/commit/92a63e1494d7e24a9f36cf639257b181080a535f)
- Groovy REPL: add tab completions to classes that are created in REPL  [`513e6fd4`](https://github.com/jline/jline3/commit/513e6fd4ca3bb6821cb2fa24d56ca5092a56c3ec) 
- Groovy REPL: complete get meta methods also as identifiers [`6567d4bf`](https://github.com/jline/jline3/commit/6567d4bf7876fdecea85af8a970e42749711f1ff) 

*Upgrades*

- Upgrade Groovy to 3.0.8 [`278fac94`](https://github.com/jline/jline3/commit/278fac94e66e74bef2d34e73e0b5ebd5598eeca6) 
- Upgrade JNA to 5.8.0 [`8e9fc369`](https://github.com/jline/jline3/commit/8e9fc3697ae2a7695d867eb3c47199779285b087)
- Upgrade Jansi to 2.3.2 [`fac777f5`](https://github.com/jline/jline3/commit/fac777f5645f860b3379eda6d41b6e4736779b6b)

**Comment by gnodet** [comment]
JLine 3.20.0 is now available in maven central.
