### ISSUE TITLE
Read without adding to history

### ISSUE THREAD

**Issue by scgray** [jline/jline3#72]
It is useful to use the same console used at a general purpose prompt for also asking simple questions, like:

    1> foo
    2> bar
    3> \execute
    Are you sure? (Y/N): _

it would be nice to have the ability to disable history for these sorts of interaction -- at the very lead disable adding an entry to history.  Alternatively, it would be nice to include a No-Op history implementation that could be swapped out.

**Comment by gnodet** [comment]
You can do the following:
```
    public String readLine(String prompt, Character mask) throws IOException {
        try {
            reader.getVariables().put(LineReader.DISABLE_HISTORY, Boolean.TRUE);
            return reader.readLine(prompt, mask);
        } finally {
            reader.getVariables().remove(LineReader.DISABLE_HISTORY);
        }
    }
```

**Comment by scgray** [comment]
Ahh, I missed that variable.  Thanks!

**Comment by gnodet** [comment]
If the LineReader.HISTORY_FILE variable is not defined, the history will be in-memory only.  Isn't that sufficient as a kind-of no-op history ?

**Comment by scgray** [comment]
Yes, but in my case I want the history for some inputs but not for others, so I want to selectively turn history on or off prior to prompting.  The other option, I guess, is to use two LineReader's, but that seems like overkill.

**Comment by gnodet** [comment]
Change the `LineReader.DISABLE_HISTORY` variable value at will as shown in the first example, I think that's you easiest way.

**Comment by scgray** [comment]
Yep, that is what I did and it works great. Thanks!
