### ISSUE TITLE
SyntaxError does nothing

### ISSUE THREAD

**Issue by udoprog** [jline/jline3#74]
Hey,

`Parser#parse(...)` [specifically throws SyntaxError](https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/Parser.java#L13), but it is [actively being ignored by LineReaderImpl](https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L2497).

This is counter intuitive since `SyntaxError` contains fields that reports details about the error that occurred.
My workaround is to use an internal RuntimeException like SyntaxError that won't be ignored and that I can catch to report useful errors.

Is this intended?

**Comment by gnodet** [comment]
No it's not really intended.  I think I haven't really thought about how to handle such errors.
Do you have a use case, or a desired behavior ?

**Comment by gnodet** [comment]
Could it be related to issue #46 ?
I.e we could display the syntax error information below the buffer; if the user presses <enter> again, we could validate despite the error...

**Comment by udoprog** [comment]
No preference, basically I do this right now:
https://github.com/udoprog/heroic/blob/jline3/heroic-shell/src/main/java/com/spotify/heroic/HeroicInteractiveShell.java#L101

Just letting it through is fine by me. It might also be useful to install some specific mechanism for how to deal with syntax errors. But that might just obfuscate it more than necessary.

**Comment by gnodet** [comment]
Fixed by https://github.com/mattirn/jline3/commit/221f01cc196aa0e55964494f0ab91fe8b08f20a1
