### ISSUE TITLE
Certain characters not working on Czech QWERTY keyboard

### ISSUE THREAD

**Issue by lahodaj** [jline/jline3#747]
Some characters, like '{' cannot be typed (and a bit surprisingly not even pasted) on Czech QWERTY keyboard. These characters are input using AltGr+Shift. Looking at the code here:
https://github.com/jline/jline3/blob/92a63e1494d7e24a9f36cf639257b181080a535f/terminal/src/main/java/org/jline/terminal/impl/AbstractWindowsTerminal.java#L253

the code tries to detect AltGr, but it also checks that Shift is not pressed, so doing AltGr+Shift+{ is failing the check, and the character is not typed. If I remove the `| SHIFT_PRESSED` from the test, I can type the characters fine.

Is there a need for the test to include Shift? Will removing the Shift check break something?

Thanks!

This was originally reported for OpenJDK:
https://bugs.openjdk.java.net/browse/JDK-8272139

**Comment by gnodet** [comment]
I don't really see any problem in removing the check for the SHIFT key.  Would you mind raising a PR for that ?
