### ISSUE TITLE
The next release

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#765]
@gnodet, the next version can be released when you find appropriate.

*Bugs*
- Standard escape character (\\) doesn't seems to be handled correctly, fixes [#798](https://github.com/jline/jline3/issues/798) 
- Infinite loop in TerminalLine constructor, fixes [#751](https://github.com/jline/jline3/issues/751)
- Less method run(Source... sources) throws UnsupportedOperationException, fixes [#810](https://github.com/jline/jline3/issues/810)
- less pager does not work well when using InputStreamSource, fixes [#812](https://github.com/jline/jline3/issues/812)
- Scroll forward of the cli cause tailtips to collide with text, fixes [#738](https://github.com/jline/jline3/issues/738)
- Mandatory import of sun.misc, fixes [#758](https://github.com/jline/jline3/issues/758)
- Candidates customized order lost when tabbing through candidates, fixes [#763](https://github.com/jline/jline3/issues/763)
- LineReader Candidate: tests for sorting and potential int overflow fix ([#762](https://github.com/jline/jline3/pull/762))
- Tab candidate menu list exceeds from visible terminal display, fixes [#759](https://github.com/jline/jline3/issues/759)
- Error in custom command line highlighter let readLine() method in an unusable state, fixes [#741](https://github.com/jline/jline3/issues/741)
- Fix last line not displayed when scrolling using Display, fixes [#737](https://github.com/jline/jline3/issues/737)
- nano editor fails to highlight block comments, fixes [#753](https://github.com/jline/jline3/issues/753)
- Nano SyntaxHighlighter fails to highlight the line after the block comment, fixes [#743](https://github.com/jline/jline3/issues/743)
- Nano SyntaxHighlighter fails to highlight strings with line delimiters, fixes [#742
](https://github.com/jline/jline3/issues/742)
- lsStyle resolver defined as static field, fixes [#764](https://github.com/jline/jline3/issues/764)
- Fix Parser javadoc of ParseContext.SPLIT_LINE, fixes [#733](https://github.com/jline/jline3/issues/733)
- Groovy REPL: methods print and println appear twice in tab completion candidate list, fixes [#749](https://github.com/jline/jline3/issues/749)
- 3.20.0 Regression - Groovy REPL highlight syntax errors while typing is broken, fixes [#748](https://github.com/jline/jline3/issues/748)
- Groovy REPL: tab-completion does not complete all methods even if allMethodsCompletion=true, fixes [#745](https://github.com/jline/jline3/issues/745)
- Groovy REPL: prnt command parameter completion does not work well, fixes [#744](https://github.com/jline/jline3/issues/744)

*Enhancements and new features*
-  command less: manage object arguments [#811](https://github.com/jline/jline3/issues/811) 
- prnt command: add option --multiColumns ([#813](https://github.com/jline/jline3/pull/813))
- Support for comments in DefaultParser ([#731](https://github.com/jline/jline3/pull/731))
- SyntaxHighlighter: add parser to tokenize string literals and comments, fixes [#746](https://github.com/jline/jline3/issues/746)
- [Theme System](https://github.com/jline/jline3/wiki/Theme-System): use token names in highlight configurations in place of hard coded colors

*Breaking changes*

`SyntaxHighlighter` has been moved from `org.jline.builtins.Nano.SyntaxHighlighter` to `org.jline.builtins.SyntaxHighlighter`

**Comment by rinswind** [comment]
Will there be a release soon, as I need to run jline under Java 11 and I am blocked by #758?

**Comment by mattirn** [comment]
@gnodet also I start to be blocked by JLine. Would be great if you could release a new JLine!

**Comment by gnodet** [comment]
Sure, will do that this week.

**Comment by gnodet** [comment]
JLine 3.22.0 is released.  It should be available on maven central very shortly.
