### ISSUE TITLE
Entering Chinese on windows will cause garbled code

### ISSUE THREAD

**Issue by Ruokwok** [jline/jline3#766]
On the simplified Chinese version of windows, when you enter Chinese, you will get chaotic strings. I tried `chcp 65001` / `-Dfile.encoding=utf8` / `encoding("utf8")` and other methods, but they didn't solve the problem, or even got worse.

The problem only occurs on CMD and PowerShell of windows, and there is no problem in Linux or IDEA console.

My code is like this
```
Terminal terminal = TerminalBuilder.builder().encoding("gbk").build();
LineReader lineReader = LineReaderBuilder.builder().terminal(terminal).build();
while (true) {
    String line = lineReader.readLine(">");
    System.out.println(line);
}
```
It's not just input. If you change the above ">" to Chinese, it will also print "?????" or garbled.
Thank you.

**Comment by Ruokwok** [comment]
If I use the `encoding("utf8")` method, Chinese will become ???, and ??? is a common garbled content when reading a gbk encoded file with utf8. But I tried all kinds of methods, but they didn't solve the problem.

**Comment by mattirn** [comment]
@Ruokwok, simplified Chinese (GBK) code page is 936.
Enter the following command in the dos prompt:
```
\> chcp 936
```
Then launch your JLine app using java option `-Dfile.encoding=utf8`.

I have tested using JLine repl demo... at least now copy and paste Chinese characters works.
