### ISSUE TITLE
Can I use Jline to set the cursor position in the console like I can with C# with Console.SetCursorPosition(x,y)?

### ISSUE THREAD

**Issue by SpyderCoder** [jline/jline3#769]
I've been fiddling around making console games in Java but I ran into some hiccups like console flicker because of console screen clearing and while I did solve it using JNI my current solution has a drawback of only working on a Windows 64 bit system. 

I'm wondering if a feature that lets me set the cursor position in the console on Windows, OS X, and Linux exists as I can't find anything that seems to suggest that in the documentation.

**Comment by gnodet** [comment]
You can use
```
        terminal.puts(Capability.cursor_address, row, col);
```
