### ISSUE TITLE
How to highlight some words in the line that is entered using Jline?

### ISSUE THREAD

**Issue by PashaTurok** [jline/jline3#771]
[](https://stackoverflow.com/posts/71355920/timeline)I use Jline 3.21. This is how I read a line
```

var terminal = TerminalBuilder.terminal();
var lineReader = LineReaderBuilder.builder().terminal(terminal).build();
..
lineReader.readLine(...);
```

Now I want to highlight (for example with green color) some words while user is entering the line. Could anyone explain what is the right way to do it?

**Comment by PashaTurok** [comment]
Please, give me at least algorithm and class names that are used for such problems. Any help is highly appreciated.

**Comment by mattirn** [comment]
You have to implement [Highlighter](https://www.javadoc.io/doc/org.jline/jline/latest/org.jline/org/jline/reader/Highlighter.html) interface and set it to your lineReader:
```
var lineReader = LineReaderBuilder.builder().terminal(terminal).highlighter(highlighter).build();
```
Example implementation:
```
    public class MyHighlighter implements Highlighter {

        @Override
        public AttributedString highlight(LineReader reader, String buffer) {
            AttributedStringBuilder asb = new AttributedStringBuilder();
            asb.style(new AttributedStyle().foreground(AttributedStyle.GREEN));
            int idx = buffer.indexOf(" ");
            if (idx > 0) {
                asb.append(buffer.substring(0,  idx));
                asb.style(AttributedStyle.DEFAULT);
                asb.append(buffer.substring(idx));
            } else {
                asb.append(buffer);
            }
            return asb.toAttributedString();
        }

        @Override
        public void setErrorPattern(Pattern errorPattern) {}

        @Override
        public void setErrorIndex(int errorIndex) {}
    }
```

JLine has two implementations of `Highlighter`: [DefaultHighlighter](https://static.javadoc.io/org.jline/jline/latest/org.jline/org/jline/reader/impl/DefaultHighlighter.html) and [SystemHighlighter](https://www.javadoc.io/doc/org.jline/jline/latest/org.jline/org/jline/console/impl/SystemHighlighter.html) that is used in groovy REPL demo. See [wiki doc](https://github.com/jline/jline3/wiki/Highlighting%20and%20parsing#builtin-highlighters)

**Comment by PashaTurok** [comment]
@mattirn Thank you very much. This is what I needed.
