### ISSUE TITLE
Cannot contribute to wiki for History page

### ISSUE THREAD

**Issue by mikesamuel** [jline/jline3#772]
I'd like to flesh out the [History wiki entry](https://github.com/jline/jline3/wiki/History).   Current content

> TODO

I think it's set to only allow collaborators to be wiki editors.
I tried to fork so I could send a PR against the wiki, but my fork doesn't get wiki content.

I was thinking of briefly discussing:

- A short how to use *DefaultHistory* with JLine Reader.
  1. Make sure your reader associates a path to a user history file with the *LineReader.HISTORY_FILE* variable per https://github.com/jline/jline3/blob/c6ae2c1295c81893456a38ae69509693a690b50d/reader/src/main/java/org/jline/reader/impl/history/DefaultHistory.java#L52
  2. Shout out [net.harawata:appdirs](https://github.com/harawata/appdirs) to help pick an app-specific directory for user files in an OS-respectful manner.
  3. Create a [*DefaultHistory*](https://github.com/jline/jline3/blob/c6ae2c1295c81893456a38ae69509693a690b50d/reader/src/main/java/org/jline/reader/impl/history/DefaultHistory.java#L47-L49) instance.  If you don't pass in your line reader to *DefaultHistory*'s constructor, you'll need to `.attach` it.
  4. Read any existing history entries
  5. Do your line reading loop 
  6. On exit, write the new history
- Brief discussion of dealing with race conditions due to concurrent uses of jline backed tools.
- Brief discussion of how to avoid losing history if reader loop exits with exception.

**Comment by gnodet** [comment]
I just found the link to clone the wiki : https://github.com/jline/jline3.wiki.git

**Comment by mikesamuel** [comment]
I created a wiki on my fork and then did the below:
```bash
$ git remote add jline-jline3.wiki https://github.com/jline/jline3.wiki.git
$ git fetch jline-jline3.wiki
remote: Enumerating objects: 408, done.
remote: Total 408 (delta 0), reused 0 (delta 0), pack-reused 408
Receiving objects: 100% (408/408), 69.39 KiB | 623.00 KiB/s, done.
Resolving deltas: 100% (236/236), done.
From https://github.com/jline/jline3.wiki
 * [new branch]      master     -> jline-jline3.wiki/master
$ git merge jline-jline3.wiki/master
fatal: refusing to merge unrelated histories
$ git pull jline-jline3.wiki master --allow-unrelated-histories
From https://github.com/jline/jline3.wiki
 * branch            master     -> FETCH_HEAD
Auto-merging Home.md
CONFLICT (add/add): Merge conflict in Home.md
Automatic merge failed; fix conflicts and then commit the result.
```

Maybe that'll allow me to send a PR your way.  There may be odd merge conflicts.

**Comment by mikesamuel** [comment]
[The compare link](https://github.com/mikesamuel/jline3/wiki/History/_compare/28016354cb2b9cadd3659c251d735f66e00eebbf...4bdfd475da430ed22b6f5ec6adea7b7eb24de4bb) for wiki edits doesn't give the option of opening a PR, but the edits are available at https://github.com/mikesamuel/jline3/wiki/History

**Comment by gnodet** [comment]
Thx, I've integrated your changes on the wiki !
