### ISSUE TITLE
jansi-XXX-libjansi.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by robmarzialetti** [jline/jline3#778]
I am using a tool called "CommandBox" which, behind the scenes, uses Jline for its CLI.

I have no problem with CommandBox, which I have installed on some Linux and Windows servers.

In my last installation, however, on startup, I get this error:

```
root@server-# ./box
Failed to load native library: jansi-2.3.2-77fdf64ca7bda556-libjansi.so. osinfo: Linux / x86_64
java.lang.UnsatisfiedLinkError: /tmp/jansi-2.3.2-77fdf64ca7bda556-libjansi.so: /tmp/jansi-2.3.2-77fdf64ca7bda556-libjansi.so: failed to map segment from shared object

```
I think the error is due to some library that was not installed on the server, because I have no problems on other machines.

I tried:

=1

To upgrade to jline-3.21.0.jar with no success (CommandBox uses **jline-3.19.0.jar.**)

=2

To install some libraries:

```
apt-get install libjansi-java
ldconfig
```
without solution.

This is my environment:

```
CommandBox Version: 5.4.2 + 00453
Java Version: 11.0.14 (Ubuntu)
Java Path: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
OS Username: root
JLine Terminal: org.jline.terminal.impl.PosixSysTerminal
```

```
root@server-# uname -a
Linux 5.11.0-1029-gcp#33 ~ 20.04.3-Ubuntu SMP
x86_64 x86_64 x86_64 GNU/Linux
```

Any idea?

Many many thanks.

**Comment by bdw429s** [comment]
Subscribing :)

**Comment by mattirn** [comment]
See https://github.com/prestodb/presto/issues/13408

**Comment by bdw429s** [comment]
@mattirn CommandBox sets both of the following system properties
* `library.jansi.path`
* `jna.tmpdir`
 to a folder that the CLI has access to.  Would the `/tmp` permissions discussed in the presto ticket still apply here?  Are there new/different system properties I need to be setting?   I originally did this to solve permissions issues on locked down PCs.

**Comment by mattirn** [comment]
Yes, `/tmp` permissions will apply also here. See, the error message above: CLI is trying to load shared lib from `/tmp`. I'm not aware any system properties that could be used to resolve the problem.

**Comment by bdw429s** [comment]
@mattirn The `library.jansi.path` system property was given to me by @gnodet explicitly to override the location where the native libs were extracted to and used.  Please see this post from the JLine mailing list:
https://groups.google.com/g/jline-users/c/SXKPsQgZA-A/m/itukW7lKBwAJ

It sounds like this may be a regression if the overridden temp folder is no longer being used.

**Comment by mattirn** [comment]
Ok, then I think you should open the ticket in [Jansi](https://github.com/fusesource/jansi) project.

**Comment by bdw429s** [comment]
@robmarzialetti I have gotten a reply on the linked jansi ticket and he suggested using a different java system property. I have made this change on the bleeding edge builds of CommandBox in this ticket:

https://ortussolutions.atlassian.net/browse/COMMANDBOX-1480

Could you please test this for us?  If you're not in a position to test the bleeding edge, you can manually set the system property by placing a `commandbox.properties` file in the same folder as your `box` binary with the following:

```
jansi.tmpdir=/path/to/writable/dir/
```
and then restart the shell.  It sounds like the Jansi library should pick up that system property and use it instead of trying to write to your system `/tmp` folder.

**Comment by robmarzialetti** [comment]
Ok  @bdw429s 

I tried:
- with CommandBox 5.4.2 by setting the commandbox.proprierties file
- with CommandBox 5.6.0-alpha
it works fine either way like a charm!

Many many thanks!

**Comment by bdw429s** [comment]
Awesome, great work everyone! :wink:
