### ISSUE TITLE
Fix documentation links

### ISSUE THREAD

**Issue by renatoathaydes** [jline/jline3#78]
Hi,

I have been using JLine2 happily and am trying to migrate to JLine 3.

It's been really hard because of the lack of documentation and the API is now much less intuitive than before... maybe with more documentation that wouldn't be so much the case.

Anyway, this issue is just about the broken links I've found:

* in https://github.com/jline/jline3/wiki/Using-line-readers on the first paragraph, the link to `highlight and parsers` goes to `https://github.com/jline/jline3/wiki/Highlighting%20and%20parsing` which does not exist.
* in https://github.com/jline/jline3/wiki/LineReader#linereader-building-options the table links to `Completers`, `History`, `Highlighter`, `Parser`, go to https://github.com/jline/jline3/wiki/Completion, https://github.com/jline/jline3/wiki/History, https://github.com/jline/jline3/wiki/Highlighting%20and%20parsing, https://github.com/jline/jline3/wiki/Highlighting%20and%20parsing which do not exist, and the `Expander` link goes to the wrong place: https://github.com/jline/jline3/wiki/LineReader.
* in the same page, on the first line, the link to `LineReader` goes to https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/LineReader.java and on the second line, the `LineBuilderReader` link to  https://github.com/jline/jline3/blob/master/src/main/java/org/jline/reader/LineReaderBuilder.java both are broken and result in 404s.

Hope this helps, I would fix the wiki if the pages actually existed, but most of them simply don't seem to exist at all (except the Java classes which seem to have moved to different sub-modules).

Anyway, Merry Christmas.

**Comment by gnodet** [comment]
Right, the empty pages have not been created yet.
And yeah, the build has recently been changed into a multi-module build, so all links are broken.

**Comment by gnodet** [comment]
I've fixed the links and created the pages.
Obviously, the documentation is a bit crude, but I would welcome any patches...
Merry Christmas to you too !

**Comment by renatoathaydes** [comment]
I would patch if I actually knew how to use JLine 3 :) which is what I am trying to do... currently, I need to read the source?

**Comment by gnodet** [comment]
Maybe have a look at the [examples](https://github.com/jline/jline3/blob/master/builtins/src/test/java/org/jline/example/Example.java) ?

**Comment by gnodet** [comment]
The links have been fixed a while ago, so I'm closing this issue.

**Comment by gnodet** [comment]
Feel free to provide PR for documentation though ;-)

**Comment by renatoathaydes** [comment]
Is JLine2 development going to continue for some time yet? It seems you're diverging quite a lot from it with JLine 3, could the direction you're heading with it not be appropriate for all users? I for one like the previous API much better.

**Comment by gnodet** [comment]
If someone is willing to work on JLine2, I'd happily merge PR or give access.
What part of the API are you talking about specifically ?
