### ISSUE TITLE
Windows console output problem

### ISSUE THREAD

**Issue by gearhand** [jline/jline3#79]
Running Jline 3 Example from Windows 10 cmd. What I expected to have:
```
prompt> some input
======>"some input"
prompt>
```

But this is what I actually have:
```
prompt> some input
======>"some input"
prompt> ======>""
prompt>
```

In IDEA (under both Windows and Linux) and in Linux shell all works fine.
Both IDEA under Windows and cmd reports "Unable to create a system terminal, creating a dumb terminal"

**Comment by gnodet** [comment]
This look like a `\r / \n` problem at first glance. I'll have a quick look.

**Comment by gnodet** [comment]
Oh, on Windows, you need either the jansi or jna library on the classpath in order to get correct support.  Do you have one of those library ?

**Comment by gearhand** [comment]
Ok, with jna or jansi installed it works correctly. Thank you
