### ISSUE TITLE
Can't create system terminal with Windows 10 command prompt or PowerShell

### ISSUE THREAD

**Issue by kmecpp** [jline/jline3#791]
I'm using the following code:

```
public static void main(String[] args) throws Exception {
    Logger.getLogger("org.jline").setLevel(Level.ALL);
    TerminalBuilder.builder().system(true).build();
}
```

This generates the following ouput
```
Jul 17, 2022 11:32:30 AM org.jline.utils.Log logr
WARNING: input is tty: true
Jul 17, 2022 11:32:30 AM org.jline.utils.Log logr
WARNING: output is tty: true
Jul 17, 2022 11:32:30 AM org.jline.utils.Log logr
WARNING: Creating a dumb terminal
java.lang.IllegalStateException: Unable to create a system terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:329)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:271)
        at com.voidflame.servermanager.ServerManager.main(ServerManager.java:59)
```

This happens in my Windows 10 Command Prompt and PowerShell but in my Git Bash shell it runs correctly

These are the only dependencies in my build.gradle

```
shade 'org.fusesource.jansi:jansi:2.4.0'

shade 'org.jline:jline:3.21.0'
shade 'org.jline:jline-terminal-jansi:3.21.0'
```

**Comment by mattirn** [comment]
You probably don't have Jansi library in your classpath. See JLine README: [Jansi vs JNA](https://github.com/jline/jline3#jansi-vs-jna).

**Comment by kmecpp** [comment]
Jansi looks like its installed correctly

![image](https://user-images.githubusercontent.com/6520738/179416541-fac09b40-82df-45ba-ad41-f04c82c0666b.png)


![image](https://user-images.githubusercontent.com/6520738/179416653-287097cb-7420-42be-b872-683c4d35b835.png)

```
public static void main(String[] args) throws Exception {
    Logger.getLogger("org.jline").setLevel(Level.ALL);
    AnsiConsole.systemInstall();
    System.out.println(Ansi.ansi().fg(Color.RED).a("Hello").fgRgb(0, 255, 0).a(" World").reset());
    
    TerminalBuilder.builder().system(true).build();
}
```

**Comment by mattirn** [comment]
If  you have created a fat jar of your JLine app that might be the problem. JLine loads dynamically JNA/Jansi support classes using [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) and probably fails to load these from fat jar.

**Comment by kmecpp** [comment]
Ah I see. Thank you, Using a separate folder for the libraries works. I was using a fat jar and `java -jar <fat_jar>` to run the program.

Using the [Gradle Shadow plugin](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow) also fixed the problem, while still enabling me to package everything in a single jar. Turns out I was using a primitive script for packaging the libraries into the jar and wasn't properly adding everything that should have been in `/META-INF`
