### ISSUE TITLE
How to read output/ outputstream

### ISSUE THREAD

**Issue by AliAlbaity** [jline/jline3#793]
I am trying to write a test to assert that the output displayed by the terminal is as expected. 
```
InputStream io = new ByteArrayInputStream("help\n".getBytes(StandardCharsets.UTF_8));
ByteArrayOutputStream os = new ByteArrayOutputStream(); 
Terminal streamTerminal = TerminalBuilder.builder().system(false).streams(io, os).build();
```

This is my terminal currently. 

The command I am using is "help", I want to assert that the output is as expected by comparing it to a string. Is there a way I could do this using outputsreams or any other method possible?

**Comment by gnodet** [comment]
To test the `LineReader`, we're using the [`ReaderTestSupport` class](https://github.com/jline/jline3/blob/a8ce4e85b850c061ecb53278b4eafdb1572e7ff5/reader/src/test/java/org/jline/reader/impl/ReaderTestSupport.java), this may be useful for you as well.
