### ISSUE TITLE
Tailtip widgets overwrite entered line

### ISSUE THREAD

**Issue by valepakh** [jline/jline3#797]
This issue is reproduced on Windows in Command Prompt and Powershell, but, unlike https://github.com/jline/jline3/issues/794 it's not reproduced under Windows Terminal.
This could be reproduced used `jline-repl.bat jansi` in the demo folder.
Start by filling the screen with output from any command, like `alias`, then enable tailtip widgets using Alt-S.
Next, scroll the window so that the prompt is hidden below the bottom edge.
Press up arrow, it's already looks not good, the line from the widget appears underneath the completer suggestion.
![image](https://user-images.githubusercontent.com/8614891/185908461-d85aff25-8a9f-4d60-a06d-d0caffe8d0bb.png)
Now press tab
![image](https://user-images.githubusercontent.com/8614891/185908771-6637fa89-c083-494c-be10-00dec25f78ed.png)
Now the help in the tailtip widgets appears above the prompt, the prompt itself is hidden, the cursor is blinking in the empty space and the completer suggestion is below that.

**Comment by mattirn** [comment]
duplicate with #738
