### ISSUE TITLE
When invoking LineReader.readLine and set the 'mask' param, it doesn't seem to work

### ISSUE THREAD

**Issue by yogurtzzz** [jline/jline3#799]
For scenarios like typing in password, I want to hide the user's input. But the param 'mask' doesn't seem to work. My code is as below (Java), the version of JLine is 3.9.0
```java
Terminal terminal = TerminalBuilder.builder().build();
LineReader lineReader = LineReaderBuilder.builder().terminal(terminal).build();
String password = lineReader.readLine("Input Your Password", '*');
```

When I run the code, user's input is still echoed as plain text.
Is there any clue about this problem ?

**Comment by gnodet** [comment]
Could you check the implementation class of the `terminal` variable ?

**Comment by yogurtzzz** [comment]
It's `org.jline.terminal.impl.DumbTerminal`.
Plus, when run the code, there's a warning message "Unable to create a system terminal, creating a dumb terminal".
Is this the problem ?

**Comment by gnodet** [comment]
> It's `org.jline.terminal.impl.DumbTerminal`.
> Plus, when run the code, there's a warning message "Unable to create a system terminal, creating a dumb terminal".
> Is this the problem ?

Yes, definitely.  You need to raise the log level to DEBUG and use `-Dorg.jline.terminal.dumb=false` system property to forbid the creation of a dumb terminal.  Note that on windows, the `jansi` or `jna` library is required in order to create a useful terminal.

**Comment by yogurtzzz** [comment]
problem solved. many thanks !
![aceac09295bfb6d1df39dd53778ff98](https://user-images.githubusercontent.com/22660362/188445103-4564fb1e-676f-47d2-b8d6-a2462d66c8e7.png)
