### ISSUE TITLE
Update conemu capabilities

### ISSUE THREAD

**Issue by jvalkeal** [jline/jline3#800]
I was looking why cursor show/hide doesn't work in `conemu` but works fine in `cmd` and `powershell`. Looks like `windows-conemu.caps` is quite old and `conemu` has matured quite a bit since caps were updated. Essentially in repl demo `tput cursor_invisible` and `tput cursor_visible` doesn't work if type is `windows-conemu`. 

If I add below to `windows-conemu.caps` those those start to work.
```
civis=\E[?25l, cvvis=\E[?25h,
```
Looking at https://conemu.github.io/en/AnsiEscapeCodes.html#List_of_supported_codes I'm just wondering what else this caps file might be missing?

**Comment by mattirn** [comment]
Activate/restore xterm alternative buffer and save/restore cursor position (`enter_ca_mode`, `exit_ca_mode`) are also missing
```
smcup=\E[?1049h, rmcup=\E[?1049l
```
