### ISSUE TITLE
Leaving application causes console arrows / tabs to work incorrectly

### ISSUE THREAD

**Issue by frossm** [jline/jline3#819]
Hello.  I have a java console application that has been using jline-reader v3.21.0 without issue. 

Upon upgrading to v3.22.0, when I leave my java application, the arrow keys in my terminal no longer function.

Pressing up arrow, for example, gives me `[A` instead of showing the last command.  `Tab` will now insert tabs instead of completion.

I downgraded to v3.21.0 and everything is working again, but I wanted to report this.  For reference, the application is [RPNCalc](https://github.com/frossm/rpncalc) and I'm happy to try anything in my app to help troubleshoot.

For reference, I'm running Windows 11.  

Please let me know how I can help.

Thank you

Michael

**Comment by frossm** [comment]
In doing a quick test, I don't see this issue in bash on Ubuntu, but I probably need to look at it more closely.

**Comment by mattirn** [comment]
Tested on Windows `CMD` and `PowerShell`. I have been able to reproduce the fault only on Windows `CMD` when using with `Jansi`:
```
...\demo>jline-repl.bat jansi
```
As a work around you can fix your terminal settings after you exit from your app by entering command `reset`.
