### ISSUE TITLE
vi style editing in JLine3

### ISSUE THREAD

**Issue by user3477071** [jline/jline3#821]
As per
    https://github.com/jline/jline3/issues/230
inputrc support has been removed from JLine3.

The jshell command that is part of JDK uses JLine3 for line editing.

Is it possible to enable vi style line editing on the jshell command
through a configuration file used by JLine3?

**Comment by gnodet** [comment]
Note that `InputRC` support has been somewhat added back in #230 with https://github.com/jline/jline3/blob/jline-parent-3.22.0/builtins/src/main/java/org/jline/builtins/InputRC.java, though it's not called automatically.

Unfortunately, the _jshell_ tool does not seem to allow any external configuration, looking at https://github.com/openjdk/jdk/blob/master/src/jdk.jshell/share/classes/jdk/internal/jshell/tool/ConsoleIOContext.java.

**Comment by user3477071** [comment]
As per jshell docs at

> https://docs.oracle.com/en/java/javase/17/jshell/editing.html

Shell editing in JShell is built on JLine, which is functionally similar to BSD editline and GNU readline in Emacs mode.

If GNU readline in Emacs mode can be supported by JLine notwithstanding the limitation of

> Unfortunately, the jshell tool does not seem to allow any external configuration, looking at https://github.com/openjdk/jdk/blob/master/src/jdk.jshell/share/classes/jdk/internal/jshell/tool/ConsoleIOContext.java.

it is not clear why GNU readline in vi mode also be supported in similar fashion. 

Can JLine enable GNU readline in vi mode when $HOME/.inputrc is present?
