### ISSUE TITLE
Some characters display below prompt after tail_tip enabled.

### ISSUE THREAD

**Issue by sunyoupk** [jline/jline3#824]
I use jline3 with picocli on spring boot.
I have a question about TailTipWidgets.

I did tailTipWidgets.enable() in the code to use TailTipWidgets.

`TailTipWidgets tailTipWidgets = new TailTipWidgets(reader, systemRegistry::commandDescription, 5, TailTipWidgets.TipType.COMPLETER);
                tailTipWidgets.enable();`

I ran the program built with java -jar in macos terminal,
To test the provided "cls" command, I typed "cls" and entered the tab key.
Then, as in the attached image, 'q' characters are output in large quantities,
Below that, the available options for cls are shown.

I wonder if this phenomenon is my own problem or because of some setting to be displayed as 'q'.
If that's the case, I'm thinking there might be a way to set that option somewhere too.

<img width="1218" alt="tailtip" src="https://user-images.githubusercontent.com/4415162/219553726-a3b5cb12-42fe-44bd-bbf1-a67ff07051e3.png">

Can you provide a guide on how to do this?

**Comment by mattirn** [comment]
@sunyoupk for some reason the status bar delimiter character '─' is displayed as 'q'. Please, could you give more information to reproduce the problem: terminal/terminal emulator, terminal character encoding etc.
