### ISSUE TITLE
Merge ConsoleUI to provide interactive menus

### ISSUE THREAD

**Issue by MTyson** [jline/jline3#841]
I want to achieve an effect like so: https://www.npmjs.com/package/prompt-checkbox

But in Java.  (C'mon Java, you can do it).

**Comment by mattirn** [comment]
Yes, you can do it also in java... See #592 and my old pull request  [Upgrade JLine to 3.19.0 awegmann/consoleui#24](https://github.com/awegmann/consoleui/pull/24), which IMHO is working pretty well.

**Comment by MTyson** [comment]
Nice, thanks.  Does this attempt things like https://www.npmjs.com/package/inquirer, meaning, arrow key navigable select/multi-select?  
I've tried about half a dozen java libs and they all end up just being "menus" that select by means of typing in the option letter/num.

**Comment by MTyson** [comment]
It looks like it does indeed.  What is the quickest path to take from a vanilla JLine app to an app that can offer interactive menu prompts?

**Comment by lutzseverino** [comment]
I'm pretty confused right now, can someone point me in the right direction on (preferably) an explanation on how to do these sorts of things? As I understand, JLine is capable of reading UP, DOWN, and such keystrokes, I just _cannot_ for the life of me get it to work!

**Comment by MTyson** [comment]
My superficial understanding is that the JLine library does not handle single keystrokes but you can add a layer that will respond that way.  I think the second comment above demonstrates how to do that in the links.  Still looking.

**Comment by MTyson** [comment]
I'm actually writing a piece for InfoWorld on JLine, and I was hoping to include some fancy menu handling but I think I'll just go with entering text and hitting the enter key.

**Comment by MTyson** [comment]
I just got to look at ConsoleUI - it does exactly what we want. Thanks @mattirn @awegmann.

**Comment by lutzseverino** [comment]
So, to clear everything up: JLine doesn't provide this functionality on its own. Why isn't #24 getting merged?

**Comment by gnodet** [comment]
> So, to clear everything up: JLine doesn't provide this functionality on its own. Why did [#24](https://github.com/awegmann/consoleui/pull/24) never get merged?

That's not for us to answer. I suppose the project is not maintained anymore... However, if there's a will and if @awegmann is ok, we could merge ConsoleUI into a new JLine module and shut down the ConsoleUI project.

**Comment by awegmann** [comment]
Hi everybody. Mea culpa. ConsoleUI is not really maintained anymore from my side. I would be pleased, if the project can live directly with JLine. 
When I started ConsoleUI using JLine2 was the way to got, but the way I caught the keystrokes also felt a bit awkward. I knew, that JLine was not designed to allow this kind of usage. 
Which jline3 this part of the code also had to be changed. If ConsoleUI were a part of JLine, the integration would benefit. 
To answer your question, Guillaume: yes, I would like ConsoleUI to live its life in your project.

**Comment by gnodet** [comment]
> Hi everybody. Mea culpa. ConsoleUI is not really maintained anymore from my side. I would be pleased, if the project can live directly with JLine. When I started ConsoleUI using JLine2 was the way to got, but the way I caught the keystrokes also felt a bit awkward. I knew, that JLine was not designed to allow this kind of usage. Which jline3 this part of the code also had to be changed. If ConsoleUI were a part of JLine, the integration would benefit. To answer your question, Guillaume: yes, I would like ConsoleUI to live its life in your project.

Ok, thx for the quick reply !

@mattirn @lutzseverino do you want to take a look at creating a PR to merge ConsoleUI into JLine in a new module ?

**Comment by mattirn** [comment]
Ok, I can do a PR.
