### ISSUE TITLE
Behavior of parsing arguments with spaces produced by filename completion 

### ISSUE THREAD

**Issue by brett-smith** [jline/jline3#848]
Hi,

I am trying to use `picocli-shell-jline3` along with JLine to build an application that has command, argument and filename completion. I don't think that actually matters for the issue I am having, but it's worth mentioning.

Following the example given by `picocli-shell-jline3`, I am creating a `SystemRegistryImpl` and using its `execute()` method to execute a command string. A few `Completer` implementations are also added, one being `FileNameCompleter`. 

The bit of code where the trouble starts looks like this.

```
				var line = reader.readLine(getPrompt() + " ", rightPrompt, (MaskingCallback) null, null);
				if (line.length() > 0)
					exitCode = (int) systemRegistry.execute(line);
```

Say I want to get to a folder `/home/me/Desktop/Folder With Spaces`, if in my shell I type in ..

```
cd /home/me[Tab]
```

and then follow the tab completion until I get to the folder I want, I end up with ...

```
cd /home/me/Desktop/Folder\ With\ Spaces
```

This is of course perfectly valid.  I can see that the `ParsedLine` that comes out of `DefaultParser.parse()` is correct, containing two words, `cd` and the string `/home/me/Desktop/Folder With Spaces`. 

The problem seems to come at some point between the parser and the output `readLine()`. Inspecting the return value, you can see that it is `cd /home/me/Desktop/Folder With Spaces`. This means `SystemRegistry` will be unable to parse the string correctly.

I have looked for options or builder methods that might affect this behavior, but cannot see anything obvious. 

It does work as expected if you wrap the argument in quotes though, but I cannot see a way to wrap the completion results in quotes either. 

Any suggestions?

**Comment by mattirn** [comment]
@brett-smith, which JLine version are you using? I think this is fixed in #798.

**Comment by brett-smith** [comment]
I am on the latest that is in Maven Central, version 3.2.23. That does look a bit different, but It has given me a couple of things I could try.  Will do so and report back.

**Comment by brett-smith** [comment]
Thanks for the pointer. It  seems .. 

```java
option(LineReader.Option.DISABLE_EVENT_EXPANSION, true).
```

was all that's needed. I'll keep testing, but so far it seems to be fine with paths with spaces with both quoted arguments and escaped spaces.
