### ISSUE TITLE
Changing default colors for AUTO_MENU_LIST

### ISSUE THREAD

**Issue by vszitkey** [jline/jline3#850]
Hi, I would like to use AUTO_MENU_LIST option, but not with the default colors.

![image](https://github.com/jline/jline3/assets/125252416/7cf32e47-4e66-46d2-a162-1ed3993c71cd)

Way to do this was mentioned in https://github.com/jline/jline3/issues/582. But I no longer see `COMPLETION_COLOR_STARTING`, `COMPLETION_COLOR_DESCRIPTION` and `COMPLETION_LIST_BACKGROUND_COLOR` variables, so I tried to change them with following attempts, but without any success.

`LineReader reader = LineReaderBuilder.builder()`
                `.terminal(this.terminal)`
                `.option(LineReader.Option.AUTO_MENU_LIST, true)`
                `.variable(COMPLETION_STYLE_LIST_BACKGROUND, Colors.rgbColor("white"))`
                `.variable(COMPLETION_STYLE_BACKGROUND, Colors.rgbColor("white"))`
                `.completer(completer)`
                `.build();`

Most likely I am missing something trivial, any advice? Thanks

**Comment by mattirn** [comment]
@vszitkey , the `LineReader` variables that control menu list styles have a prefix  `COMPLETION_STYLE_LIST_`  as an example `COMPLETION_STYLE_LIST_STARTING`, `COMPLETION_STYLE_LIST_DESCRIPTION` , `COMPLETION_STYLE_LIST_BACKGROUND` etc, see #617.

**Comment by vszitkey** [comment]
Thank you very much @mattirn :)
