### ISSUE TITLE
LineReader distrup the user command during writing?

### ISSUE THREAD

**Issue by emrahtema** [jline/jline3#851]
I could not figured out how to use LineReader that the automatic outputs will not distrup the user command during typing.
The scenario to make this happen:
- User is typing something
- LineReader outputs the system status periodically
- When LineReader outputs the status, user typing is distrupted
- (Extra) The command prompt is not at the bottom, it comes after outputs (it will be good to make it at bottom but how?)

I am running the code at IntellijIDE. The Java code for JLine 3.20.0 is that:

```
public class JLineExample {
    public static void main(String[] args) {
        try {
            SharedProperties.terminal = TerminalBuilder.terminal();
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }
        SharedProperties.lineReader = LineReaderBuilder.builder()
            .terminal(SharedProperties.terminal)
            .history(new DefaultHistory())
            .build();
        // Start the system status printer thread
        SystemStatusPrinter statusPrinter = new SystemStatusPrinter();
        Thread statusThread = new Thread(statusPrinter);
        statusThread.start();
        try {
            String prompt = "Enter your input: ";
            while (true) {
                String line = SharedProperties.lineReader.readLine(prompt, null);
                if ("exit".equalsIgnoreCase(line.trim())) {
                    break;
                }
                SharedProperties.print("You entered: " + line);
            }
        } catch (UserInterruptException | EndOfFileException e) {
            System.out.println("Application interrupted.");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Close the terminal and stop the system status printer thread
            statusPrinter.stop();
            terminal.close();
        }
    }
}

class SystemStatusPrinter implements Runnable {
    private volatile boolean running = true;
    public void stop() {
        running = false;
    }
    @Override
    public void run() {
        while (running) {
            SharedProperties.print("System Status: ?");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}

class SharedProperties {
    public static Terminal terminal;
    public static LineReader lineReader;
    public static void print (String text) {
        lineReader.getTerminal().writer().print(text);
        lineReader.getTerminal().writer().flush();
    }
}
```

**Comment by gnodet** [comment]
See #666, #630

**Comment by emrahtema** [comment]
I tried but it doesn't print when I call to print the system status like in the code above:

`SharedProperties.print("System Status: ?");`

From:
```
public static void print (String text) {
    PrintAboveWriter printAbove = new PrintAboveWriter(lineReader);
    printAbove.write(w.toCharArray());
    printAbove.flush();
}
```
Adding JNA as a dependency solved my problem but I think PrintAboveWriter must be a better solution. Do you have any idiea what is the matter with my code?

**Comment by gnodet** [comment]
> I tried but it doesn't print when I call to print the system status like in the code above:
> 
> `SharedProperties.print("System Status: ?");`
> 
> From:
> 
> ```
> public static void print (String text) {
>     PrintAboveWriter printAbove = new PrintAboveWriter(lineReader);
>     printAbove.write(w.toCharArray());
>     printAbove.flush();
> }
> ```
> 
> Adding JNA as a dependency solved my problem but I think PrintAboveWriter must be a better solution. Do you have any idiea what is the matter with my code?

JNA or jansi is required in order to have proper support on Windows.

**Comment by emrahtema** [comment]
Should I understand that:
If we are working with Linux terminal, PrintAboveWriter must be used. If we are working on Windows terminal, JNA or Jansi is required, PrintAboveWriter is not required in this case?

**Comment by gnodet** [comment]
> Should I understand that:
> If we are working with Linux terminal, PrintAboveWriter must be used. If we are working on Windows terminal, JNA or Jansi is required, PrintAboveWriter is not required in this case?

No, `PrintAboveWriter` is always required for your use case.  JNA or Jansi is required for proper JLine support on Windows and recommended on Linux.

**Comment by emrahtema** [comment]
`PrintAboveWriter` is not working even though I added JNA. I am still using `lineReader.getTerminal().writer().print(text);` after adding JNA and solved my problem.

**Comment by gnodet** [comment]
Ok, not sure how it works for you.
Your example gives the following for me:
```
➜  jline3 git:(master) ✗ java -cp jline/target/jline-3.23.1-SNAPSHOT.jar:reader/target/test-classes --add-opens java.base/java.lang=ALL-UNNAMED org.jline.example.JLineExample
System Status: ?Enter your input: System Status: ?System Status: ?System Status: ?dsaSystem Status: ?System Status: ?
```
which is clearly what I expect from the code.

By using the following code:
```
    public static void print(String text) {
        PrintWriter writer = new PrintWriter(new PrintAboveWriter(lineReader));
        writer.println(text);
        writer.flush();
    }
```
I end up with the correct output:
```
➜  jline3 git:(master) ✗ java -cp jline/target/jline-3.23.1-SNAPSHOT.jar:reader/target/test-classes --add-opens java.base/java.lang=ALL-UNNAMED org.jline.example.JLineExample
System Status: ?
System Status: ?
System Status: ?
System Status: ?
System Status: ?
System Status: ?
Enter your input: dsa
```

**Comment by emrahtema** [comment]
It is great. I was using `PrintAboveWriter` wrong. Thanks a lot.

**Comment by creperozelot** [comment]
yo tried this code above but isnt working for me does anyone know why? I use this code :

```java
public static void Serverlog(String server, String msg) {
        LineReader lineReader = CloudMain.getInstance().getTerminal().getLineReader();
        //lineReader.printAbove(Color.translate(server + " -> " + msg));


        PrintWriter writer = new PrintWriter(new PrintAboveWriter(lineReader));
        writer.println(Color.translate(server + " -> " + msg));
        writer.flush();
    }
```

**Comment by gnodet** [comment]
> yo tried this code above but isnt working for me does anyone know why? I use this code :
> 
> ```java
> public static void Serverlog(String server, String msg) {
>         LineReader lineReader = CloudMain.getInstance().getTerminal().getLineReader();
>         //lineReader.printAbove(Color.translate(server + " -> " + msg));
> 
> 
>         PrintWriter writer = new PrintWriter(new PrintAboveWriter(lineReader));
>         writer.println(Color.translate(server + " -> " + msg));
>         writer.flush();
>     }
> ```

You need to explain what you expect and what you get, else the code itself does not help much.

**Comment by creperozelot** [comment]
Sorry, tried to log a message in the console, what worked so far but if I enter something and a new log displays on the log, my input gets cleared. What it shouldn't. Do you eventually know why or what I did wrong?
