### ISSUE TITLE
vi-style paren blinking causes unwanted "echo" in emacs

### ISSUE THREAD

**Issue by hvesalai** [jline/jline3#864]
When using `sbt` from emacs (through `sbt-mode`), the terminal is set not to echo. However, if the input line contains parenthesis, the line is partially repeated.

```
scala> "foo"
val res1: String = foo

scala> "foo)bar"
"foo)val res2: String = foo()
```

Note on the last line the additional `"foo)`, which is not expected.

The behavior is possibly caused by the vi-style paren blinking: https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L2167

The question is, why is this functionality enabled for dumb terminals in sbt? Is there something wrong in how sbt uses jline3 or is it a bug in jline3 proper? I am available to help with a bug fix as soon as I understand which module to change.

**Comment by hvesalai** [comment]
More specifically the erroneous output appears after calling `redisplay()` here: 

https://github.com/jline/jline3/blob/jline-parent-3.18.0/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L2197

I wonder if that line should be removed since `redisplay()` is conditionally called also after applying the widgets here:

https://github.com/jline/jline3/blob/jline-parent-3.18.0/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L705

Or if the condition `if (!dumb) {` should be moved to be within `redisplay` so handling of dumb terminal would be localized to one place.

**Comment by hvesalai** [comment]
@gnodet I would like to make a pull request to fix this, but would want some feedback on the approach before that. Would you have a moment to advice.

**Comment by gnodet** [comment]
> @gnodet I would like to make a pull request to fix this, but would want some feedback on the approach before that. Would you have a moment to advice.

With a dumb terminal, I'm even wondering if the read line loop which read bindings and evaluates widgets should be called at all.  Given there's no line edition possible, I think the `LineReader` should simply read the full line and return it without any processing.  Thoughts ?

**Comment by hvesalai** [comment]
That's true. However, history should be stored because sbt provides even dump terminals ways to access the history.

**Comment by hvesalai** [comment]
OTOH. Things such as history expansion would work equally on DUMP terminals (i.e. `!!`)

**Comment by hvesalai** [comment]
How about if we make a keymap for DUMP that only has a few things that will work in that environment?

**Comment by gnodet** [comment]
> How about if we make a keymap for DUMP that only has a few things that will work in that environment?

Yes, sounds a good idea.

**Comment by hvesalai** [comment]
Actually we already have there the `safe()` keybindings. Couldn't we use just that for DUMP?

**Comment by hvesalai** [comment]
ping @gnodet. I would appreciate feedback on my fix (I have tested it on the repl and it works). Besides the `master`, I would also like it to be ported to the next release if that is not from `master`

**Comment by hvesalai** [comment]
This wasn't completed after all. The reason is that https://github.com/jline/jline3/blob/jline-parent-3.24.1/reader/src/main/java/org/jline/reader/impl/InputRC.java#L47 undoes what we implemented in LineReaderImpl.

The line in

**Comment by hvesalai** [comment]
@gnodet can you reopen the issue, it needs more fixing, see above comment
