### ISSUE TITLE
Confusion about terminal capabilities causes jline to print `[30m~[0mnull null[?2004h>....`

### ISSUE THREAD

**Issue by cpitclaudel** [jline/jline3#865]
While trying to run `sbt` (the Scala build system), specifically `sbt console`, on CI on a private Gitlab instance, I ran into the following output:

```
Welcome to Scala 3.3.1 (17, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
[30m~[0mnull null[?2004h>....
```

Scala uses jline3 under the hood, and the problem was fixed by forcing sbt to consider the current terminal as `dumb` using `-Djline.terminal=none`.  However, there may still be a bug here to fix?  

The second part of the prompt comes from https://github.com/jline/jline3/blob/bd9536644c5a0ec8b268e5f12c92c3d33f9c8d00/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L3934 ; the two `null` come from the call to `freshLine` after turning on bracketed paste mode (`Capability.carriage_return` returns null).

**Comment by gnodet** [comment]
`jline.terminal=none` is a JLine 2 option.
Afaik, that's still the one in use:
```
➜  ~ sbt
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.9.6  (this may take some time)...
[info] [launcher] getting Scala 2.12.18 (for sbt)...
[info] Updated file /Users/gnodet/project/build.properties: set sbt.version to 1.9.6
[info] welcome to sbt 1.9.6 (Oracle Corporation Java 21)
[info] loading project definition from /Users/gnodet/project
[info] Updating 
https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom
  100.0% [##########] 19.4 KiB (218.3 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of 
[info] Fetched artifacts of 
[info] set current project to gnodet (in build file:/Users/gnodet/)
[info] sbt server started at local:///Users/gnodet/.sbt/1.0/server/353f3920bb9500f42abf/sock
[info] started sbt server
sbt:gnodet> 
```
I've seen https://github.com/som-snytt/scala/commit/77c7c477cc9ba6212bfd3ced3d034b70c6ea1b9f but I don't think it has been integrated into the main `sbt` branch.

Anyway, I'll provide a fix for this problem, but if sbt does not upgrade, it won't help much...

**Comment by gnodet** [comment]
Also, bracketed paste mode and fresh lines are not called at all on dumb terminals:
https://github.com/jline/jline3/blob/05ee05dbc7b9c5ba9df8358d8a9fc58227101ed0/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L631C22-L641

Which exact `sbt` version are you using ?

**Comment by gnodet** [comment]
> I can try to make a minimal repro for this if you think it's worth looking into (It doesn't happen locally for me; only on a CI machine)

Yes, a few steps (shell commands) to reproduce the problem would help.  I suppose the CI environment may be reproduced by redirecting the input/output from file.

**Comment by gnodet** [comment]
I will close this bug issue as inactive and non-reproducible. Please chime in if anyone has more information.
