### ISSUE TITLE
Completer not invoked when line is empty

### ISSUE THREAD

**Issue by adibacco** [jline/jline3#88]
I expected to see candidates when pressing the TAB at the beginning of a line. I mean, the line is still empty and in this case the completer seems not to be invoked at all.

Is this an expected behavior? It would be really useful to have such a feature.

**Comment by gnodet** [comment]
Yes, that's the expected behavior. It allow pasting scripts indented with tabs quite easily.  This behavior is the same as the `zsh` shell btw.

**Comment by adibacco** [comment]
Is it not possible to tweak something to have anyway the completion?

**Comment by gnodet** [comment]
Sure it is, it's controlled by the `LineReader.Option.INSERT_TAB`.

**Comment by adibacco** [comment]
Your suggestion did the trick.
Again, awesome library. Thx.
