### ISSUE TITLE
How to have a Candidate that only suggests but doesn't complete

### ISSUE THREAD

**Issue by adibacco** [jline/jline3#89]
I tried to add a Candidate with **complete** parameter set to false and I expected to see just a suggestion (with a description) but without auto-completion. 

The **complete** parameter seems not to work or meant for this purpose.

**Comment by gnodet** [comment]
Right, the `complete` parameter of the `Candidate` means that the candidate is a fully well formed completion candidate, so that jline will add a space if selected as a completion.

If you want to disable auto-completion, you can try turning off the `Option.AUTO_MENU` option.

**Comment by adibacco** [comment]
I'm not sure I understood exactly. 
I would need something a little bit different from a Candidate. The user should type a numerical value but it would be nice to have a Suggestion more than a Candidate and I though that a Candidate with **complete** set to **false** would have did the trick.

**Comment by gnodet** [comment]
Ah, some kind of candidate that would appear in the completion list, but not actually complete ?
Can you try giving a "" value with a non-empty description ? The user should see the description, but I'm not quite sure what the exact behavior would be.
An alternative would be to write a custom highlighter or display it below the editing line, but both ways are slightly more complicated to implement. 
Let me know if the empty value for the candidate works...

**Comment by adibacco** [comment]
I tried having a Candidate with "" value and it didn't work but reading the code we found that something like this can work and it works (adding two candidates, last is fake):

```
                } else if (line.words().get(1).equals("txFreq")) {
                    candidates.add(new Candidate("1", "descr", null, "frequency in MHz", null, null, false));
                    candidates.add(new Candidate("2", "", null, "", null, null, false));
                }
```

**Comment by gnodet** [comment]
I've slightly changed the code so that a candidate with an empty value will do what you want, i.e. display but not complete.

**Comment by adibacco** [comment]
Thx very much for your help.

Regards,
Antonio.
