### ISSUE TITLE
Jni provider fails on linux

### ISSUE THREAD

**Issue by jvalkeal** [jline/jline3#896]
I'm still debugging this issue on my side but I wanted to throw this out here if it immediately rings a bell.

When trying to use `3.24.1` I'm getting into trouble with tests(where I don't have a proper tty). I get `jni` and `exec` and then `jni` fails with `newTerminal` with

```
java: symbol lookup error: /tmp/jlinenative-3.24.1-e342cc4f6f2aa9de-libjlinenative.so: undefined symbol: openpty
```
![jline-error-1](https://github.com/jline/jline3/assets/50398/74fd4a3f-cd8e-4a7d-b1e0-fb542fc1638d)

If I run my cli in a real terminal and attach debugger, I have `jni`, `jansi`, `jna` and `exec` but `jni` doesn't fail with `sysTerminal` and I get `PosixSysTerminal`.

![jline-error-2](https://github.com/jline/jline3/assets/50398/12c557c2-c1c1-4722-b00d-c4f1cc13d84e)

I'm on `Ubuntu 18.04.6 LTS` in this system.

**Comment by jvalkeal** [comment]
So it looks to be `CLibrary.openpty()` in `LinuxNativePty.open()` which throws that hard error if `org.jline:jline-terminal-jna` is in a classpath. If `jna` is not in a classpath then `newTerminal` throws `NoClassDefFoundError` and JLine catches that and moves on.

**Comment by gnodet** [comment]
Not sure to understand, is the problem with the JNI provider or the JNA provider ? Or are those two different problems ?

**Comment by jvalkeal** [comment]
I'm a bit rusty with this jni stuff so give me some rope here. Looks like when this `/tmp/jlinenative-3.24.1-e342cc4f6f2aa9de-libjlinenative.so` is extracted and used this call

https://github.com/jline/jline3/blob/bf698ba5fe46e190616dce9284c92e8e49079c15/terminal-jni/src/main/java/org/jline/terminal/impl/jni/linux/LinuxNativePty.java#L46-L51

doesn't work. Looking ldd:

```
$ ldd /tmp/jlinenative-3.24.1-e342cc4f6f2aa9de-libjlinenative.so
	linux-vdso.so.1 (0x00007fff87b3c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc9d0365000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc9d0959000)
```
I don't see it linking to `libutil` where I think `openpty` is. If I do:
```
export LD_PRELOAD=/lib/x86_64-linux-gnu/libutil.so.1
```
before build then the error goes away.

**Comment by gnodet** [comment]
Sorry for the delay.  The thing I'm wondering about, is how to change the makefile so that the libraries are linked with `libutil`...

**Comment by dattasid** [comment]
You may need to load required libraries explicitly whenever you use Linker.nativeLinker() . Linker.defaultLookup() behaves differently depending on architecture, I dont think it is reliable.
