### ISSUE TITLE
Error split?

### ISSUE THREAD

**Issue by super-admi** [jline/jline3#897]
`String line = "find object type name revision select attribute[Object Name]";
`
call:

`public static List<String> getWords(String line) {
        Parser parser = getParser();
        ParsedLine parsedLine = parser.parse(line, 0);
        return parsedLine.words();
    }
`  
but, the words is:
...,  attribute[Object,  Name]

**Comment by mattirn** [comment]
@super-admi , that is correct behaviour i.e. your method should return the list of words:
```
find, object, type, name, revision, select, attribute[Object, Name]
```
