### ISSUE TITLE
Use logger instead of System.out/System.err in JLineNativeLoader

### ISSUE THREAD

**Issue by tincore** [jline/jline3#907]
jline 3.24.1

Motivation from this request: I'm experiencing cases where jline new native libraries are forbidden to be loaded because of corporate security software installed on user machines. Basically, that software prevents execution of `dll` files on `tmp` directory (in Windows user/Temp).

As part of the terminal available provider detection process  `JLineNativeLoader.loadNativeLibrary()` can be called one or multiple times.  For each failed call messages are displayed in System.err/System.out.  It seems like there is no way (except upfront disabling `exec` and `jni` provider) to prevent this messages polluting application startup.

By using logger instead of System.out/System.err we would have the possibility to, optionally, hide those non critical errors from console.

**Comment by gnodet** [comment]
Sure, can you point to the message displayed to sysout/syserr ? Or maybe raise a PR ?
That said, there's also a way to extract the library to a given directory and point to that one instead of letting the loader extract the binary DLL from inside the jar and loading it.

**Comment by tincore** [comment]
Thanks for the response.

This particular error comes from `UnsatisfiedLinkError`

I think that something like the following snippet should be fine. Could be that Warning is more adequate than error though.

```
    /**
     * Loads native library using the given path and name of the library.
     *
     * @param libPath Path of the native library.
     * @return True for successfully loading; false otherwise.
     */
    private static boolean loadNativeLibrary(File libPath) {
        if (libPath.exists()) {

            try {
                String path = libPath.getAbsolutePath();
                System.load(path);
                nativeLibraryPath = path;
                return true;
            } catch (UnsatisfiedLinkError e) {
                logger.log(Level.SEVERE, "Failed to load native library:%s. osinfo: %s".formatted(libPath.getName(), OSInfo.getNativeLibFolderPathForCurrentOS()), e);
                return false;
            }

        } else {
            return false;
        }
    }
```

I've already implemented an equivalent temporary hack on my side as I don't have jline as direct dependency.
