### ISSUE TITLE
Writing to a concrete terminal row

### ISSUE THREAD

**Issue by PavelTurk** [jline/jline3#908]
I want to create terminal progress bar and place this bar at the bottom of the screen. For example like this:

![xUd8n](https://github.com/jline/jline3/assets/10261361/84c181d5-94b8-4de0-bd9b-7f98f6082c0f)

As I understand I need to get concrete row in terminal and modify it. Could anyone say how to do it in jline?

**Comment by mattirn** [comment]
@PavelTurk, I think you can do it using [Status](https://www.javadoc.io/doc/org.jline/jline/latest/org/jline/utils/Status.html).

**Comment by gnodet** [comment]
Please reopen if needed.
