### ISSUE TITLE
Mouse events not working in Ubuntu 14.04 default terminal.

### ISSUE THREAD

**Issue by lvivtotoro** [jline/jline3#91]
This simple code:

	Terminal term = TerminalBuilder.terminal();
	MouseEvent event = term.readMouseEvent();
	term.writer().append(event.getButton() + "").flush();
The above code freezes and doesn't do anything. (I can't even do CTRL+C to terminate it)
I'm using the latest jLine version, Java 8.

**Comment by gnodet** [comment]
That's not really designed to work this way.
You first need to call:
```
term.trackMouse(Terminal.MouseTracking.Normal);
```

Then, when the terminal receives a mouse event, i.e. the input stream contains the `key(term, Capability.key_mouse)` sequence, you can call the `term.readMouseEvent()` method.

I'll add some javadoc to the Terminal mouse support methods, as it's obviously lacking.

**Comment by gnodet** [comment]
Have a look at the `mousetrack` example which constantly displays the last mouse event to the upper right corner of the terminal:
  https://github.com/jline/jline3/blob/2c74096936c293ec6717e0f7ade3246590e2ac73/builtins/src/test/java/org/jline/example/Example.java#L246-L262

**Comment by gnodet** [comment]
I'm closing this issue.  Please reopen or open a new issue if you still have problems.
