### ISSUE TITLE
QUIT signal handler ignored

### ISSUE THREAD

**Issue by sdaschner** [jline/jline3#912]
Registering a handler for QUIT is ignored in my example applications. The other handlers (INT for `Ctrl+c`, TSTP, etc.) work as expected.

Example:

```java
        try (Terminal terminal = TerminalBuilder.terminal()) {
            terminal.enterRawMode();

            terminal.handle(Terminal.Signal.INT, signal -> handleIntSignal());
            terminal.handle(Terminal.Signal.QUIT, signal -> {
                System.out.println("QUIT");
            });
            terminal.handle(Terminal.Signal.TSTP, signal -> {
                System.out.println("TSTP");
            });
            
            // ... input is read via terminal.reader().read(long) FWIW
```

When running the app, `Ctrl+c` and `Ctrl+z` result in the expected behavior (e.g. printing `TSTP`), but hitting `Ctrl+\` prints a thread dump instead of `QUIT`.

This might be connected to #441.

I'm using Jline `3.23.0` and `OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)`

**Comment by gnodet** [comment]
Can you try with `TerminalBuilder.builder().nativeSignals(true).build()` when building the terminal ?

**Comment by sdaschner** [comment]
I've just tried, but no change and same outcome for the `Ctrl+\` / `QUIT` signal... The `TSTP` signal is still handled as expected / as before.

**Comment by gnodet** [comment]
Could you provide a small reproducer maybe ? Is that specific to given a platform / environment ?

**Comment by sdaschner** [comment]
Sure, added [here](https://github.com/sdaschner/quarkus-playground/blob/912-quit-signal-handler/src/main/java/com/sebastian_daschner/client/TestCommand.java):

```bash
# checkout branch 912-quit-signal-handler
mvn clean package
java -jar target/quarkus-app/quarkus-run.jar
# press Ctrl+Z, prints TSTP
# press Ctrl+\, prints thread dump (instead of QUIT)
# press Ctrl+C, exists
```

**Comment by gnodet** [comment]
It seems the only way to disable thread dump is to use [`-Xrs`](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html#BABHDABI) JVM option, but this means providing a replacement to catch and dispatch those which JLine does not support.
Bottom line, I don't think it's possible to intercept the `QUIT` signal in JLine.

**Comment by sdaschner** [comment]
Hmm ok, thanks.

I'm just curious how the `Signal.QUIT` handler got in in the first place? Wasn't this tested in some Java runtime or does it depend on the JVM being used...?

**Comment by gnodet** [comment]
> Hmm ok, thanks.
> 
> I'm just curious how the `Signal.QUIT` handler got in in the first place? Wasn't this tested in some Java runtime or does it depend on the JVM being used...?

I was wondering the exact same thing when I looked at it yesterday... I don't recall...

**Comment by gnodet** [comment]
Ah, I think I know.  It does work if the client is not a JVM.  For example, you can connect to a JLine based virtual terminal using an openssh client.  In such case, the correct signal will be sent through the terminal and be caught and handled by the terminal.
