### ISSUE TITLE
Some 3.25.0 artifacts missing from central

### ISSUE THREAD

**Issue by jvalkeal** [jline/jline3#926]
I don't know what should be in central compared to previous versions but these can't be found:

```
jline
jline-builtins
jline-console
jline-demo
jline-native
jline-reader
jline-remote-telnet
jline-style
jline-terminal-jna
```

**Comment by gnodet** [comment]
Don't trust the index pages.
All the artifacts are available:
  https://central.sonatype.com/artifact/org.jline/jline/3.25.0
