### ISSUE TITLE
Add support for monitoring window size changes.

### ISSUE THREAD

**Issue by Irineu333** [jline/jline3#929]
I'm new to the world of command line programs, so I don't know how hard it is to implement this (or even if it's possible). But I would like there to be a way to monitor changes in screen size, to adjust the screen in real time, like ncdu, htop, and midnight commander do.

**Comment by jvalkeal** [comment]
Jline can dispatch signals and it would be `WINCH` in this case. https://en.wikipedia.org/wiki/Signal_(IPC)#SIGWINCH

**Comment by Irineu333** [comment]
Thank you @jvalkeal, that solved my problem!
