### ISSUE TITLE
Issue With Resizing Command Prompt With Status Bar

### ISSUE THREAD

**Issue by philiprichens** [jline/jline3#939]
I've attached a short test program which shows the issue when using 3.25.1. When the status bar is visible, resizing a Command Prompt on Windows causes the status bar to be repeated across the window.

Here's a screen shot showing the result.

![ScreenShot-StatusBar](https://github.com/jline/jline3/assets/54800013/10524a60-6310-4908-86b5-a0537411fca0)

```
import java.io.IOException;
import java.util.Collections;
import org.jline.reader.LineReader;
import org.jline.reader.LineReaderBuilder;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import org.jline.utils.AttributedStringBuilder;
import org.jline.utils.Log;
import org.jline.utils.Status;

public class TestStatusBar {

    public static void main(String[] args) throws IOException {
        TestStatusBar tester = new TestStatusBar();
        tester.processInput();
    }

    private final Terminal terminal;
    private final LineReader reader;
    private Status status;
    
    public TestStatusBar() throws IOException {
        terminal = TerminalBuilder.builder().build();
        Log.info(terminal.getClass().getSimpleName());
        reader = LineReaderBuilder.builder()
                .terminal(terminal)
                .build();
    }

    public void processInput() {
        while (true) {
            String line = reader.readLine("TESTSTATUSBAR> ");
            if (status == null) {
                status = Status.getStatus(terminal, true);                        
            }
            AttributedStringBuilder attribStringBuilder = new AttributedStringBuilder();
            attribStringBuilder.append("something for the status bar: " + line);
            status.update(Collections.singletonList(attribStringBuilder.toAttributedString()));
            if (line.equalsIgnoreCase("QUIT")) {
                System.exit(0);
            }
        }
    }
}
```

**Comment by mattirn** [comment]
@philiprichens , after a resize, you need to redraw the terminal, see #902.

**Comment by philiprichens** [comment]
Playing with this some more, I can see that it is the redrawing of the status bar that is making a mess of the terminal window, and jline is at least in control of that. I can improve things somewhat if I override handleSignal like this:-

        @Override
        protected void handleSignal(Terminal.Signal signal) {            
            if (signal == Terminal.Signal.WINCH) {
                Status status = Status.getStatus(terminal, true);
                status.update(Collections.singletonList(new AttributedStringBuilder().toAttributedString()));
            }
            super.handleSignal(signal);
            if (signal == Terminal.Signal.WINCH) {
                Status status = Status.getStatus(terminal, false);
                AttributedStringBuilder attribStringBuilder = new AttributedStringBuilder();
                attribStringBuilder.append("something for the status bar");
                status.update(Collections.singletonList(attribStringBuilder.toAttributedString()));
            }
        }        

However, there is then a problem with the prompt disappearing that I am unsure how to resolve. Perhaps one of the jline contributors will know what to do to mend that?

This is at least enough to make me think it should be possible to resolve this issue successfully within jline. It is such a shame at the moment, because it does makes the status bar rather unusable.

**Comment by gnodet** [comment]
@philiprichens could you give a try to the #969 PR to see if that improve things ?  It's not perfect, but it fixes a bunch of problems I think.
