### ISSUE TITLE
Support for Java versions less than 8?

### ISSUE THREAD

**Issue by drosenbauer** [jline/jline3#98]
I'm stuck writing an interface in a version of Java less than 8, thanks to third-party requirements. I can use (and in fact am using) JLine2, which doesn't have this version requirement. I'd like to stay up to date with the latest and greatest if I can.

Is there a technical reason Java 8 was chosen?

**Comment by gnodet** [comment]
It may be possible to leverage https://github.com/orfjackal/retrolambda to bring back some Java 7 support.  Do you want to investigate that ?

**Comment by drosenbauer** [comment]
Hm, sure, I'll give it a shot!

**Comment by gnodet** [comment]
Possible fix at https://github.com/jline/jline3/tree/jdk7
Though I'm not sure we should provide it directly given some dependencies also require jdk 8.

**Comment by frog-o** [comment]
I was trying to use this on android and doing a quick google search tells me from one of the commit I read android only "support java 5" but sometimes "java 7 " works.  also the link does not work

**Comment by gnodet** [comment]
I've pushed the branch correctly so https://github.com/jline/jline3/tree/jdk7 should work.
