### ISSUE TITLE
Tests getting weird characters in the output

### ISSUE THREAD

**Issue by lahodaj** [jline/jline3#982]
I think this is happens typically in tests, not so important in real uses. Caused by:
https://github.com/jline/jline3/pull/975

When the `Display` is set to size `0x0`, it used to have `Integer.MAX_VALUE-1` columns, and `1` row. #975 changed that to `1` column, `1` row, which, by itself seems to make sense. But, there's some special handling when writing at the very right edge of the terminal:
https://github.com/jline/jline3/blob/84eea316ea37d9e4dcb83a6c7e0400268bc5dbfe/terminal/src/main/java/org/jline/utils/Display.java#L312

So, some tests, which effectively run with `Display` size `0x0` get the internal size of `1x1`, and write odd number of character then get ` \b` in the output, which they didn't before. And it is hard to defend adding these characters to the expected test output. Not sure at this time what is the more appropriate way out of this, but though I would report it.

To see the problem, try to add this test into `reader/src/test/java/org/jline/reader/impl/LineReaderTest.java`:
```
    @Test
    public void x() throws IOException {
        ByteArrayInputStream in = new ByteArrayInputStream(new byte[] {'\n'});
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (Terminal terminal = new DumbTerminal(in, out)) {
            LineReader r = new LineReaderImpl(terminal);
            r.readLine("123");
            String written = new String(out.toByteArray());

            assertEquals("123", written);
        }
    }
```

**Comment by gnodet** [comment]
> I think this is happens typically in tests, not so important in real uses. Caused by: #975
> 
> When the `Display` is set to size `0x0`, it used to have `Integer.MAX_VALUE-1` columns, and `1` row. #975 changed that to `1` column, `1` row, which, by itself seems to make sense. But, there's some special handling when writing at the very right edge of the terminal:
> 
> To see the problem, try to add this test into `reader/src/test/java/org/jline/reader/impl/LineReaderTest.java`:
> 
> ```
>     @Test
>     public void x() throws IOException {
>         ByteArrayInputStream in = new ByteArrayInputStream(new byte[] {'\n'});
>         ByteArrayOutputStream out = new ByteArrayOutputStream();
>         try (Terminal terminal = new DumbTerminal(in, out)) {
>             LineReader r = new LineReaderImpl(terminal);
>             r.readLine("1234");
>             String written = new String(out.toByteArray());
> 
>             assertEquals("1234", written);
>         }
>     }
> ```

The test succeeds for me on master on MacOS...

**Comment by lahodaj** [comment]
Uh, sorry. Just before submitting I was double-checking the behavior for various lengths of the prompt, an accidentally copied the version which prints `1234`. The prompt length must be odd to see the problem, i.e. either `123` or `12345` (or similar). I've fixed the test in the original comment, removing the `4` from the prompt.

Sorry for the trouble.
