### ISSUE TITLE
JLine 3.1.x adds extra space after prompt

### ISSUE THREAD

**Issue by grgrzybek** [jline/jline3#99]
Just run Felix framework 5.6.x with these bundles in `bundles` dir:
* jline-3.1.3.jar
* org.apache.felix.gogo.command-1.0.2.jar
* org.apache.felix.gogo.jline-1.0.2.jar
* org.apache.felix.gogo.runtime-1.0.2.jar

**Comment by gnodet** [comment]
Could you try with the following ?
  * clone and build https://github.com/jline/jline3/tree/3.1.x
  * run ./demo/jline-gogo.sh
I can't replicate the problem, it may be system dependent.  
What's your OS / terminal ?

**Comment by grgrzybek** [comment]
You're right - works fine under `gnome-terminal`, broken under `terminator`.
````
[ggrzybek@everfree] /data/ggrzybek/sources/github.com/jline/jline3 
$ ./demo/jline-gogo.sh 
Classpath: /data/ggrzybek/sources/github.com/jline/jline3/demo/../jline/target/jline-3.2.0-SNAPSHOT.jar:/data/ggrzybek/sources/github.com/jline/jline3/demo/target/lib/org.apache.felix.gogo.runtime-1.0.2.jar:/data/ggrzybek/sources/github.com/jline/jline3/demo/target/lib/org.apache.felix.gogo.jline-1.0.2.jar
Launching Gogo JLine...
____________________________
Welcome to Apache Felix Gogo

g!  $COLUMNS                                                            17:45:31
80
g!  system:                                                             17:45:33
g!                                                                      17:45:41
gosh: stopping framework
[ggrzybek@everfree] /data/ggrzybek/sources/github.com/jline/jline3 
$ echo $COLUMNS 
80
[ggrzybek@everfree] /data/ggrzybek/sources/github.com/jline/jline3 
$ 
````

even if I see COLUMNS=80 under bash and jline shell. There are two spaces after `g!` and when I typed `system:` and then `<TAB>`, cursor was positioned **on** `:` instead of **after** `:`.

**Comment by grgrzybek** [comment]
both terms report:
````
17:48 $ echo $TERM
xterm-256color
````

**Comment by gnodet** [comment]
I reproduced the error on terminator / OS X.  It seems to be a regression caused by #25

**Comment by gnodet** [comment]
@PerBothner any idea ?
At first glance, it seems to be caused by https://github.com/jline/jline3/blob/master/terminal/src/main/java/org/jline/utils/Display.java#L447-L448 which in this case, only move the cursor left by one and not two as the code suggests.

**Comment by PerBothner** [comment]
There seems to be two different terminators: [one mostly written in Java](https://code.google.com/archive/p/jessies/wikis/Terminator.wiki) and [one based on Gnome terminal](https://gnometerminator.blogspot.com/p/introduction.html). I'm not sure which one I tried (`terminator --version` prints out "1.91" but has no "About" or "Help" menu), and it may not be the same one you're using.

At least when it comes to he terminator installed by Fedora, it is clear that it is nowhere near xterm-compatible. Try running vttest and you'll find failures starting with the very first test. To what extent should we cater to broken terminal emulators?  Maybe if they're very popular or many people are stuck with it - but is terminator in that category? This bug should be reported to the terminator authors.


Is there a way we can detect terminator, and turn off right-margin wrapping in that case, since terminator doesn't seem to handle that in an xterm-compatible (or vt100-compatible) way?  Or ask people to change `TERM` to something more accurate?

**Comment by gnodet** [comment]
It seems that using ```TERM=rxvt``` works better for me. 
@grgrzybek can you check the same on your side ?

**Comment by grgrzybek** [comment]
`TERM=rxvt` didn't help.

I use:
````
$ terminator --version
terminator 0.98
$ rpm -qf `which terminator`
terminator-0.98-2.fc23.noarch
````

and you've convinced me to stop ;) Closing this issue as it's not `jline3` related.

**Comment by PerBothner** [comment]
Here is a test shell (bash) command:

    echo -en "123456789A123456789B123456789C123456789D123456789E123456789F123456789G123456789H\e[D_\n\n"

If you execute this on an 80-column-wide terminal, it should look like:

       123456789A123456789B123456789C123456789D123456789E123456789F123456789G12345678_H

That is: After writing H you're at the right margin.  If  you move one column left, you do *not* end up before the 'H', as you might expect, but before the '9' to its left.  This is how xterm-compatible (and vt100-compatible) terminals behave.  Specifically, column indexes range from 1 to 80.  There is no extra index for the position "after the last column". Writing a character in the right-most column does *not* change the column index (as used for calculating relative motion). Instead, it sets a special "wrap" bit.  The mysterious logic in `moveVisualCursorTo` deals with this artifact.

This test worked on the 'terminator' command I have accessible on Fedora - but perhaps you have the "other" terminator?

**Comment by grgrzybek** [comment]
@PerBothner thanks for hints. On `gnome-terminal` I saw:
````
123456789A123456789B123456789C123456789D123456789E123456789F123456789G123456789_
````
On `terminator`:

**Comment by PerBothner** [comment]
When I do  dnf provides /usr/bin/terminator on Fedora 25 I strangely get 3 matches:

    terminator-1.91-2.fc25.noarch : Store and run multiple GNOME terminals in one
                              : window
    Repo        : @System
    terminator-0.98-4.fc25.noarch : Store and run multiple GNOME terminals in one
                              : window
    Repo        : fedora
    terminator-1.91-2.fc25.noarch : Store and run multiple GNOME terminals in one
                              : window
    Repo        : updates

I think you need to get a newer copy of Terminator.

**Comment by grgrzybek** [comment]
First I should get newer Fedora ;) I waited for new machine though...

**Comment by grgrzybek** [comment]
But thanks for help and great explanation

**Comment by grgrzybek** [comment]
on terminator-1.91 [from here](https://launchpad.net/terminator/+download
) it works fine. Thanks again for your time!

**Comment by grgrzybek** [comment]
on terminator-1.91 [from here](https://launchpad.net/terminator/+download
) it works fine. Thanks again for your time!
